In [ ]:
!pip -q install \
gensim \
pyLDAvis \
openpyxl

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# ============================================================
# NG04-1 — Imports and Paths
# ============================================================

from pathlib import Path
import json
import warnings

import numpy as np
import pandas as pd

from gensim.models import LdaModel
from gensim.corpora import Dictionary
from gensim.models.coherencemodel import CoherenceModel

warnings.filterwarnings("ignore")

print("Imports completed.")

Imports completed.

In [ ]:
# ============================================================
# NG04-1B — NewsGroupsTopicEval Paths
# ============================================================

BASE_DIR = Path(
    "/content/drive/MyDrive/LDAChatGPT/NewsGroupsTopicEval"
)

DATA_DIR = BASE_DIR / "data"
MODEL_DIR = BASE_DIR / "models"
VECTOR_DIR = BASE_DIR / "vectors"
ANALYSIS_DIR = BASE_DIR / "analysis"

ANALYSIS_DIR.mkdir(parents=True, exist_ok=True)

CONFIG_FILE = BASE_DIR /"config/config.json"

print("BASE_DIR     :", BASE_DIR)
print("DATA_DIR     :", DATA_DIR)
print("MODEL_DIR    :", MODEL_DIR)
print("VECTOR_DIR   :", VECTOR_DIR)
print("ANALYSIS_DIR :", ANALYSIS_DIR)

assert BASE_DIR.exists(), "NewsGroupsTopicEval folder not found."

print("\n✓ Folder structure validated.")

BASE_DIR     : /content/drive/MyDrive/LDAChatGPT/NewsGroupsTopicEval
DATA_DIR     : /content/drive/MyDrive/LDAChatGPT/NewsGroupsTopicEval/data
MODEL_DIR    : /content/drive/MyDrive/LDAChatGPT/NewsGroupsTopicEval/models
VECTOR_DIR   : /content/drive/MyDrive/LDAChatGPT/NewsGroupsTopicEval/vectors
ANALYSIS_DIR : /content/drive/MyDrive/LDAChatGPT/NewsGroupsTopicEval/analysis

✓ Folder structure validated.

In [ ]:
# ============================================================
# NG04-2 — Load Configuration
# ============================================================

with open(CONFIG_FILE, "r", encoding="utf-8") as f:
    CONFIG = json.load(f)

RANDOM_SEED = CONFIG["random_seed"]
N_FOLDS = CONFIG["n_folds"]

TOPIC_MIN = CONFIG["topic_min"]
TOPIC_MAX = CONFIG["topic_max"]

TOPIC_LIST = list(range(TOPIC_MIN, TOPIC_MAX + 1))

LDA_PASSES = CONFIG["lda_passes"]
LDA_ITERATIONS = CONFIG["lda_iterations"]
LDA_CHUNKSIZE = CONFIG["lda_chunksize"]

ALPHA = CONFIG["lda_alpha"]
ETA = CONFIG["lda_eta"]

LDA_UPDATE_EVERY = CONFIG["lda_update_every"]
LDA_DECAY = CONFIG["lda_decay"]
LDA_OFFSET = CONFIG["lda_offset"]

TOP_WORDS = CONFIG["top_words"]

print("=" * 70)
print("NG04 CONFIGURATION")
print("=" * 70)

print(f"Dataset       : {CONFIG['dataset_name']}")
print(f"Folds         : {N_FOLDS}")
print(f"Topic range   : {TOPIC_MIN}–{TOPIC_MAX}")
print(f"Experiments   : {N_FOLDS * len(TOPIC_LIST)}")
print(f"LDA passes    : {LDA_PASSES}")
print(f"LDA iterations: {LDA_ITERATIONS}")
print(f"Chunksize     : {LDA_CHUNKSIZE}")
print(f"Alpha         : {ALPHA}")
print(f"Eta           : {ETA}")
print(f"Top words     : {TOP_WORDS}")

assert ALPHA == "symmetric"
assert ETA == "symmetric"

print("\n✓ NG04 configuration loaded successfully.")

======================================================================
NG04 CONFIGURATION
======================================================================
Dataset       : 20_Newsgroups
Folds         : 5
Topic range   : 2–100
Experiments   : 495
LDA passes    : 20
LDA iterations: 400
Chunksize     : 2000
Alpha         : symmetric
Eta           : symmetric
Top words     : 20

✓ NG04 configuration loaded successfully.

In [ ]:
# ============================================================
# NG04-3 — Inspect NG03 Outputs
# ============================================================

print("=" * 70)
print("MODEL DIRECTORY")
print("=" * 70)

if MODEL_DIR.exists():
    for p in sorted(MODEL_DIR.rglob("*")):
        if p.is_file():
            print(p.relative_to(BASE_DIR))

print("\n" + "=" * 70)
print("VECTOR DIRECTORY")
print("=" * 70)

if VECTOR_DIR.exists():
    for p in sorted(VECTOR_DIR.rglob("*")):
        if p.is_file():
            print(p.relative_to(BASE_DIR))

print("\n" + "=" * 70)
print("ANALYSIS DIRECTORY")
print("=" * 70)

if ANALYSIS_DIR.exists():
    for p in sorted(ANALYSIS_DIR.rglob("*")):
        if p.is_file():
            print(p.relative_to(BASE_DIR))

======================================================================
MODEL DIRECTORY
======================================================================
models/Fold_1/K_10/lda_model
models/Fold_1/K_10/lda_model.expElogbeta.npy
models/Fold_1/K_10/lda_model.id2word
models/Fold_1/K_10/lda_model.state
models/Fold_1/K_100/lda_model
models/Fold_1/K_100/lda_model.expElogbeta.npy
models/Fold_1/K_100/lda_model.id2word
models/Fold_1/K_100/lda_model.state
models/Fold_1/K_11/lda_model
models/Fold_1/K_11/lda_model.expElogbeta.npy
models/Fold_1/K_11/lda_model.id2word
models/Fold_1/K_11/lda_model.state
models/Fold_1/K_12/lda_model
models/Fold_1/K_12/lda_model.expElogbeta.npy
models/Fold_1/K_12/lda_model.id2word
models/Fold_1/K_12/lda_model.state
models/Fold_1/K_13/lda_model
models/Fold_1/K_13/lda_model.expElogbeta.npy
models/Fold_1/K_13/lda_model.id2word
models/Fold_1/K_13/lda_model.state
models/Fold_1/K_14/lda_model
models/Fold_1/K_14/lda_model.expElogbeta.npy
models/Fold_1/K_14/lda_model.id2word
models/Fold_1/K_14/lda_model.state
models/Fold_1/K_15/lda_model
models/Fold_1/K_15/lda_model.expElogbeta.npy
models/Fold_1/K_15/lda_model.id2word
models/Fold_1/K_15/lda_model.state
models/Fold_1/K_16/lda_model
models/Fold_1/K_16/lda_model.expElogbeta.npy
models/Fold_1/K_16/lda_model.id2word
models/Fold_1/K_16/lda_model.state
models/Fold_1/K_17/lda_model
models/Fold_1/K_17/lda_model.expElogbeta.npy
models/Fold_1/K_17/lda_model.id2word
models/Fold_1/K_17/lda_model.state
models/Fold_1/K_18/lda_model
models/Fold_1/K_18/lda_model.expElogbeta.npy
models/Fold_1/K_18/lda_model.id2word
models/Fold_1/K_18/lda_model.state
models/Fold_1/K_19/lda_model
models/Fold_1/K_19/lda_model.expElogbeta.npy
models/Fold_1/K_19/lda_model.id2word
models/Fold_1/K_19/lda_model.state
models/Fold_1/K_2/lda_model
models/Fold_1/K_2/lda_model.expElogbeta.npy
models/Fold_1/K_2/lda_model.id2word
models/Fold_1/K_2/lda_model.state
models/Fold_1/K_20/lda_model
models/Fold_1/K_20/lda_model.expElogbeta.npy
models/Fold_1/K_20/lda_model.id2word
models/Fold_1/K_20/lda_model.state
models/Fold_1/K_21/lda_model
models/Fold_1/K_21/lda_model.expElogbeta.npy
models/Fold_1/K_21/lda_model.id2word
models/Fold_1/K_21/lda_model.state
models/Fold_1/K_22/lda_model
models/Fold_1/K_22/lda_model.expElogbeta.npy
models/Fold_1/K_22/lda_model.id2word
models/Fold_1/K_22/lda_model.state
models/Fold_1/K_23/lda_model
models/Fold_1/K_23/lda_model.expElogbeta.npy
models/Fold_1/K_23/lda_model.id2word
models/Fold_1/K_23/lda_model.state
models/Fold_1/K_24/lda_model
models/Fold_1/K_24/lda_model.expElogbeta.npy
models/Fold_1/K_24/lda_model.id2word
models/Fold_1/K_24/lda_model.state
models/Fold_1/K_25/lda_model
models/Fold_1/K_25/lda_model.expElogbeta.npy
models/Fold_1/K_25/lda_model.id2word
models/Fold_1/K_25/lda_model.state
models/Fold_1/K_26/lda_model
models/Fold_1/K_26/lda_model.expElogbeta.npy
models/Fold_1/K_26/lda_model.id2word
models/Fold_1/K_26/lda_model.state
models/Fold_1/K_27/lda_model
models/Fold_1/K_27/lda_model.expElogbeta.npy
models/Fold_1/K_27/lda_model.id2word
models/Fold_1/K_27/lda_model.state
models/Fold_1/K_28/lda_model
models/Fold_1/K_28/lda_model.expElogbeta.npy
models/Fold_1/K_28/lda_model.id2word
models/Fold_1/K_28/lda_model.state
models/Fold_1/K_29/lda_model
models/Fold_1/K_29/lda_model.expElogbeta.npy
models/Fold_1/K_29/lda_model.id2word
models/Fold_1/K_29/lda_model.state
models/Fold_1/K_3/lda_model
models/Fold_1/K_3/lda_model.expElogbeta.npy
models/Fold_1/K_3/lda_model.id2word
models/Fold_1/K_3/lda_model.state
models/Fold_1/K_30/lda_model
models/Fold_1/K_30/lda_model.expElogbeta.npy
models/Fold_1/K_30/lda_model.id2word
models/Fold_1/K_30/lda_model.state
models/Fold_1/K_31/lda_model
models/Fold_1/K_31/lda_model.expElogbeta.npy
models/Fold_1/K_31/lda_model.id2word
models/Fold_1/K_31/lda_model.state
models/Fold_1/K_32/lda_model
models/Fold_1/K_32/lda_model.expElogbeta.npy
models/Fold_1/K_32/lda_model.id2word
models/Fold_1/K_32/lda_model.state
models/Fold_1/K_33/lda_model
models/Fold_1/K_33/lda_model.expElogbeta.npy
models/Fold_1/K_33/lda_model.id2word
models/Fold_1/K_33/lda_model.state
models/Fold_1/K_34/lda_model
models/Fold_1/K_34/lda_model.expElogbeta.npy
models/Fold_1/K_34/lda_model.id2word
models/Fold_1/K_34/lda_model.state
models/Fold_1/K_35/lda_model
models/Fold_1/K_35/lda_model.expElogbeta.npy
models/Fold_1/K_35/lda_model.id2word
models/Fold_1/K_35/lda_model.state
models/Fold_1/K_36/lda_model
models/Fold_1/K_36/lda_model.expElogbeta.npy
models/Fold_1/K_36/lda_model.id2word
models/Fold_1/K_36/lda_model.state
models/Fold_1/K_37/lda_model
models/Fold_1/K_37/lda_model.expElogbeta.npy
models/Fold_1/K_37/lda_model.id2word
models/Fold_1/K_37/lda_model.state
models/Fold_1/K_38/lda_model
models/Fold_1/K_38/lda_model.expElogbeta.npy
models/Fold_1/K_38/lda_model.id2word
models/Fold_1/K_38/lda_model.state
models/Fold_1/K_39/lda_model
models/Fold_1/K_39/lda_model.expElogbeta.npy
models/Fold_1/K_39/lda_model.id2word
models/Fold_1/K_39/lda_model.state
models/Fold_1/K_4/lda_model
models/Fold_1/K_4/lda_model.expElogbeta.npy
models/Fold_1/K_4/lda_model.id2word
models/Fold_1/K_4/lda_model.state
models/Fold_1/K_40/lda_model
models/Fold_1/K_40/lda_model.expElogbeta.npy
models/Fold_1/K_40/lda_model.id2word
models/Fold_1/K_40/lda_model.state
models/Fold_1/K_41/lda_model
models/Fold_1/K_41/lda_model.expElogbeta.npy
models/Fold_1/K_41/lda_model.id2word
models/Fold_1/K_41/lda_model.state
models/Fold_1/K_42/lda_model
models/Fold_1/K_42/lda_model.expElogbeta.npy
models/Fold_1/K_42/lda_model.id2word
models/Fold_1/K_42/lda_model.state
models/Fold_1/K_43/lda_model
models/Fold_1/K_43/lda_model.expElogbeta.npy
models/Fold_1/K_43/lda_model.id2word
models/Fold_1/K_43/lda_model.state
models/Fold_1/K_44/lda_model
models/Fold_1/K_44/lda_model.expElogbeta.npy
models/Fold_1/K_44/lda_model.id2word
models/Fold_1/K_44/lda_model.state
models/Fold_1/K_45/lda_model
models/Fold_1/K_45/lda_model.expElogbeta.npy
models/Fold_1/K_45/lda_model.id2word
models/Fold_1/K_45/lda_model.state
models/Fold_1/K_46/lda_model
models/Fold_1/K_46/lda_model.expElogbeta.npy
models/Fold_1/K_46/lda_model.id2word
models/Fold_1/K_46/lda_model.state
models/Fold_1/K_47/lda_model
models/Fold_1/K_47/lda_model.expElogbeta.npy
models/Fold_1/K_47/lda_model.id2word
models/Fold_1/K_47/lda_model.state
models/Fold_1/K_48/lda_model
models/Fold_1/K_48/lda_model.expElogbeta.npy
models/Fold_1/K_48/lda_model.id2word
models/Fold_1/K_48/lda_model.state
models/Fold_1/K_49/lda_model
models/Fold_1/K_49/lda_model.expElogbeta.npy
models/Fold_1/K_49/lda_model.id2word
models/Fold_1/K_49/lda_model.state
models/Fold_1/K_5/lda_model
models/Fold_1/K_5/lda_model.expElogbeta.npy
models/Fold_1/K_5/lda_model.id2word
models/Fold_1/K_5/lda_model.state
models/Fold_1/K_50/lda_model
models/Fold_1/K_50/lda_model.expElogbeta.npy
models/Fold_1/K_50/lda_model.id2word
models/Fold_1/K_50/lda_model.state
models/Fold_1/K_51/lda_model
models/Fold_1/K_51/lda_model.expElogbeta.npy
models/Fold_1/K_51/lda_model.id2word
models/Fold_1/K_51/lda_model.state
models/Fold_1/K_52/lda_model
models/Fold_1/K_52/lda_model.expElogbeta.npy
models/Fold_1/K_52/lda_model.id2word
models/Fold_1/K_52/lda_model.state
models/Fold_1/K_53/lda_model
models/Fold_1/K_53/lda_model.expElogbeta.npy
models/Fold_1/K_53/lda_model.id2word
models/Fold_1/K_53/lda_model.state
models/Fold_1/K_54/lda_model
models/Fold_1/K_54/lda_model.expElogbeta.npy
models/Fold_1/K_54/lda_model.id2word
models/Fold_1/K_54/lda_model.state
models/Fold_1/K_55/lda_model
models/Fold_1/K_55/lda_model.expElogbeta.npy
models/Fold_1/K_55/lda_model.id2word
models/Fold_1/K_55/lda_model.state
models/Fold_1/K_56/lda_model
models/Fold_1/K_56/lda_model.expElogbeta.npy
models/Fold_1/K_56/lda_model.id2word
models/Fold_1/K_56/lda_model.state
models/Fold_1/K_57/lda_model
models/Fold_1/K_57/lda_model.expElogbeta.npy
models/Fold_1/K_57/lda_model.id2word
models/Fold_1/K_57/lda_model.state
models/Fold_1/K_58/lda_model
models/Fold_1/K_58/lda_model.expElogbeta.npy
models/Fold_1/K_58/lda_model.id2word
models/Fold_1/K_58/lda_model.state
models/Fold_1/K_59/lda_model
models/Fold_1/K_59/lda_model.expElogbeta.npy
models/Fold_1/K_59/lda_model.id2word
models/Fold_1/K_59/lda_model.state
models/Fold_1/K_6/lda_model
models/Fold_1/K_6/lda_model.expElogbeta.npy
models/Fold_1/K_6/lda_model.id2word
models/Fold_1/K_6/lda_model.state
models/Fold_1/K_60/lda_model
models/Fold_1/K_60/lda_model.expElogbeta.npy
models/Fold_1/K_60/lda_model.id2word
models/Fold_1/K_60/lda_model.state
models/Fold_1/K_61/lda_model
models/Fold_1/K_61/lda_model.expElogbeta.npy
models/Fold_1/K_61/lda_model.id2word
models/Fold_1/K_61/lda_model.state
models/Fold_1/K_62/lda_model
models/Fold_1/K_62/lda_model.expElogbeta.npy
models/Fold_1/K_62/lda_model.id2word
models/Fold_1/K_62/lda_model.state
models/Fold_1/K_63/lda_model
models/Fold_1/K_63/lda_model.expElogbeta.npy
models/Fold_1/K_63/lda_model.id2word
models/Fold_1/K_63/lda_model.state
models/Fold_1/K_64/lda_model
models/Fold_1/K_64/lda_model.expElogbeta.npy
models/Fold_1/K_64/lda_model.id2word
models/Fold_1/K_64/lda_model.state
models/Fold_1/K_65/lda_model
models/Fold_1/K_65/lda_model.expElogbeta.npy
models/Fold_1/K_65/lda_model.id2word
models/Fold_1/K_65/lda_model.state
models/Fold_1/K_66/lda_model
models/Fold_1/K_66/lda_model.expElogbeta.npy
models/Fold_1/K_66/lda_model.id2word
models/Fold_1/K_66/lda_model.state
models/Fold_1/K_67/lda_model
models/Fold_1/K_67/lda_model.expElogbeta.npy
models/Fold_1/K_67/lda_model.id2word
models/Fold_1/K_67/lda_model.state
models/Fold_1/K_68/lda_model
models/Fold_1/K_68/lda_model.expElogbeta.npy
models/Fold_1/K_68/lda_model.id2word
models/Fold_1/K_68/lda_model.state
models/Fold_1/K_69/lda_model
models/Fold_1/K_69/lda_model.expElogbeta.npy
models/Fold_1/K_69/lda_model.id2word
models/Fold_1/K_69/lda_model.state
models/Fold_1/K_7/lda_model
models/Fold_1/K_7/lda_model.expElogbeta.npy
models/Fold_1/K_7/lda_model.id2word
models/Fold_1/K_7/lda_model.state
models/Fold_1/K_70/lda_model
models/Fold_1/K_70/lda_model.expElogbeta.npy
models/Fold_1/K_70/lda_model.id2word
models/Fold_1/K_70/lda_model.state
models/Fold_1/K_71/lda_model
models/Fold_1/K_71/lda_model.expElogbeta.npy
models/Fold_1/K_71/lda_model.id2word
models/Fold_1/K_71/lda_model.state
models/Fold_1/K_72/lda_model
models/Fold_1/K_72/lda_model.expElogbeta.npy
models/Fold_1/K_72/lda_model.id2word
models/Fold_1/K_72/lda_model.state
models/Fold_1/K_73/lda_model
models/Fold_1/K_73/lda_model.expElogbeta.npy
models/Fold_1/K_73/lda_model.id2word
models/Fold_1/K_73/lda_model.state
models/Fold_1/K_74/lda_model
models/Fold_1/K_74/lda_model.expElogbeta.npy
models/Fold_1/K_74/lda_model.id2word
models/Fold_1/K_74/lda_model.state
models/Fold_1/K_75/lda_model
models/Fold_1/K_75/lda_model.expElogbeta.npy
models/Fold_1/K_75/lda_model.id2word
models/Fold_1/K_75/lda_model.state
models/Fold_1/K_76/lda_model
models/Fold_1/K_76/lda_model.expElogbeta.npy
models/Fold_1/K_76/lda_model.id2word
models/Fold_1/K_76/lda_model.state
models/Fold_1/K_77/lda_model
models/Fold_1/K_77/lda_model.expElogbeta.npy
models/Fold_1/K_77/lda_model.id2word
models/Fold_1/K_77/lda_model.state
models/Fold_1/K_78/lda_model
models/Fold_1/K_78/lda_model.expElogbeta.npy
models/Fold_1/K_78/lda_model.id2word
models/Fold_1/K_78/lda_model.state
models/Fold_1/K_79/lda_model
models/Fold_1/K_79/lda_model.expElogbeta.npy
models/Fold_1/K_79/lda_model.id2word
models/Fold_1/K_79/lda_model.state
models/Fold_1/K_8/lda_model
models/Fold_1/K_8/lda_model.expElogbeta.npy
models/Fold_1/K_8/lda_model.id2word
models/Fold_1/K_8/lda_model.state
models/Fold_1/K_80/lda_model
models/Fold_1/K_80/lda_model.expElogbeta.npy
models/Fold_1/K_80/lda_model.id2word
models/Fold_1/K_80/lda_model.state
models/Fold_1/K_81/lda_model
models/Fold_1/K_81/lda_model.expElogbeta.npy
models/Fold_1/K_81/lda_model.id2word
models/Fold_1/K_81/lda_model.state
models/Fold_1/K_82/lda_model
models/Fold_1/K_82/lda_model.expElogbeta.npy
models/Fold_1/K_82/lda_model.id2word
models/Fold_1/K_82/lda_model.state
models/Fold_1/K_83/lda_model
models/Fold_1/K_83/lda_model.expElogbeta.npy
models/Fold_1/K_83/lda_model.id2word
models/Fold_1/K_83/lda_model.state
models/Fold_1/K_84/lda_model
models/Fold_1/K_84/lda_model.expElogbeta.npy
models/Fold_1/K_84/lda_model.id2word
models/Fold_1/K_84/lda_model.state
models/Fold_1/K_85/lda_model
models/Fold_1/K_85/lda_model.expElogbeta.npy
models/Fold_1/K_85/lda_model.id2word
models/Fold_1/K_85/lda_model.state
models/Fold_1/K_86/lda_model
models/Fold_1/K_86/lda_model.expElogbeta.npy
models/Fold_1/K_86/lda_model.id2word
models/Fold_1/K_86/lda_model.state
models/Fold_1/K_87/lda_model
models/Fold_1/K_87/lda_model.expElogbeta.npy
models/Fold_1/K_87/lda_model.id2word
models/Fold_1/K_87/lda_model.state
models/Fold_1/K_88/lda_model
models/Fold_1/K_88/lda_model.expElogbeta.npy
models/Fold_1/K_88/lda_model.id2word
models/Fold_1/K_88/lda_model.state
models/Fold_1/K_89/lda_model
models/Fold_1/K_89/lda_model.expElogbeta.npy
models/Fold_1/K_89/lda_model.id2word
models/Fold_1/K_89/lda_model.state
models/Fold_1/K_9/lda_model
models/Fold_1/K_9/lda_model.expElogbeta.npy
models/Fold_1/K_9/lda_model.id2word
models/Fold_1/K_9/lda_model.state
models/Fold_1/K_90/lda_model
models/Fold_1/K_90/lda_model.expElogbeta.npy
models/Fold_1/K_90/lda_model.id2word
models/Fold_1/K_90/lda_model.state
models/Fold_1/K_91/lda_model
models/Fold_1/K_91/lda_model.expElogbeta.npy
models/Fold_1/K_91/lda_model.id2word
models/Fold_1/K_91/lda_model.state
models/Fold_1/K_92/lda_model
models/Fold_1/K_92/lda_model.expElogbeta.npy
models/Fold_1/K_92/lda_model.id2word
models/Fold_1/K_92/lda_model.state
models/Fold_1/K_93/lda_model
models/Fold_1/K_93/lda_model.expElogbeta.npy
models/Fold_1/K_93/lda_model.id2word
models/Fold_1/K_93/lda_model.state
models/Fold_1/K_94/lda_model
models/Fold_1/K_94/lda_model.expElogbeta.npy
models/Fold_1/K_94/lda_model.id2word
models/Fold_1/K_94/lda_model.state
models/Fold_1/K_95/lda_model
models/Fold_1/K_95/lda_model.expElogbeta.npy
models/Fold_1/K_95/lda_model.id2word
models/Fold_1/K_95/lda_model.state
models/Fold_1/K_96/lda_model
models/Fold_1/K_96/lda_model.expElogbeta.npy
models/Fold_1/K_96/lda_model.id2word
models/Fold_1/K_96/lda_model.state
models/Fold_1/K_97/lda_model
models/Fold_1/K_97/lda_model.expElogbeta.npy
models/Fold_1/K_97/lda_model.id2word
models/Fold_1/K_97/lda_model.state
models/Fold_1/K_98/lda_model
models/Fold_1/K_98/lda_model.expElogbeta.npy
models/Fold_1/K_98/lda_model.id2word
models/Fold_1/K_98/lda_model.state
models/Fold_1/K_99/lda_model
models/Fold_1/K_99/lda_model.expElogbeta.npy
models/Fold_1/K_99/lda_model.id2word
models/Fold_1/K_99/lda_model.state
models/Fold_2/K_10/lda_model
models/Fold_2/K_10/lda_model.expElogbeta.npy
models/Fold_2/K_10/lda_model.id2word
models/Fold_2/K_10/lda_model.state
models/Fold_2/K_100/lda_model
models/Fold_2/K_100/lda_model.expElogbeta.npy
models/Fold_2/K_100/lda_model.id2word
models/Fold_2/K_100/lda_model.state
models/Fold_2/K_11/lda_model
models/Fold_2/K_11/lda_model.expElogbeta.npy
models/Fold_2/K_11/lda_model.id2word
models/Fold_2/K_11/lda_model.state
models/Fold_2/K_12/lda_model
models/Fold_2/K_12/lda_model.expElogbeta.npy
models/Fold_2/K_12/lda_model.id2word
models/Fold_2/K_12/lda_model.state
models/Fold_2/K_13/lda_model
models/Fold_2/K_13/lda_model.expElogbeta.npy
models/Fold_2/K_13/lda_model.id2word
models/Fold_2/K_13/lda_model.state
models/Fold_2/K_14/lda_model
models/Fold_2/K_14/lda_model.expElogbeta.npy
models/Fold_2/K_14/lda_model.id2word
models/Fold_2/K_14/lda_model.state
models/Fold_2/K_15/lda_model
models/Fold_2/K_15/lda_model.expElogbeta.npy
models/Fold_2/K_15/lda_model.id2word
models/Fold_2/K_15/lda_model.state
models/Fold_2/K_16/lda_model
models/Fold_2/K_16/lda_model.expElogbeta.npy
models/Fold_2/K_16/lda_model.id2word
models/Fold_2/K_16/lda_model.state
models/Fold_2/K_17/lda_model
models/Fold_2/K_17/lda_model.expElogbeta.npy
models/Fold_2/K_17/lda_model.id2word
models/Fold_2/K_17/lda_model.state
models/Fold_2/K_18/lda_model
models/Fold_2/K_18/lda_model.expElogbeta.npy
models/Fold_2/K_18/lda_model.id2word
models/Fold_2/K_18/lda_model.state
models/Fold_2/K_19/lda_model
models/Fold_2/K_19/lda_model.expElogbeta.npy
models/Fold_2/K_19/lda_model.id2word
models/Fold_2/K_19/lda_model.state
models/Fold_2/K_2/lda_model
models/Fold_2/K_2/lda_model.expElogbeta.npy
models/Fold_2/K_2/lda_model.id2word
models/Fold_2/K_2/lda_model.state
models/Fold_2/K_20/lda_model
models/Fold_2/K_20/lda_model.expElogbeta.npy
models/Fold_2/K_20/lda_model.id2word
models/Fold_2/K_20/lda_model.state
models/Fold_2/K_21/lda_model
models/Fold_2/K_21/lda_model.expElogbeta.npy
models/Fold_2/K_21/lda_model.id2word
models/Fold_2/K_21/lda_model.state
models/Fold_2/K_22/lda_model
models/Fold_2/K_22/lda_model.expElogbeta.npy
models/Fold_2/K_22/lda_model.id2word
models/Fold_2/K_22/lda_model.state
models/Fold_2/K_23/lda_model
models/Fold_2/K_23/lda_model.expElogbeta.npy
models/Fold_2/K_23/lda_model.id2word
models/Fold_2/K_23/lda_model.state
models/Fold_2/K_24/lda_model
models/Fold_2/K_24/lda_model.expElogbeta.npy
models/Fold_2/K_24/lda_model.id2word
models/Fold_2/K_24/lda_model.state
models/Fold_2/K_25/lda_model
models/Fold_2/K_25/lda_model.expElogbeta.npy
models/Fold_2/K_25/lda_model.id2word
models/Fold_2/K_25/lda_model.state
models/Fold_2/K_26/lda_model
models/Fold_2/K_26/lda_model.expElogbeta.npy
models/Fold_2/K_26/lda_model.id2word
models/Fold_2/K_26/lda_model.state
models/Fold_2/K_27/lda_model
models/Fold_2/K_27/lda_model.expElogbeta.npy
models/Fold_2/K_27/lda_model.id2word
models/Fold_2/K_27/lda_model.state
models/Fold_2/K_28/lda_model
models/Fold_2/K_28/lda_model.expElogbeta.npy
models/Fold_2/K_28/lda_model.id2word
models/Fold_2/K_28/lda_model.state
models/Fold_2/K_29/lda_model
models/Fold_2/K_29/lda_model.expElogbeta.npy
models/Fold_2/K_29/lda_model.id2word
models/Fold_2/K_29/lda_model.state
models/Fold_2/K_3/lda_model
models/Fold_2/K_3/lda_model.expElogbeta.npy
models/Fold_2/K_3/lda_model.id2word
models/Fold_2/K_3/lda_model.state
models/Fold_2/K_30/lda_model
models/Fold_2/K_30/lda_model.expElogbeta.npy
models/Fold_2/K_30/lda_model.id2word
models/Fold_2/K_30/lda_model.state
models/Fold_2/K_31/lda_model
models/Fold_2/K_31/lda_model.expElogbeta.npy
models/Fold_2/K_31/lda_model.id2word
models/Fold_2/K_31/lda_model.state
models/Fold_2/K_32/lda_model
models/Fold_2/K_32/lda_model.expElogbeta.npy
models/Fold_2/K_32/lda_model.id2word
models/Fold_2/K_32/lda_model.state
models/Fold_2/K_33/lda_model
models/Fold_2/K_33/lda_model.expElogbeta.npy
models/Fold_2/K_33/lda_model.id2word
models/Fold_2/K_33/lda_model.state
models/Fold_2/K_34/lda_model
models/Fold_2/K_34/lda_model.expElogbeta.npy
models/Fold_2/K_34/lda_model.id2word
models/Fold_2/K_34/lda_model.state
models/Fold_2/K_35/lda_model
models/Fold_2/K_35/lda_model.expElogbeta.npy
models/Fold_2/K_35/lda_model.id2word
models/Fold_2/K_35/lda_model.state
models/Fold_2/K_36/lda_model
models/Fold_2/K_36/lda_model.expElogbeta.npy
models/Fold_2/K_36/lda_model.id2word
models/Fold_2/K_36/lda_model.state
models/Fold_2/K_37/lda_model
models/Fold_2/K_37/lda_model.expElogbeta.npy
models/Fold_2/K_37/lda_model.id2word
models/Fold_2/K_37/lda_model.state
models/Fold_2/K_38/lda_model
models/Fold_2/K_38/lda_model.expElogbeta.npy
models/Fold_2/K_38/lda_model.id2word
models/Fold_2/K_38/lda_model.state
models/Fold_2/K_39/lda_model
models/Fold_2/K_39/lda_model.expElogbeta.npy
models/Fold_2/K_39/lda_model.id2word
models/Fold_2/K_39/lda_model.state
models/Fold_2/K_4/lda_model
models/Fold_2/K_4/lda_model.expElogbeta.npy
models/Fold_2/K_4/lda_model.id2word
models/Fold_2/K_4/lda_model.state
models/Fold_2/K_40/lda_model
models/Fold_2/K_40/lda_model.expElogbeta.npy
models/Fold_2/K_40/lda_model.id2word
models/Fold_2/K_40/lda_model.state
models/Fold_2/K_41/lda_model
models/Fold_2/K_41/lda_model.expElogbeta.npy
models/Fold_2/K_41/lda_model.id2word
models/Fold_2/K_41/lda_model.state
models/Fold_2/K_42/lda_model
models/Fold_2/K_42/lda_model.expElogbeta.npy
models/Fold_2/K_42/lda_model.id2word
models/Fold_2/K_42/lda_model.state

In [ ]:
# ============================================================
# NG04-4 — Validate Complete LDA Model Set
# ============================================================

from pathlib import Path
import pandas as pd
import numpy as np

EXPECTED_EXPERIMENTS = N_FOLDS * len(TOPIC_LIST)

print("=" * 70)
print("NG04 MODEL VALIDATION")
print("=" * 70)

print(f"Expected folds       : {N_FOLDS}")
print(f"Expected K values    : {len(TOPIC_LIST)}")
print(f"Expected experiments : {EXPECTED_EXPERIMENTS}")
print()

# ------------------------------------------------------------
# Find all expected model paths
# ------------------------------------------------------------

model_records = []
missing_models = []

for fold in range(1, N_FOLDS + 1):

    for k in TOPIC_LIST:

        model_path = (
            MODEL_DIR
            / f"Fold_{fold}"
            / f"K_{k}"
            / "lda_model"
        )

        exists = model_path.exists()

        model_records.append({
            "Fold": fold,
            "Topics": k,
            "ModelPath": str(model_path),
            "Exists": exists
        })

        if not exists:
            missing_models.append((fold, k))

model_validation_df = pd.DataFrame(model_records)

# ------------------------------------------------------------
# Summary
# ------------------------------------------------------------

n_found = int(model_validation_df["Exists"].sum())
n_missing = int((~model_validation_df["Exists"]).sum())

print(f"Models found         : {n_found}")
print(f"Models missing       : {n_missing}")
print()

if missing_models:
    print("MISSING MODELS:")
    for fold, k in missing_models[:20]:
        print(f"  Fold={fold}, K={k}")

    if len(missing_models) > 20:
        print(f"  ... and {len(missing_models) - 20} more")

    raise FileNotFoundError(
        f"{n_missing} expected LDA models are missing."
    )

print("✓ All expected LDA models are present.")

# ------------------------------------------------------------
# Fold-wise validation
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FOLD-WISE MODEL COUNTS")
print("=" * 70)

fold_counts = (
    model_validation_df
    .groupby("Fold")["Exists"]
    .sum()
)

for fold, count in fold_counts.items():
    print(f"Fold {fold}: {int(count)} models")

assert all(fold_counts == len(TOPIC_LIST))

# ------------------------------------------------------------
# K-wise validation
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("K RANGE VALIDATION")
print("=" * 70)

print(
    f"Minimum K found : "
    f"{model_validation_df.loc[model_validation_df['Exists'], 'Topics'].min()}"
)

print(
    f"Maximum K found : "
    f"{model_validation_df.loc[model_validation_df['Exists'], 'Topics'].max()}"
)

assert (
    model_validation_df["Topics"].min() == TOPIC_MIN
    and
    model_validation_df["Topics"].max() == TOPIC_MAX
)

print("\n" + "=" * 70)
print("VALIDATION PASSED")
print("=" * 70)

print(
    f"✓ {n_found}/{EXPECTED_EXPERIMENTS} "
    "LDA models are available."
)

In [ ]:
# ============================================================
# NG04-5 — Load NG03 Experiment Manifest
# ============================================================

MANIFEST_FILE = MODEL_DIR / "experiment_manifest_stage3.csv"

if not MANIFEST_FILE.exists():
    raise FileNotFoundError(
        f"NG03 manifest not found:\n{MANIFEST_FILE}"
    )

manifest_df = pd.read_csv(MANIFEST_FILE)

print("=" * 70)
print("NG03 EXPERIMENT MANIFEST")
print("=" * 70)

print("Shape:", manifest_df.shape)
print()

print("Columns:")
for col in manifest_df.columns:
    print("  ", col)

print("\nFirst 5 rows:")
display(manifest_df.head())

======================================================================
NG03 EXPERIMENT MANIFEST
======================================================================
Shape: (495, 10)

Columns:
   ExperimentID
   Fold
   Topics
   TrainDocuments
   TestDocuments
   DictionarySize
   ModelPath
   TrainVectorPath
   TestVectorPath
   Status

First 5 rows:

,ExperimentID,Fold,Topics,TrainDocuments,TestDocuments,DictionarySize,ModelPath,TrainVectorPath,TestVectorPath,Status
0,NG_F1_K2,1,2,14637,3660,18264,/content/drive/MyDrive/LDAChatGPT/NewsGroupsTo...,/content/drive/MyDrive/LDAChatGPT/NewsGroupsTo...,/content/drive/MyDrive/LDAChatGPT/NewsGroupsTo...,Completed
1,NG_F1_K3,1,3,14637,3660,18264,/content/drive/MyDrive/LDAChatGPT/NewsGroupsTo...,/content/drive/MyDrive/LDAChatGPT/NewsGroupsTo...,/content/drive/MyDrive/LDAChatGPT/NewsGroupsTo...,Completed
2,NG_F1_K4,1,4,14637,3660,18264,/content/drive/MyDrive/LDAChatGPT/NewsGroupsTo...,/content/drive/MyDrive/LDAChatGPT/NewsGroupsTo...,/content/drive/MyDrive/LDAChatGPT/NewsGroupsTo...,Completed
3,NG_F1_K5,1,5,14637,3660,18264,/content/drive/MyDrive/LDAChatGPT/NewsGroupsTo...,/content/drive/MyDrive/LDAChatGPT/NewsGroupsTo...,/content/drive/MyDrive/LDAChatGPT/NewsGroupsTo...,Completed
4,NG_F1_K6,1,6,14637,3660,18264,/content/drive/MyDrive/LDAChatGPT/NewsGroupsTo...,/content/drive/MyDrive/LDAChatGPT/NewsGroupsTo...,/content/drive/MyDrive/LDAChatGPT/NewsGroupsTo...,Completed

In [ ]:
# ============================================================
# NG04-5B — Validate Manifest
# ============================================================

print("=" * 70)
print("MANIFEST VALIDATION")
print("=" * 70)

print(f"Manifest rows : {len(manifest_df)}")
print(f"Expected rows : {EXPECTED_EXPERIMENTS}")

assert len(manifest_df) == EXPECTED_EXPERIMENTS, (
    f"Expected {EXPECTED_EXPERIMENTS} rows, "
    f"found {len(manifest_df)}."
)

print("✓ Manifest contains 495 experiments.")

# Check Fold/K uniqueness
possible_fold_k_columns = [
    ("Fold", "Topics"),
    ("fold", "topics"),
    ("Fold", "K"),
    ("fold", "K")
]

fold_col = None
topic_col = None

for fcol, tcol in possible_fold_k_columns:
    if fcol in manifest_df.columns and tcol in manifest_df.columns:
        fold_col = fcol
        topic_col = tcol
        break

if fold_col is None:
    raise KeyError(
        "Could not identify Fold and Topics/K columns in "
        "experiment_manifest_stage3.csv.\n"
        f"Available columns: {list(manifest_df.columns)}"
    )

print(f"Fold column   : {fold_col}")
print(f"Topic column  : {topic_col}")

duplicate_pairs = manifest_df.duplicated(
    subset=[fold_col, topic_col]
).sum()

print(f"Duplicate Fold/K pairs : {duplicate_pairs}")

assert duplicate_pairs == 0

print("✓ Fold/K combinations are unique.")

======================================================================
MANIFEST VALIDATION
======================================================================
Manifest rows : 495
Expected rows : 495
✓ Manifest contains 495 experiments.
Fold column   : Fold
Topic column  : Topics
Duplicate Fold/K pairs : 0
✓ Fold/K combinations are unique.

In [ ]:
# ============================================================
# NG04-6B — Validate Fold-Level Dictionaries
# ============================================================

DICTIONARY_DIR = BASE_DIR / "dictionary"

print("=" * 70)
print("NG03 FOLD-LEVEL DICTIONARY VALIDATION")
print("=" * 70)

print("Dictionary root:")
print(DICTIONARY_DIR)

assert DICTIONARY_DIR.exists(), \
    f"Dictionary directory not found: {DICTIONARY_DIR}"

dictionary_records = []
missing_folds = []

for fold in range(1, N_FOLDS + 1):

    fold_dir = DICTIONARY_DIR / f"Fold_{fold}"

    print(f"\n{'-' * 70}")
    print(f"FOLD {fold}")
    print(f"Directory: {fold_dir}")

    if not fold_dir.exists():
        print("✗ Fold dictionary directory does not exist.")
        missing_folds.append(fold)
        continue

    items = sorted(fold_dir.iterdir())

    if not items:
        print("✗ Directory is empty.")
        missing_folds.append(fold)
        continue

    print("Contents:")

    for item in items:
        print(" ", item.name)

        dictionary_records.append({
            "Fold": fold,
            "Path": str(item),
            "Name": item.name
        })

print("\n" + "=" * 70)
print("DICTIONARY VALIDATION SUMMARY")
print("=" * 70)

print(f"Expected folds : {N_FOLDS}")
print(f"Missing folds  : {missing_folds}")
print(f"Fold resources : {len(dictionary_records)}")

assert len(missing_folds) == 0, \
    f"Missing dictionary resources for folds: {missing_folds}"

print("\n✓ All five fold-level dictionary directories exist.")

======================================================================
NG03 FOLD-LEVEL DICTIONARY VALIDATION
======================================================================
Dictionary root:
/content/drive/MyDrive/LDAChatGPT/NewsGroupsTopicEval/dictionary

----------------------------------------------------------------------
FOLD 1
Directory: /content/drive/MyDrive/LDAChatGPT/NewsGroupsTopicEval/dictionary/Fold_1
Contents:
  dictionary.dict

----------------------------------------------------------------------
FOLD 2
Directory: /content/drive/MyDrive/LDAChatGPT/NewsGroupsTopicEval/dictionary/Fold_2
Contents:
  dictionary.dict

----------------------------------------------------------------------
FOLD 3
Directory: /content/drive/MyDrive/LDAChatGPT/NewsGroupsTopicEval/dictionary/Fold_3
Contents:
  dictionary.dict

----------------------------------------------------------------------
FOLD 4
Directory: /content/drive/MyDrive/LDAChatGPT/NewsGroupsTopicEval/dictionary/Fold_4
Contents:
  dictionary.dict

----------------------------------------------------------------------
FOLD 5
Directory: /content/drive/MyDrive/LDAChatGPT/NewsGroupsTopicEval/dictionary/Fold_5
Contents:
  dictionary.dict

======================================================================
DICTIONARY VALIDATION SUMMARY
======================================================================
Expected folds : 5
Missing folds  : []
Fold resources : 5

✓ All five fold-level dictionary directories exist.

In [ ]:
# ============================================================
# NG04-6C — Inspect Dictionary File Structure
# ============================================================

print("=" * 70)
print("DICTIONARY FILE STRUCTURE")
print("=" * 70)

for fold in range(1, N_FOLDS + 1):

    fold_dir = DICTIONARY_DIR / f"Fold_{fold}"

    print(f"\n{'-' * 70}")
    print(f"FOLD {fold}")

    for item in sorted(fold_dir.rglob("*")):

        if item.is_file():
            size_kb = item.stat().st_size / 1024

            print(
                f"  {item.relative_to(fold_dir)}"
                f"    ({size_kb:.2f} KB)"
            )

======================================================================
DICTIONARY FILE STRUCTURE
======================================================================

----------------------------------------------------------------------
FOLD 1
  dictionary.dict    (415.04 KB)

----------------------------------------------------------------------
FOLD 2
  dictionary.dict    (408.42 KB)

----------------------------------------------------------------------
FOLD 3
  dictionary.dict    (399.73 KB)

----------------------------------------------------------------------
FOLD 4
  dictionary.dict    (405.29 KB)

----------------------------------------------------------------------
FOLD 5
  dictionary.dict    (410.60 KB)

In [ ]:
# ============================================================
# NG04-7 — Validate Fold Dictionaries
# ============================================================

from gensim.corpora import Dictionary

print("=" * 70)
print("NG04 FOLD DICTIONARY VALIDATION")
print("=" * 70)

DICTIONARY_DIR = BASE_DIR / "dictionary"

dictionary_info = []

for fold in range(1, N_FOLDS + 1):

    dictionary_path = (
        DICTIONARY_DIR
        / f"Fold_{fold}"
        / "dictionary.dict"
    )

    print(f"\n{'-' * 70}")
    print(f"FOLD {fold}")
    print("Dictionary:", dictionary_path)

    assert dictionary_path.exists(), (
        f"Dictionary not found: {dictionary_path}"
    )

    dictionary = Dictionary.load(str(dictionary_path))

    vocab_size = len(dictionary)

    print("Vocabulary size:", vocab_size)

    dictionary_info.append({
        "Fold": fold,
        "DictionaryPath": str(dictionary_path),
        "DictionarySize": vocab_size
    })

dictionary_df = pd.DataFrame(dictionary_info)

print("\n" + "=" * 70)
print("DICTIONARY SUMMARY")
print("=" * 70)

display(dictionary_df)

======================================================================
NG04 FOLD DICTIONARY VALIDATION
======================================================================

----------------------------------------------------------------------
FOLD 1
Dictionary: /content/drive/MyDrive/LDAChatGPT/NewsGroupsTopicEval/dictionary/Fold_1/dictionary.dict
Vocabulary size: 18264

----------------------------------------------------------------------
FOLD 2
Dictionary: /content/drive/MyDrive/LDAChatGPT/NewsGroupsTopicEval/dictionary/Fold_2/dictionary.dict
Vocabulary size: 17976

----------------------------------------------------------------------
FOLD 3
Dictionary: /content/drive/MyDrive/LDAChatGPT/NewsGroupsTopicEval/dictionary/Fold_3/dictionary.dict
Vocabulary size: 17589

----------------------------------------------------------------------
FOLD 4
Dictionary: /content/drive/MyDrive/LDAChatGPT/NewsGroupsTopicEval/dictionary/Fold_4/dictionary.dict
Vocabulary size: 17883

----------------------------------------------------------------------
FOLD 5
Dictionary: /content/drive/MyDrive/LDAChatGPT/NewsGroupsTopicEval/dictionary/Fold_5/dictionary.dict
Vocabulary size: 18083

======================================================================
DICTIONARY SUMMARY
======================================================================

   Fold                                     DictionaryPath  DictionarySize
0     1  /content/drive/MyDrive/LDAChatGPT/NewsGroupsTo...           18264
1     2  /content/drive/MyDrive/LDAChatGPT/NewsGroupsTo...           17976
2     3  /content/drive/MyDrive/LDAChatGPT/NewsGroupsTo...           17589
3     4  /content/drive/MyDrive/LDAChatGPT/NewsGroupsTo...           17883
4     5  /content/drive/MyDrive/LDAChatGPT/NewsGroupsTo...           18083

In [ ]:
# ============================================================
# NG04-7B — Compare Manifest Dictionary Size
#              with Actual Dictionary Size
# ============================================================

print("=" * 70)
print("MANIFEST vs ACTUAL DICTIONARY SIZE")
print("=" * 70)

manifest_dictionary_sizes = (
    manifest_df
    .groupby("Fold")["DictionarySize"]
    .first()
    .reset_index()
)

manifest_dictionary_sizes = manifest_dictionary_sizes.rename(
    columns={
        "DictionarySize": "ManifestDictionarySize"
    }
)

dictionary_check = manifest_dictionary_sizes.merge(
    dictionary_df[["Fold", "DictionarySize"]],
    on="Fold",
    how="left"
)

dictionary_check["Match"] = (
    dictionary_check["ManifestDictionarySize"]
    == dictionary_check["DictionarySize"]
)

display(dictionary_check)

print("\n" + "=" * 70)
print("VALIDATION RESULT")
print("=" * 70)

for _, row in dictionary_check.iterrows():
    print(
        f"Fold {int(row['Fold'])}: "
        f"Manifest={int(row['ManifestDictionarySize'])}, "
        f"Actual={int(row['DictionarySize'])}, "
        f"Match={row['Match']}"
    )

assert dictionary_check["Match"].all(), (
    "Dictionary size mismatch detected."
)

print("\n✓ All fold dictionaries match the NG03 manifest.")

======================================================================
MANIFEST vs ACTUAL DICTIONARY SIZE
======================================================================

   Fold  ManifestDictionarySize  DictionarySize  Match
0     1                   18264           18264   True
1     2                   17976           17976   True
2     3                   17589           17589   True
3     4                   17883           17883   True
4     5                   18083           18083   True

======================================================================
VALIDATION RESULT
======================================================================
Fold 1: Manifest=18264, Actual=18264, Match=True
Fold 2: Manifest=17976, Actual=17976, Match=True
Fold 3: Manifest=17589, Actual=17589, Match=True
Fold 4: Manifest=17883, Actual=17883, Match=True
Fold 5: Manifest=18083, Actual=18083, Match=True

✓ All fold dictionaries match the NG03 manifest.

In [ ]:
# --------------------------------------------------
# 8A
# --------------------------------------------------
from pathlib import Path
import pandas as pd
import numpy as np
from gensim.models import LdaModel
from gensim.corpora import Dictionary

BASE_DIR = Path(
    "/content/drive/MyDrive/LDAChatGPT/NewsGroupsTopicEval"
)

MODEL_DIR = BASE_DIR / "models"
DICTIONARY_DIR = BASE_DIR / "dictionary"
ANALYSIS_DIR = BASE_DIR / "analysis"

ANALYSIS_DIR.mkdir(parents=True, exist_ok=True)

MANIFEST_FILE = MODEL_DIR / "experiment_manifest_stage3.csv"

manifest_df = pd.read_csv(MANIFEST_FILE)

print("Manifest rows:", len(manifest_df))
print("Expected rows:", 5 * 99)

assert len(manifest_df) == 495
assert manifest_df[["Fold", "Topics"]].drop_duplicates().shape[0] == 495

print("✓ NG03 manifest loaded and validated.")

Manifest rows: 495
Expected rows: 495
✓ NG03 manifest loaded and validated.

In [ ]:
# --------------------------------------------------
# 8B
# --------------------------------------------------
print("Manifest columns:")
print(manifest_df.columns.tolist())

print("\nFirst five rows:")
display(manifest_df.head())

Manifest columns:
['ExperimentID', 'Fold', 'Topics', 'TrainDocuments', 'TestDocuments', 'DictionarySize', 'ModelPath', 'TrainVectorPath', 'TestVectorPath', 'Status']

First five rows:

,ExperimentID,Fold,Topics,TrainDocuments,TestDocuments,DictionarySize,ModelPath,TrainVectorPath,TestVectorPath,Status
0,NG_F1_K2,1,2,14637,3660,18264,/content/drive/MyDrive/LDAChatGPT/NewsGroupsTo...,/content/drive/MyDrive/LDAChatGPT/NewsGroupsTo...,/content/drive/MyDrive/LDAChatGPT/NewsGroupsTo...,Completed
1,NG_F1_K3,1,3,14637,3660,18264,/content/drive/MyDrive/LDAChatGPT/NewsGroupsTo...,/content/drive/MyDrive/LDAChatGPT/NewsGroupsTo...,/content/drive/MyDrive/LDAChatGPT/NewsGroupsTo...,Completed
2,NG_F1_K4,1,4,14637,3660,18264,/content/drive/MyDrive/LDAChatGPT/NewsGroupsTo...,/content/drive/MyDrive/LDAChatGPT/NewsGroupsTo...,/content/drive/MyDrive/LDAChatGPT/NewsGroupsTo...,Completed
3,NG_F1_K5,1,5,14637,3660,18264,/content/drive/MyDrive/LDAChatGPT/NewsGroupsTo...,/content/drive/MyDrive/LDAChatGPT/NewsGroupsTo...,/content/drive/MyDrive/LDAChatGPT/NewsGroupsTo...,Completed
4,NG_F1_K6,1,6,14637,3660,18264,/content/drive/MyDrive/LDAChatGPT/NewsGroupsTo...,/content/drive/MyDrive/LDAChatGPT/NewsGroupsTo...,/content/drive/MyDrive/LDAChatGPT/NewsGroupsTo...,Completed

In [ ]:
# ============================================================
# NG04-8M — Reconstruct Exact NG03 Train/Test BOW Corpora
# ============================================================

import ast
import pandas as pd
from pathlib import Path
from gensim.corpora import Dictionary

print("=" * 80)
print("NG04-8M — RECONSTRUCT EXACT NG03 CORPORA")
print("=" * 80)

# ------------------------------------------------------------
# Token restoration — copied from NG03
# ------------------------------------------------------------

def restore_tokens(value):

    if isinstance(value, list):
        return value

    if pd.isna(value):
        return []

    if isinstance(value, str):

        try:
            tokens = ast.literal_eval(value)

            if isinstance(tokens, list):
                return [
                    str(token)
                    for token in tokens
                ]

        except Exception:
            pass

        return value.split()

    return []


# ------------------------------------------------------------
# Load fold exactly as NG03 did
# ------------------------------------------------------------

def load_ng03_fold(fold):

    train_file = (
        BASE_DIR
        / "folds"
        / f"Fold_{fold}"
        / "train.xlsx"
    )

    test_file = (
        BASE_DIR
        / "folds"
        / f"Fold_{fold}"
        / "test.xlsx"
    )

    train = pd.read_excel(train_file)
    test = pd.read_excel(test_file)

    assert "Tokens" in train.columns
    assert "Tokens" in test.columns

    train["Tokens"] = (
        train["Tokens"]
        .apply(restore_tokens)
    )

    test["Tokens"] = (
        test["Tokens"]
        .apply(restore_tokens)
    )

    return train, test


# ------------------------------------------------------------
# Reconstruct exact fold resources
# ------------------------------------------------------------

ng04_fold_resources = {}

validation_rows = []

for fold in range(1, 6):

    print("\n" + "=" * 70)
    print(f"Fold {fold}")
    print("=" * 70)

    train_df, test_df = load_ng03_fold(fold)

    train_tokens = train_df["Tokens"].tolist()
    test_tokens = test_df["Tokens"].tolist()

    # --------------------------------------------------------
    # Load SAME dictionary used by trained models
    # --------------------------------------------------------

    dictionary_path = (
        BASE_DIR
        / "dictionary"
        / f"Fold_{fold}"
        / "dictionary.dict"
    )

    dictionary = Dictionary.load(
        str(dictionary_path)
    )

    # --------------------------------------------------------
    # Exact BOW transformation used in NG03
    # --------------------------------------------------------

    train_corpus = [
        dictionary.doc2bow(document)
        for document in train_tokens
    ]

    test_corpus = [
        dictionary.doc2bow(document)
        for document in test_tokens
    ]

    # --------------------------------------------------------
    # Manifest reference
    # --------------------------------------------------------

    mf = (
        manifest_df[
            manifest_df["Fold"] == fold
        ]
        .iloc[0]
    )

    expected_train = int(
        mf["TrainDocuments"]
    )

    expected_test = int(
        mf["TestDocuments"]
    )

    expected_dict = int(
        mf["DictionarySize"]
    )

    print(
        "Train documents :",
        len(train_corpus),
        "| expected:",
        expected_train
    )

    print(
        "Test documents  :",
        len(test_corpus),
        "| expected:",
        expected_test
    )

    print(
        "Dictionary size :",
        len(dictionary),
        "| expected:",
        expected_dict
    )

    train_match = (
        len(train_corpus)
        == expected_train
    )

    test_match = (
        len(test_corpus)
        == expected_test
    )

    dict_match = (
        len(dictionary)
        == expected_dict
    )

    print()
    print("Train count match :", train_match)
    print("Test count match  :", test_match)
    print("Dictionary match  :", dict_match)

    assert train_match
    assert test_match
    assert dict_match

    # --------------------------------------------------------
    # Store for NG04 metrics
    # --------------------------------------------------------

    ng04_fold_resources[fold] = {

        "TrainDataFrame":
            train_df,

        "TestDataFrame":
            test_df,

        "TrainTokens":
            train_tokens,

        "TestTokens":
            test_tokens,

        "Dictionary":
            dictionary,

        "TrainCorpus":
            train_corpus,

        "TestCorpus":
            test_corpus
    }

    validation_rows.append({

        "Fold": fold,

        "TrainDocuments":
            len(train_corpus),

        "ExpectedTrain":
            expected_train,

        "TestDocuments":
            len(test_corpus),

        "ExpectedTest":
            expected_test,

        "DictionarySize":
            len(dictionary),

        "ExpectedDictionary":
            expected_dict,

        "Valid":
            (
                train_match
                and test_match
                and dict_match
            )
    })


# ------------------------------------------------------------
# Final validation
# ------------------------------------------------------------

corpus_validation_df = pd.DataFrame(
    validation_rows
)

print("\n" + "=" * 80)
print("CORPUS RECONSTRUCTION SUMMARY")
print("=" * 80)

print(
    corpus_validation_df.to_string(
        index=False
    )
)

assert corpus_validation_df["Valid"].all()

print("\n" + "=" * 80)
print("✓ EXACT NG03 CORPORA SUCCESSFULLY RECONSTRUCTED")
print("✓ READY FOR PERPLEXITY / COHERENCE COMPUTATION")
print("=" * 80)

================================================================================
NG04-8M — RECONSTRUCT EXACT NG03 CORPORA
================================================================================

======================================================================
Fold 1
======================================================================
Train documents : 14637 | expected: 14637
Test documents  : 3660 | expected: 3660
Dictionary size : 18264 | expected: 18264

Train count match : True
Test count match  : True
Dictionary match  : True

======================================================================
Fold 2
======================================================================
Train documents : 14637 | expected: 14637
Test documents  : 3660 | expected: 3660
Dictionary size : 17976 | expected: 17976

Train count match : True
Test count match  : True
Dictionary match  : True

======================================================================
Fold 3
======================================================================
Train documents : 14638 | expected: 14638
Test documents  : 3659 | expected: 3659
Dictionary size : 17589 | expected: 17589

Train count match : True
Test count match  : True
Dictionary match  : True

======================================================================
Fold 4
======================================================================
Train documents : 14638 | expected: 14638
Test documents  : 3659 | expected: 3659
Dictionary size : 17883 | expected: 17883

Train count match : True
Test count match  : True
Dictionary match  : True

======================================================================
Fold 5
======================================================================
Train documents : 14638 | expected: 14638
Test documents  : 3659 | expected: 3659
Dictionary size : 18083 | expected: 18083

Train count match : True
Test count match  : True
Dictionary match  : True

================================================================================
CORPUS RECONSTRUCTION SUMMARY
================================================================================
 Fold  TrainDocuments  ExpectedTrain  TestDocuments  ExpectedTest  DictionarySize  ExpectedDictionary  Valid
    1           14637          14637           3660          3660           18264               18264   True
    2           14637          14637           3660          3660           17976               17976   True
    3           14638          14638           3659          3659           17589               17589   True
    4           14638          14638           3659          3659           17883               17883   True
    5           14638          14638           3659          3659           18083               18083   True

================================================================================
✓ EXACT NG03 CORPORA SUCCESSFULLY RECONSTRUCTED
✓ READY FOR PERPLEXITY / COHERENCE COMPUTATION
================================================================================

In [ ]:
# ============================================================
# NG04-8N — Single-Model Perplexity Validation
# ============================================================

from gensim.models import LdaModel
import numpy as np

print("=" * 80)
print("NG04-8N — SINGLE-MODEL PERPLEXITY VALIDATION")
print("=" * 80)

VALIDATION_FOLD = 1
VALIDATION_K = 2

# ------------------------------------------------------------
# Load exact reconstructed corpora
# ------------------------------------------------------------

resources = ng04_fold_resources[VALIDATION_FOLD]

train_corpus = resources["TrainCorpus"]
test_corpus  = resources["TestCorpus"]

# ------------------------------------------------------------
# Load saved NG03 model
# ------------------------------------------------------------

model_path = (
    BASE_DIR
    / "models"
    / f"Fold_{VALIDATION_FOLD}"
    / f"K_{VALIDATION_K}"
    / "lda_model"
)

model = LdaModel.load(str(model_path))

print("\nModel:")
print(model_path)

print("\nFold:", VALIDATION_FOLD)
print("K   :", VALIDATION_K)

print(
    "Train documents:",
    len(train_corpus)
)

print(
    "Test documents :",
    len(test_corpus)
)

# ------------------------------------------------------------
# Gensim log perplexity
# ------------------------------------------------------------

train_log_perplexity = model.log_perplexity(
    train_corpus
)

test_log_perplexity = model.log_perplexity(
    test_corpus
)

# Gensim's corresponding conventional perplexity
train_perplexity = 2 ** (
    -train_log_perplexity
)

test_perplexity = 2 ** (
    -test_log_perplexity
)

# ------------------------------------------------------------
# Validate numerical output
# ------------------------------------------------------------

assert np.isfinite(train_log_perplexity)
assert np.isfinite(test_log_perplexity)

assert train_perplexity > 0
assert test_perplexity > 0

# ------------------------------------------------------------
# Display
# ------------------------------------------------------------

print("\n" + "-" * 60)

print(
    f"Train log-perplexity : "
    f"{train_log_perplexity:.8f}"
)

print(
    f"Test log-perplexity  : "
    f"{test_log_perplexity:.8f}"
)

print(
    f"Train perplexity     : "
    f"{train_perplexity:.8f}"
)

print(
    f"Test perplexity      : "
    f"{test_perplexity:.8f}"
)

print("-" * 60)

print("\n✓ Perplexity computation successful.")
print("✓ Exact NG03 BOW corpus accepted by saved LDA model.")
print("✓ Ready for the 495-model metric computation.")

================================================================================
NG04-8N — SINGLE-MODEL PERPLEXITY VALIDATION
================================================================================

Model:
/content/drive/MyDrive/LDAChatGPT/NewsGroupsTopicEval/models/Fold_1/K_2/lda_model

Fold: 1
K   : 2
Train documents: 14637
Test documents : 3660

------------------------------------------------------------
Train log-perplexity : -8.16694155
Test log-perplexity  : -8.21858425
Train perplexity     : 287.40503889
Test perplexity      : 297.87933826
------------------------------------------------------------

✓ Perplexity computation successful.
✓ Exact NG03 BOW corpus accepted by saved LDA model.
✓ Ready for the 495-model metric computation.

In [ ]:
# ============================================================
# NG04-8O — Compute Perplexity for All 495 LDA Models
# ============================================================

import gc
import time
import numpy as np
import pandas as pd

from pathlib import Path
from gensim.models import LdaModel

print("=" * 80)
print("NG04-8O — PERPLEXITY FOR ALL 495 MODELS")
print("=" * 80)

# ------------------------------------------------------------
# Output directory
# ------------------------------------------------------------

METRIC_DIR = BASE_DIR / "metrics"
METRIC_DIR.mkdir(
    parents=True,
    exist_ok=True
)

PERPLEXITY_CHECKPOINT = (
    METRIC_DIR
    / "ng04_perplexity_checkpoint.csv"
)

PERPLEXITY_FINAL = (
    METRIC_DIR
    / "ng04_perplexity_all_models.csv"
)

# ------------------------------------------------------------
# Load existing checkpoint if available
# ------------------------------------------------------------

if PERPLEXITY_CHECKPOINT.exists():

    perplexity_df = pd.read_csv(
        PERPLEXITY_CHECKPOINT
    )

    print(
        "\nExisting checkpoint found:",
        len(perplexity_df),
        "experiments"
    )

else:

    perplexity_df = pd.DataFrame(
        columns=[
            "ExperimentID",
            "Fold",
            "Topics",
            "TrainLogPerplexity",
            "TestLogPerplexity",
            "TrainPerplexity",
            "TestPerplexity"
        ]
    )

    print(
        "\nNo checkpoint found."
    )


# ------------------------------------------------------------
# Completed experiments
# ------------------------------------------------------------

if len(perplexity_df) > 0:

    completed = set(
        zip(
            perplexity_df["Fold"].astype(int),
            perplexity_df["Topics"].astype(int)
        )
    )

else:

    completed = set()


print(
    "Already completed:",
    len(completed)
)

print(
    "Remaining:",
    495 - len(completed)
)


# ------------------------------------------------------------
# Timer
# ------------------------------------------------------------

start_time = time.time()

new_count = 0


# ============================================================
# Process folds
# ============================================================

for fold in range(1, 6):

    print("\n" + "=" * 70)
    print(f"FOLD {fold}")
    print("=" * 70)

    resources = ng04_fold_resources[fold]

    train_corpus = resources[
        "TrainCorpus"
    ]

    test_corpus = resources[
        "TestCorpus"
    ]

    # --------------------------------------------------------
    # Process K = 2 ... 100
    # --------------------------------------------------------

    for topics in range(2, 101):

        if (fold, topics) in completed:

            print(
                f"Fold={fold}, K={topics}: "
                f"already completed — skipping"
            )

            continue

        experiment_id = (
            f"NG_F{fold}_K{topics}"
        )

        model_path = (
            BASE_DIR
            / "models"
            / f"Fold_{fold}"
            / f"K_{topics}"
            / "lda_model"
        )

        try:

            # ------------------------------------------------
            # Load trained NG03 model
            # ------------------------------------------------

            model = LdaModel.load(
                str(model_path)
            )

            # ------------------------------------------------
            # Log-perplexity
            # ------------------------------------------------

            train_log = float(
                model.log_perplexity(
                    train_corpus
                )
            )

            test_log = float(
                model.log_perplexity(
                    test_corpus
                )
            )

            # ------------------------------------------------
            # Conventional perplexity
            # ------------------------------------------------

            train_perp = float(
                2 ** (-train_log)
            )

            test_perp = float(
                2 ** (-test_log)
            )

            # ------------------------------------------------
            # Numerical validation
            # ------------------------------------------------

            assert np.isfinite(train_log)
            assert np.isfinite(test_log)

            assert np.isfinite(train_perp)
            assert np.isfinite(test_perp)

            assert train_perp > 0
            assert test_perp > 0

            # ------------------------------------------------
            # Result
            # ------------------------------------------------

            result_row = {
                "ExperimentID":
                    experiment_id,

                "Fold":
                    fold,

                "Topics":
                    topics,

                "TrainLogPerplexity":
                    train_log,

                "TestLogPerplexity":
                    test_log,

                "TrainPerplexity":
                    train_perp,

                "TestPerplexity":
                    test_perp
            }

            perplexity_df = pd.concat(
                [
                    perplexity_df,
                    pd.DataFrame(
                        [result_row]
                    )
                ],
                ignore_index=True
            )

            # ------------------------------------------------
            # Save immediately
            # ------------------------------------------------

            perplexity_df.to_csv(
                PERPLEXITY_CHECKPOINT,
                index=False
            )

            completed.add(
                (fold, topics)
            )

            new_count += 1

            print(
                f"✓ Fold={fold}, K={topics} | "
                f"TrainLog={train_log:.5f} | "
                f"TestLog={test_log:.5f} | "
                f"TestPerp={test_perp:.3f}"
            )

            # ------------------------------------------------
            # Memory cleanup
            # ------------------------------------------------

            del model

            gc.collect()

        except Exception as e:

            print(
                f"✗ ERROR Fold={fold}, "
                f"K={topics}: {e}"
            )

            # Preserve everything obtained so far
            perplexity_df.to_csv(
                PERPLEXITY_CHECKPOINT,
                index=False
            )

            gc.collect()


# ============================================================
# Sort results
# ============================================================

perplexity_df["Fold"] = (
    perplexity_df["Fold"]
    .astype(int)
)

perplexity_df["Topics"] = (
    perplexity_df["Topics"]
    .astype(int)
)

perplexity_df = (
    perplexity_df
    .sort_values(
        ["Fold", "Topics"]
    )
    .drop_duplicates(
        subset=[
            "Fold",
            "Topics"
        ],
        keep="last"
    )
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# Save final result
# ------------------------------------------------------------

perplexity_df.to_csv(
    PERPLEXITY_FINAL,
    index=False
)

perplexity_df.to_csv(
    PERPLEXITY_CHECKPOINT,
    index=False
)


# ============================================================
# Validation
# ============================================================

elapsed = time.time() - start_time

expected = 5 * 99

print("\n" + "=" * 80)
print("PERPLEXITY COMPUTATION SUMMARY")
print("=" * 80)

print(
    "Expected experiments :",
    expected
)

print(
    "Completed experiments:",
    len(perplexity_df)
)

print(
    "Newly computed       :",
    new_count
)

print(
    "Duplicate Fold-K     :",
    perplexity_df.duplicated(
        ["Fold", "Topics"]
    ).sum()
)

print(
    "Elapsed minutes      :",
    round(elapsed / 60, 2)
)

print(
    "\nFinal file:"
)

print(
    PERPLEXITY_FINAL
)


# ------------------------------------------------------------
# Strict final checks
# ------------------------------------------------------------

assert len(perplexity_df) == expected, (
    f"Expected {expected} results, "
    f"found {len(perplexity_df)}."
)

assert (
    perplexity_df
    .duplicated(
        ["Fold", "Topics"]
    )
    .sum()
    == 0
)

assert np.isfinite(
    perplexity_df[
        [
            "TrainLogPerplexity",
            "TestLogPerplexity",
            "TrainPerplexity",
            "TestPerplexity"
        ]
    ].to_numpy()
).all()


print("\n" + "=" * 80)

print(
    "✓ ALL 495 PERPLEXITY RESULTS COMPUTED"
)

print(
    "✓ CHECKPOINT SAVED"
)

print(
    "✓ FINAL PERPLEXITY TABLE SAVED"
)

print("=" * 80)


display(
    perplexity_df.head(10)
)

================================================================================
NG04-8O — PERPLEXITY FOR ALL 495 MODELS
================================================================================

Existing checkpoint found: 487 experiments
Already completed: 487
Remaining: 8

======================================================================
FOLD 1
======================================================================
Fold=1, K=2: already completed — skipping
Fold=1, K=3: already completed — skipping
Fold=1, K=4: already completed — skipping
Fold=1, K=5: already completed — skipping
Fold=1, K=6: already completed — skipping
Fold=1, K=7: already completed — skipping
Fold=1, K=8: already completed — skipping
Fold=1, K=9: already completed — skipping
Fold=1, K=10: already completed — skipping
Fold=1, K=11: already completed — skipping
Fold=1, K=12: already completed — skipping
Fold=1, K=13: already completed — skipping
Fold=1, K=14: already completed — skipping
Fold=1, K=15: already completed — skipping
Fold=1, K=16: already completed — skipping
Fold=1, K=17: already completed — skipping
Fold=1, K=18: already completed — skipping
Fold=1, K=19: already completed — skipping
Fold=1, K=20: already completed — skipping
Fold=1, K=21: already completed — skipping
Fold=1, K=22: already completed — skipping
Fold=1, K=23: already completed — skipping
Fold=1, K=24: already completed — skipping
Fold=1, K=25: already completed — skipping
Fold=1, K=26: already completed — skipping
Fold=1, K=27: already completed — skipping
Fold=1, K=28: already completed — skipping
Fold=1, K=29: already completed — skipping
Fold=1, K=30: already completed — skipping
Fold=1, K=31: already completed — skipping
Fold=1, K=32: already completed — skipping
Fold=1, K=33: already completed — skipping
Fold=1, K=34: already completed — skipping
Fold=1, K=35: already completed — skipping
Fold=1, K=36: already completed — skipping
Fold=1, K=37: already completed — skipping
Fold=1, K=38: already completed — skipping
Fold=1, K=39: already completed — skipping
Fold=1, K=40: already completed — skipping
Fold=1, K=41: already completed — skipping
Fold=1, K=42: already completed — skipping
Fold=1, K=43: already completed — skipping
Fold=1, K=44: already completed — skipping
Fold=1, K=45: already completed — skipping
Fold=1, K=46: already completed — skipping
Fold=1, K=47: already completed — skipping
Fold=1, K=48: already completed — skipping
Fold=1, K=49: already completed — skipping
Fold=1, K=50: already completed — skipping
Fold=1, K=51: already completed — skipping
Fold=1, K=52: already completed — skipping
Fold=1, K=53: already completed — skipping
Fold=1, K=54: already completed — skipping
Fold=1, K=55: already completed — skipping
Fold=1, K=56: already completed — skipping
Fold=1, K=57: already completed — skipping
Fold=1, K=58: already completed — skipping
Fold=1, K=59: already completed — skipping
Fold=1, K=60: already completed — skipping
Fold=1, K=61: already completed — skipping
Fold=1, K=62: already completed — skipping
Fold=1, K=63: already completed — skipping
Fold=1, K=64: already completed — skipping
Fold=1, K=65: already completed — skipping
Fold=1, K=66: already completed — skipping
Fold=1, K=67: already completed — skipping
Fold=1, K=68: already completed — skipping
Fold=1, K=69: already completed — skipping
Fold=1, K=70: already completed — skipping
Fold=1, K=71: already completed — skipping
Fold=1, K=72: already completed — skipping
Fold=1, K=73: already completed — skipping
Fold=1, K=74: already completed — skipping
Fold=1, K=75: already completed — skipping
Fold=1, K=76: already completed — skipping
Fold=1, K=77: already completed — skipping
Fold=1, K=78: already completed — skipping
Fold=1, K=79: already completed — skipping
Fold=1, K=80: already completed — skipping
Fold=1, K=81: already completed — skipping
Fold=1, K=82: already completed — skipping
Fold=1, K=83: already completed — skipping
Fold=1, K=84: already completed — skipping
Fold=1, K=85: already completed — skipping
Fold=1, K=86: already completed — skipping
Fold=1, K=87: already completed — skipping
Fold=1, K=88: already completed — skipping
Fold=1, K=89: already completed — skipping
Fold=1, K=90: already completed — skipping
Fold=1, K=91: already completed — skipping
Fold=1, K=92: already completed — skipping
Fold=1, K=93: already completed — skipping
Fold=1, K=94: already completed — skipping
Fold=1, K=95: already completed — skipping
Fold=1, K=96: already completed — skipping
Fold=1, K=97: already completed — skipping
Fold=1, K=98: already completed — skipping
Fold=1, K=99: already completed — skipping
Fold=1, K=100: already completed — skipping

======================================================================
FOLD 2
======================================================================
Fold=2, K=2: already completed — skipping
Fold=2, K=3: already completed — skipping
Fold=2, K=4: already completed — skipping
Fold=2, K=5: already completed — skipping
Fold=2, K=6: already completed — skipping
Fold=2, K=7: already completed — skipping
Fold=2, K=8: already completed — skipping
Fold=2, K=9: already completed — skipping
Fold=2, K=10: already completed — skipping
Fold=2, K=11: already completed — skipping
Fold=2, K=12: already completed — skipping
Fold=2, K=13: already completed — skipping
Fold=2, K=14: already completed — skipping
Fold=2, K=15: already completed — skipping
Fold=2, K=16: already completed — skipping
Fold=2, K=17: already completed — skipping
Fold=2, K=18: already completed — skipping
Fold=2, K=19: already completed — skipping
Fold=2, K=20: already completed — skipping
Fold=2, K=21: already completed — skipping
Fold=2, K=22: already completed — skipping
Fold=2, K=23: already completed — skipping
Fold=2, K=24: already completed — skipping
Fold=2, K=25: already completed — skipping
Fold=2, K=26: already completed — skipping
Fold=2, K=27: already completed — skipping
Fold=2, K=28: already completed — skipping
Fold=2, K=29: already completed — skipping
Fold=2, K=30: already completed — skipping
Fold=2, K=31: already completed — skipping
Fold=2, K=32: already completed — skipping
Fold=2, K=33: already completed — skipping
Fold=2, K=34: already completed — skipping
Fold=2, K=35: already completed — skipping
Fold=2, K=36: already completed — skipping
Fold=2, K=37: already completed — skipping
Fold=2, K=38: already completed — skipping
Fold=2, K=39: already completed — skipping
Fold=2, K=40: already completed — skipping
Fold=2, K=41: already completed — skipping
Fold=2, K=42: already completed — skipping
Fold=2, K=43: already completed — skipping
Fold=2, K=44: already completed — skipping
Fold=2, K=45: already completed — skipping
Fold=2, K=46: already completed — skipping
Fold=2, K=47: already completed — skipping
Fold=2, K=48: already completed — skipping
Fold=2, K=49: already completed — skipping
Fold=2, K=50: already completed — skipping
Fold=2, K=51: already completed — skipping
Fold=2, K=52: already completed — skipping
Fold=2, K=53: already completed — skipping
Fold=2, K=54: already completed — skipping
Fold=2, K=55: already completed — skipping
Fold=2, K=56: already completed — skipping
Fold=2, K=57: already completed — skipping
Fold=2, K=58: already completed — skipping
Fold=2, K=59: already completed — skipping
Fold=2, K=60: already completed — skipping
Fold=2, K=61: already completed — skipping
Fold=2, K=62: already completed — skipping
Fold=2, K=63: already completed — skipping
Fold=2, K=64: already completed — skipping
Fold=2, K=65: already completed — skipping
Fold=2, K=66: already completed — skipping
Fold=2, K=67: already completed — skipping
Fold=2, K=68: already completed — skipping
Fold=2, K=69: already completed — skipping
Fold=2, K=70: already completed — skipping
Fold=2, K=71: already completed — skipping
Fold=2, K=72: already completed — skipping
Fold=2, K=73: already completed — skipping
Fold=2, K=74: already completed — skipping
Fold=2, K=75: already completed — skipping
Fold=2, K=76: already completed — skipping
Fold=2, K=77: already completed — skipping
Fold=2, K=78: already completed — skipping
Fold=2, K=79: already completed — skipping
Fold=2, K=80: already completed — skipping
Fold=2, K=81: already completed — skipping
Fold=2, K=82: already completed — skipping
Fold=2, K=83: already completed — skipping
Fold=2, K=84: already completed — skipping
Fold=2, K=85: already completed — skipping
Fold=2, K=86: already completed — skipping
Fold=2, K=87: already completed — skipping
Fold=2, K=88: already completed — skipping
Fold=2, K=89: already completed — skipping
Fold=2, K=90: already completed — skipping
Fold=2, K=91: already completed — skipping
Fold=2, K=92: already completed — skipping
Fold=2, K=93: already completed — skipping
Fold=2, K=94: already completed — skipping
Fold=2, K=95: already completed — skipping
Fold=2, K=96: already completed — skipping
Fold=2, K=97: already completed — skipping
Fold=2, K=98: already completed — skipping
Fold=2, K=99: already completed — skipping
Fold=2, K=100: already completed — skipping

======================================================================
FOLD 3
======================================================================
Fold=3, K=2: already completed — skipping
Fold=3, K=3: already completed — skipping
Fold=3, K=4: already completed — skipping
Fold=3, K=5: already completed — skipping
Fold=3, K=6: already completed — skipping
Fold=3, K=7: already completed — skipping
Fold=3, K=8: already completed — skipping
Fold=3, K=9: already completed — skipping
Fold=3, K=10: already completed — skipping
Fold=3, K=11: already completed — skipping
Fold=3, K=12: already completed — skipping
Fold=3, K=13: already completed — skipping
Fold=3, K=14: already completed — skipping
Fold=3, K=15: already completed — skipping
Fold=3, K=16: already completed — skipping
Fold=3, K=17: already completed — skipping
Fold=3, K=18: already completed — skipping
Fold=3, K=19: already completed — skipping
Fold=3, K=20: already completed — skipping
Fold=3, K=21: already completed — skipping
Fold=3, K=22: already completed — skipping
Fold=3, K=23: already completed — skipping
Fold=3, K=24: already completed — skipping
Fold=3, K=25: already completed — skipping
Fold=3, K=26: already completed — skipping
Fold=3, K=27: already completed — skipping
Fold=3, K=28: already completed — skipping
Fold=3, K=29: already completed — skipping
Fold=3, K=30: already completed — skipping
Fold=3, K=31: already completed — skipping
Fold=3, K=32: already completed — skipping
Fold=3, K=33: already completed — skipping
Fold=3, K=34: already completed — skipping
Fold=3, K=35: already completed — skipping
Fold=3, K=36: already completed — skipping
Fold=3, K=37: already completed — skipping
Fold=3, K=38: already completed — skipping
Fold=3, K=39: already completed — skipping
Fold=3, K=40: already completed — skipping
Fold=3, K=41: already completed — skipping
Fold=3, K=42: already completed — skipping
Fold=3, K=43: already completed — skipping
Fold=3, K=44: already completed — skipping
Fold=3, K=45: already completed — skipping
Fold=3, K=46: already completed — skipping
Fold=3, K=47: already completed — skipping
Fold=3, K=48: already completed — skipping
Fold=3, K=49: already completed — skipping
Fold=3, K=50: already completed — skipping
Fold=3, K=51: already completed — skipping
Fold=3, K=52: already completed — skipping
Fold=3, K=53: already completed — skipping
Fold=3, K=54: already completed — skipping
Fold=3, K=55: already completed — skipping
Fold=3, K=56: already completed — skipping
Fold=3, K=57: already completed — skipping
Fold=3, K=58: already completed — skipping
Fold=3, K=59: already completed — skipping
Fold=3, K=60: already completed — skipping
Fold=3, K=61: already completed — skipping
Fold=3, K=62: already completed — skipping
Fold=3, K=63: already completed — skipping
Fold=3, K=64: already completed — skipping
Fold=3, K=65: already completed — skipping
Fold=3, K=66: already completed — skipping
Fold=3, K=67: already completed — skipping
Fold=3, K=68: already completed — skipping
Fold=3, K=69: already completed — skipping
Fold=3, K=70: already completed — skipping
Fold=3, K=71: already completed — skipping
Fold=3, K=72: already completed — skipping
Fold=3, K=73: already completed — skipping
Fold=3, K=74: already completed — skipping
Fold=3, K=75: already completed — skipping
Fold=3, K=76: already completed — skipping
Fold=3, K=77: already completed — skipping
Fold=3, K=78: already completed — skipping
Fold=3, K=79: already completed — skipping
Fold=3, K=80: already completed — skipping
Fold=3, K=81: already completed — skipping
Fold=3, K=82: already completed — skipping
Fold=3, K=83: already completed — skipping
Fold=3, K=84: already completed — skipping
Fold=3, K=85: already completed — skipping
Fold=3, K=86: already completed — skipping
Fold=3, K=87: already completed — skipping
Fold=3, K=88: already completed — skipping
Fold=3, K=89: already completed — skipping
Fold=3, K=90: already completed — skipping
Fold=3, K=91: already completed — skipping
Fold=3, K=92: already completed — skipping
Fold=3, K=93: already completed — skipping
Fold=3, K=94: already completed — skipping
Fold=3, K=95: already completed — skipping
Fold=3, K=96: already completed — skipping
Fold=3, K=97: already completed — skipping
Fold=3, K=98: already completed — skipping
Fold=3, K=99: already completed — skipping
Fold=3, K=100: already completed — skipping

======================================================================
FOLD 4
======================================================================
Fold=4, K=2: already completed — skipping
Fold=4, K=3: already completed — skipping
Fold=4, K=4: already completed — skipping
Fold=4, K=5: already completed — skipping
Fold=4, K=6: already completed — skipping
Fold=4, K=7: already completed — skipping
Fold=4, K=8: already completed — skipping
Fold=4, K=9: already completed — skipping
Fold=4, K=10: already completed — skipping
Fold=4, K=11: already completed — skipping
Fold=4, K=12: already completed — skipping
Fold=4, K=13: already completed — skipping
Fold=4, K=14: already completed — skipping
Fold=4, K=15: already completed — skipping
Fold=4, K=16: already completed — skipping
Fold=4, K=17: already completed — skipping
Fold=4, K=18: already completed — skipping
Fold=4, K=19: already completed — skipping
Fold=4, K=20: already completed — skipping
Fold=4, K=21: already completed — skipping
Fold=4, K=22: already completed — skipping
Fold=4, K=23: already completed — skipping
Fold=4, K=24: already completed — skipping
Fold=4, K=25: already completed — skipping
Fold=4, K=26: already completed — skipping
Fold=4, K=27: already completed — skipping
Fold=4, K=28: already completed — skipping
Fold=4, K=29: already completed — skipping
Fold=4, K=30: already completed — skipping
Fold=4, K=31: already completed — skipping
Fold=4, K=32: already completed — skipping
Fold=4, K=33: already completed — skipping
Fold=4, K=34: already completed — skipping
Fold=4, K=35: already completed — skipping
Fold=4, K=36: already completed — skipping
Fold=4, K=37: already completed — skipping
Fold=4, K=38: already completed — skipping
Fold=4, K=39: already completed — skipping
Fold=4, K=40: already completed — skipping
Fold=4, K=41: already completed — skipping
Fold=4, K=42: already completed — skipping
Fold=4, K=43: already completed — skipping
Fold=4, K=44: already completed — skipping
Fold=4, K=45: already completed — skipping
Fold=4, K=46: already completed — skipping
Fold=4, K=47: already completed — skipping
Fold=4, K=48: already completed — skipping
Fold=4, K=49: already completed — skipping
Fold=4, K=50: already completed — skipping
Fold=4, K=51: already completed — skipping
Fold=4, K=52: already completed — skipping
Fold=4, K=53: already completed — skipping
Fold=4, K=54: already completed — skipping
Fold=4, K=55: already completed — skipping
Fold=4, K=56: already completed — skipping
Fold=4, K=57: already completed — skipping
Fold=4, K=58: already completed — skipping
Fold=4, K=59: already completed — skipping
Fold=4, K=60: already completed — skipping
Fold=4, K=61: already completed — skipping
Fold=4, K=62: already completed — skipping
Fold=4, K=63: already completed — skipping
Fold=4, K=64: already completed — skipping
Fold=4, K=65: already completed — skipping
Fold=4, K=66: already completed — skipping
Fold=4, K=67: already completed — skipping
Fold=4, K=68: already completed — skipping
Fold=4, K=69: already completed — skipping
Fold=4, K=70: already completed — skipping
Fold=4, K=71: already completed — skipping
Fold=4, K=72: already completed — skipping
Fold=4, K=73: already completed — skipping
Fold=4, K=74: already completed — skipping
Fold=4, K=75: already completed — skipping
Fold=4, K=76: already completed — skipping
Fold=4, K=77: already completed — skipping
Fold=4, K=78: already completed — skipping
Fold=4, K=79: already completed — skipping
Fold=4, K=80: already completed — skipping
Fold=4, K=81: already completed — skipping
Fold=4, K=82: already completed — skipping
Fold=4, K=83: already completed — skipping
Fold=4, K=84: already completed — skipping
Fold=4, K=85: already completed — skipping
Fold=4, K=86: already completed — skipping
Fold=4, K=87: already completed — skipping
Fold=4, K=88: already completed — skipping
Fold=4, K=89: already completed — skipping
Fold=4, K=90: already completed — skipping
Fold=4, K=91: already completed — skipping
Fold=4, K=92: already completed — skipping
Fold=4, K=93: already completed — skipping
Fold=4, K=94: already completed — skipping
Fold=4, K=95: already completed — skipping
Fold=4, K=96: already completed — skipping
Fold=4, K=97: already completed — skipping
Fold=4, K=98: already completed — skipping
Fold=4, K=99: already completed — skipping
Fold=4, K=100: already completed — skipping

======================================================================
FOLD 5
======================================================================
Fold=5, K=2: already completed — skipping
Fold=5, K=3: already completed — skipping
Fold=5, K=4: already completed — skipping
Fold=5, K=5: already completed — skipping
Fold=5, K=6: already completed — skipping
Fold=5, K=7: already completed — skipping
Fold=5, K=8: already completed — skipping
Fold=5, K=9: already completed — skipping
Fold=5, K=10: already completed — skipping
Fold=5, K=11: already completed — skipping
Fold=5, K=12: already completed — skipping
Fold=5, K=13: already completed — skipping
Fold=5, K=14: already completed — skipping
Fold=5, K=15: already completed — skipping
Fold=5, K=16: already completed — skipping
Fold=5, K=17: already completed — skipping
Fold=5, K=18: already completed — skipping
Fold=5, K=19: already completed — skipping
Fold=5, K=20: already completed — skipping
Fold=5, K=21: already completed — skipping
Fold=5, K=22: already completed — skipping
Fold=5, K=23: already completed — skipping
Fold=5, K=24: already completed — skipping
Fold=5, K=25: already completed — skipping
Fold=5, K=26: already completed — skipping
Fold=5, K=27: already completed — skipping
Fold=5, K=28: already completed — skipping
Fold=5, K=29: already completed — skipping
Fold=5, K=30: already completed — skipping
Fold=5, K=31: already completed — skipping
Fold=5, K=32: already completed — skipping
Fold=5, K=33: already completed — skipping
Fold=5, K=34: already completed — skipping
Fold=5, K=35: already completed — skipping
Fold=5, K=36: already completed — skipping
Fold=5, K=37: already completed — skipping
Fold=5, K=38: already completed — skipping
Fold=5, K=39: already completed — skipping
Fold=5, K=40: already completed — skipping
Fold=5, K=41: already completed — skipping
Fold=5, K=42: already completed — skipping
Fold=5, K=43: already completed — skipping
Fold=5, K=44: already completed — skipping
Fold=5, K=45: already completed — skipping
Fold=5, K=46: already completed — skipping

,ExperimentID,Fold,Topics,TrainLogPerplexity,TestLogPerplexity,TrainPerplexity,TestPerplexity
0,NG_F1_K2,1,2,-8.166942,-8.218584,287.405039,297.879338
1,NG_F1_K3,1,3,-8.017795,-8.114469,259.177277,277.139657
2,NG_F1_K4,1,4,-7.962156,-8.111846,249.372131,276.636202
3,NG_F1_K5,1,5,-7.929313,-8.109783,243.759208,276.240885
4,NG_F1_K6,1,6,-7.908885,-8.111695,240.331941,276.607296
5,NG_F1_K7,1,7,-7.927259,-8.142549,243.412343,282.586535
6,NG_F1_K8,1,8,-7.950640,-8.171427,247.389346,288.299923
7,NG_F1_K9,1,9,-7.949942,-8.178067,247.269690,289.630044
8,NG_F1_K10,1,10,-7.989076,-8.215569,254.068875,297.257459
9,NG_F1_K11,1,11,-8.092732,-8.323661,272.995229,320.384566

In [ ]:
# ============================================================
# NG04-8P — Final Perplexity Result Summary
# ============================================================

METRIC_DIR = BASE_DIR / "metrics"
METRIC_DIR.mkdir(
    parents=True,
    exist_ok=True
)

PERPLEXITY_CHECKPOINT = (
    METRIC_DIR
    / "ng04_perplexity_checkpoint.csv"
)

PERPLEXITY_FINAL = (
    METRIC_DIR
    / "ng04_perplexity_all_models.csv"
)


print("=" * 80)
print("NG04-8P — FINAL PERPLEXITY RESULT SUMMARY")
print("=" * 80)

perplexity_df = pd.read_csv(
    PERPLEXITY_FINAL
)

print("Shape              :", perplexity_df.shape)

print(
    "Unique Fold-K pairs:",
    perplexity_df[
        ["Fold", "Topics"]
    ].drop_duplicates().shape[0]
)

print(
    "Missing values     :",
    perplexity_df.isna().sum().sum()
)

print()

summary = (
    perplexity_df
    .groupby("Fold")
    .agg(
        Models=("Topics", "count"),
        MinK=("Topics", "min"),
        MaxK=("Topics", "max"),
        MinTestLogPerplexity=(
            "TestLogPerplexity",
            "min"
        ),
        MaxTestLogPerplexity=(
            "TestLogPerplexity",
            "max"
        ),
        MinTestPerplexity=(
            "TestPerplexity",
            "min"
        ),
        MaxTestPerplexity=(
            "TestPerplexity",
            "max"
        )
    )
)

display(summary)

# ------------------------------------------------------------
# Strict validation
# ------------------------------------------------------------

assert len(perplexity_df) == 495

assert (
    perplexity_df[
        ["Fold", "Topics"]
    ]
    .drop_duplicates()
    .shape[0]
    == 495
)

assert perplexity_df.isna().sum().sum() == 0

assert set(
    perplexity_df["Fold"].unique()
) == {1, 2, 3, 4, 5}

for fold in range(1, 6):

    ks = set(
        perplexity_df.loc[
            perplexity_df["Fold"] == fold,
            "Topics"
        ]
    )

    assert ks == set(
        range(2, 101)
    )

print()
print("=" * 80)
print("✓ 495 UNIQUE PERPLEXITY RESULTS VERIFIED")
print("✓ ALL FOLDS CONTAIN K = 2 ... 100")
print("✓ NO MISSING VALUES")
print("=" * 80)

================================================================================
NG04-8P — FINAL PERPLEXITY RESULT SUMMARY
================================================================================
Shape              : (495, 7)
Unique Fold-K pairs: 495
Missing values     : 0

,Models,MinK,MaxK,MinTestLogPerplexity,MaxTestLogPerplexity,MinTestPerplexity,MaxTestPerplexity
Fold,,,,,,,
1,99,2,100,-15.484621,-8.109783,276.240885,45849.595997
2,99,2,100,-11.452576,-8.248373,304.093850,2802.649939
3,99,2,100,-12.210208,-7.896106,238.212537,4738.479128
4,99,2,100,-11.562086,-8.268954,308.463046,3023.671645
5,99,2,100,-11.861954,-8.315509,318.579367,3722.237205

================================================================================
✓ 495 UNIQUE PERPLEXITY RESULTS VERIFIED
✓ ALL FOLDS CONTAIN K = 2 ... 100
✓ NO MISSING VALUES
================================================================================

In [ ]:
# ============================================================
# NG04-8Q — Compute Four Coherence Metrics for All 495 Models
# ============================================================

import gc
import time
import numpy as np
import pandas as pd

from pathlib import Path
from gensim.models import LdaModel, CoherenceModel

print("=" * 80)
print("NG04-8Q — COHERENCE METRICS FOR ALL 495 MODELS")
print("=" * 80)

# ------------------------------------------------------------
# Output files
# ------------------------------------------------------------

METRIC_DIR = BASE_DIR / "metrics"

METRIC_DIR.mkdir(
    parents=True,
    exist_ok=True
)

COHERENCE_CHECKPOINT = (
    METRIC_DIR
    / "ng04_coherence_checkpoint.csv"
)

COHERENCE_FINAL = (
    METRIC_DIR
    / "ng04_coherence_all_models.csv"
)

# ------------------------------------------------------------
# Load checkpoint
# ------------------------------------------------------------

if COHERENCE_CHECKPOINT.exists():

    coherence_df = pd.read_csv(
        COHERENCE_CHECKPOINT
    )

    print(
        "\nExisting checkpoint found:",
        len(coherence_df),
        "experiments"
    )

else:

    coherence_df = pd.DataFrame(
        columns=[
            "ExperimentID",
            "Fold",
            "Topics",
            "Coherence_UMass",
            "Coherence_CV",
            "Coherence_UCI",
            "Coherence_NPMI"
        ]
    )

    print("\nNo checkpoint found.")


# ------------------------------------------------------------
# Completed Fold-K pairs
# ------------------------------------------------------------

if len(coherence_df) > 0:

    completed = set(
        zip(
            coherence_df["Fold"].astype(int),
            coherence_df["Topics"].astype(int)
        )
    )

else:

    completed = set()


print(
    "Already completed:",
    len(completed)
)

print(
    "Remaining:",
    495 - len(completed)
)


# ------------------------------------------------------------
# Timer
# ------------------------------------------------------------

start_time = time.time()

new_count = 0


# ============================================================
# Fold loop
# ============================================================

for fold in range(1, 6):

    print("\n" + "=" * 70)
    print(f"FOLD {fold}")
    print("=" * 70)

    resources = ng04_fold_resources[fold]

    train_tokens = resources[
        "TrainTokens"
    ]

    train_corpus = resources[
        "TrainCorpus"
    ]

    dictionary = resources[
        "Dictionary"
    ]

    print(
        "Training documents:",
        len(train_tokens)
    )

    print(
        "Dictionary size   :",
        len(dictionary)
    )

    # ========================================================
    # K loop
    # ========================================================

    for topics in range(2, 101):

        if (fold, topics) in completed:

            print(
                f"Fold={fold}, K={topics}: "
                "already completed — skipping"
            )

            continue

        experiment_id = (
            f"NG_F{fold}_K{topics}"
        )

        model_path = (
            BASE_DIR
            / "models"
            / f"Fold_{fold}"
            / f"K_{topics}"
            / "lda_model"
        )

        try:

            # ------------------------------------------------
            # Load existing NG03 model
            # ------------------------------------------------

            model = LdaModel.load(
                str(model_path)
            )

            # =================================================
            # 1. UMass
            # =================================================

            cm_umass = CoherenceModel(
                model=model,
                corpus=train_corpus,
                dictionary=dictionary,
                coherence="u_mass"
            )

            coherence_umass = float(
                cm_umass.get_coherence()
            )

            del cm_umass

            # =================================================
            # 2. C_V
            # =================================================

            cm_cv = CoherenceModel(
                model=model,
                texts=train_tokens,
                dictionary=dictionary,
                coherence="c_v",
                processes=1
            )

            coherence_cv = float(
                cm_cv.get_coherence()
            )

            del cm_cv

            # =================================================
            # 3. C_UCI
            # =================================================

            cm_uci = CoherenceModel(
                model=model,
                texts=train_tokens,
                dictionary=dictionary,
                coherence="c_uci",
                processes=1
            )

            coherence_uci = float(
                cm_uci.get_coherence()
            )

            del cm_uci

            # =================================================
            # 4. C_NPMI
            # =================================================

            cm_npmi = CoherenceModel(
                model=model,
                texts=train_tokens,
                dictionary=dictionary,
                coherence="c_npmi",
                processes=1
            )

            coherence_npmi = float(
                cm_npmi.get_coherence()
            )

            del cm_npmi

            # ------------------------------------------------
            # Numerical validation
            # ------------------------------------------------

            values = np.array(
                [
                    coherence_umass,
                    coherence_cv,
                    coherence_uci,
                    coherence_npmi
                ],
                dtype=float
            )

            assert np.isfinite(
                values
            ).all()

            # ------------------------------------------------
            # Save result
            # ------------------------------------------------

            result_row = {

                "ExperimentID":
                    experiment_id,

                "Fold":
                    fold,

                "Topics":
                    topics,

                "Coherence_UMass":
                    coherence_umass,

                "Coherence_CV":
                    coherence_cv,

                "Coherence_UCI":
                    coherence_uci,

                "Coherence_NPMI":
                    coherence_npmi
            }

            coherence_df = pd.concat(
                [
                    coherence_df,
                    pd.DataFrame(
                        [result_row]
                    )
                ],
                ignore_index=True
            )

            # ------------------------------------------------
            # Checkpoint immediately
            # ------------------------------------------------

            coherence_df.to_csv(
                COHERENCE_CHECKPOINT,
                index=False
            )

            completed.add(
                (fold, topics)
            )

            new_count += 1

            print(
                f"✓ Fold={fold}, K={topics} | "
                f"UMass={coherence_umass:.5f} | "
                f"CV={coherence_cv:.5f} | "
                f"UCI={coherence_uci:.5f} | "
                f"NPMI={coherence_npmi:.5f}"
            )

            # ------------------------------------------------
            # Cleanup
            # ------------------------------------------------

            del model

            gc.collect()

        except Exception as e:

            print(
                f"✗ ERROR Fold={fold}, "
                f"K={topics}: {e}"
            )

            coherence_df.to_csv(
                COHERENCE_CHECKPOINT,
                index=False
            )

            gc.collect()


# ============================================================
# Final cleanup / sorting
# ============================================================

coherence_df["Fold"] = (
    coherence_df["Fold"]
    .astype(int)
)

coherence_df["Topics"] = (
    coherence_df["Topics"]
    .astype(int)
)

coherence_df = (
    coherence_df
    .sort_values(
        ["Fold", "Topics"]
    )
    .drop_duplicates(
        subset=[
            "Fold",
            "Topics"
        ],
        keep="last"
    )
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# Save final table
# ------------------------------------------------------------

coherence_df.to_csv(
    COHERENCE_FINAL,
    index=False
)

coherence_df.to_csv(
    COHERENCE_CHECKPOINT,
    index=False
)


# ============================================================
# Final validation
# ============================================================

expected = 5 * 99

elapsed = (
    time.time()
    - start_time
)

print("\n" + "=" * 80)
print("COHERENCE COMPUTATION SUMMARY")
print("=" * 80)

print(
    "Expected experiments :",
    expected
)

print(
    "Completed experiments:",
    len(coherence_df)
)

print(
    "Newly computed       :",
    new_count
)

print(
    "Duplicate Fold-K     :",
    coherence_df.duplicated(
        ["Fold", "Topics"]
    ).sum()
)

print(
    "Elapsed minutes      :",
    round(
        elapsed / 60,
        2
    )
)

print(
    "\nFinal file:"
)

print(
    COHERENCE_FINAL
)


# ------------------------------------------------------------
# Strict checks
# ------------------------------------------------------------

assert len(coherence_df) == 495

assert (
    coherence_df
    .duplicated(
        ["Fold", "Topics"]
    )
    .sum()
    == 0
)

metric_columns = [
    "Coherence_UMass",
    "Coherence_CV",
    "Coherence_UCI",
    "Coherence_NPMI"
]

assert np.isfinite(
    coherence_df[
        metric_columns
    ].to_numpy()
).all()


print("\n" + "=" * 80)

print(
    "✓ ALL 495 COHERENCE RESULTS COMPUTED"
)

print(
    "✓ FOUR COHERENCE METRICS COMPLETE"
)

print(
    "✓ CHECKPOINT AND FINAL TABLE SAVED"
)

print("=" * 80)

display(
    coherence_df.head(10)
)

================================================================================
NG04-8Q — COHERENCE METRICS FOR ALL 495 MODELS
================================================================================

Existing checkpoint found: 188 experiments
Already completed: 188
Remaining: 307

======================================================================
FOLD 1
======================================================================
Training documents: 14637
Dictionary size   : 18264
Fold=1, K=2: already completed — skipping
Fold=1, K=3: already completed — skipping
Fold=1, K=4: already completed — skipping
Fold=1, K=5: already completed — skipping
Fold=1, K=6: already completed — skipping
Fold=1, K=7: already completed — skipping
Fold=1, K=8: already completed — skipping
Fold=1, K=9: already completed — skipping
Fold=1, K=10: already completed — skipping
Fold=1, K=11: already completed — skipping
Fold=1, K=12: already completed — skipping
Fold=1, K=13: already completed — skipping
Fold=1, K=14: already completed — skipping
Fold=1, K=15: already completed — skipping
Fold=1, K=16: already completed — skipping
Fold=1, K=17: already completed — skipping
Fold=1, K=18: already completed — skipping
Fold=1, K=19: already completed — skipping
Fold=1, K=20: already completed — skipping
Fold=1, K=21: already completed — skipping
Fold=1, K=22: already completed — skipping
Fold=1, K=23: already completed — skipping
Fold=1, K=24: already completed — skipping
Fold=1, K=25: already completed — skipping
Fold=1, K=26: already completed — skipping
Fold=1, K=27: already completed — skipping
Fold=1, K=28: already completed — skipping
Fold=1, K=29: already completed — skipping
Fold=1, K=30: already completed — skipping
Fold=1, K=31: already completed — skipping
Fold=1, K=32: already completed — skipping
Fold=1, K=33: already completed — skipping
Fold=1, K=34: already completed — skipping
Fold=1, K=35: already completed — skipping
Fold=1, K=36: already completed — skipping
Fold=1, K=37: already completed — skipping
Fold=1, K=38: already completed — skipping
Fold=1, K=39: already completed — skipping
Fold=1, K=40: already completed — skipping
Fold=1, K=41: already completed — skipping
Fold=1, K=42: already completed — skipping
Fold=1, K=43: already completed — skipping
Fold=1, K=44: already completed — skipping
Fold=1, K=45: already completed — skipping
Fold=1, K=46: already completed — skipping
Fold=1, K=47: already completed — skipping
Fold=1, K=48: already completed — skipping
Fold=1, K=49: already completed — skipping
Fold=1, K=50: already completed — skipping
Fold=1, K=51: already completed — skipping
Fold=1, K=52: already completed — skipping
Fold=1, K=53: already completed — skipping
Fold=1, K=54: already completed — skipping
Fold=1, K=55: already completed — skipping
Fold=1, K=56: already completed — skipping
Fold=1, K=57: already completed — skipping
Fold=1, K=58: already completed — skipping
Fold=1, K=59: already completed — skipping
Fold=1, K=60: already completed — skipping
Fold=1, K=61: already completed — skipping
Fold=1, K=62: already completed — skipping
Fold=1, K=63: already completed — skipping
Fold=1, K=64: already completed — skipping
Fold=1, K=65: already completed — skipping
Fold=1, K=66: already completed — skipping
Fold=1, K=67: already completed — skipping
Fold=1, K=68: already completed — skipping
Fold=1, K=69: already completed — skipping
Fold=1, K=70: already completed — skipping
Fold=1, K=71: already completed — skipping
Fold=1, K=72: already completed — skipping
Fold=1, K=73: already completed — skipping
Fold=1, K=74: already completed — skipping
Fold=1, K=75: already completed — skipping
Fold=1, K=76: already completed — skipping
Fold=1, K=77: already completed — skipping
Fold=1, K=78: already completed — skipping
Fold=1, K=79: already completed — skipping
Fold=1, K=80: already completed — skipping
Fold=1, K=81: already completed — skipping
Fold=1, K=82: already completed — skipping
Fold=1, K=83: already completed — skipping
Fold=1, K=84: already completed — skipping
Fold=1, K=85: already completed — skipping
Fold=1, K=86: already completed — skipping
Fold=1, K=87: already completed — skipping
Fold=1, K=88: already completed — skipping
Fold=1, K=89: already completed — skipping
Fold=1, K=90: already completed — skipping
Fold=1, K=91: already completed — skipping
Fold=1, K=92: already completed — skipping
Fold=1, K=93: already completed — skipping
Fold=1, K=94: already completed — skipping
Fold=1, K=95: already completed — skipping
Fold=1, K=96: already completed — skipping
Fold=1, K=97: already completed — skipping
Fold=1, K=98: already completed — skipping
Fold=1, K=99: already completed — skipping
Fold=1, K=100: already completed — skipping

======================================================================
FOLD 2
======================================================================
Training documents: 14637
Dictionary size   : 17976
Fold=2, K=2: already completed — skipping
Fold=2, K=3: already completed — skipping
Fold=2, K=4: already completed — skipping
Fold=2, K=5: already completed — skipping
Fold=2, K=6: already completed — skipping
Fold=2, K=7: already completed — skipping
Fold=2, K=8: already completed — skipping
Fold=2, K=9: already completed — skipping
Fold=2, K=10: already completed — skipping
Fold=2, K=11: already completed — skipping
Fold=2, K=12: already completed — skipping
Fold=2, K=13: already completed — skipping
Fold=2, K=14: already completed — skipping
Fold=2, K=15: already completed — skipping
Fold=2, K=16: already completed — skipping
Fold=2, K=17: already completed — skipping
Fold=2, K=18: already completed — skipping
Fold=2, K=19: already completed — skipping
Fold=2, K=20: already completed — skipping
Fold=2, K=21: already completed — skipping
Fold=2, K=22: already completed — skipping
Fold=2, K=23: already completed — skipping
Fold=2, K=24: already completed — skipping
Fold=2, K=25: already completed — skipping
Fold=2, K=26: already completed — skipping
Fold=2, K=27: already completed — skipping
Fold=2, K=28: already completed — skipping
Fold=2, K=29: already completed — skipping
Fold=2, K=30: already completed — skipping
Fold=2, K=31: already completed — skipping
Fold=2, K=32: already completed — skipping
Fold=2, K=33: already completed — skipping
Fold=2, K=34: already completed — skipping
Fold=2, K=35: already completed — skipping
Fold=2, K=36: already completed — skipping
Fold=2, K=37: already completed — skipping
Fold=2, K=38: already completed — skipping
Fold=2, K=39: already completed — skipping
Fold=2, K=40: already completed — skipping
Fold=2, K=41: already completed — skipping
Fold=2, K=42: already completed — skipping
Fold=2, K=43: already completed — skipping
Fold=2, K=44: already completed — skipping
Fold=2, K=45: already completed — skipping
Fold=2, K=46: already completed — skipping
Fold=2, K=47: already completed — skipping
Fold=2, K=48: already completed — skipping
Fold=2, K=49: already completed — skipping
Fold=2, K=50: already completed — skipping
Fold=2, K=51: already completed — skipping
Fold=2, K=52: already completed — skipping
Fold=2, K=53: already completed — skipping
Fold=2, K=54: already completed — skipping
Fold=2, K=55: already completed — skipping
Fold=2, K=56: already completed — skipping
Fold=2, K=57: already completed — skipping
Fold=2, K=58: already completed — skipping
Fold=2, K=59: already completed — skipping
Fold=2, K=60: already completed — skipping
Fold=2, K=61: already completed — skipping
Fold=2, K=62: already completed — skipping
Fold=2, K=63: already completed — skipping
Fold=2, K=64: already completed — skipping
Fold=2, K=65: already completed — skipping
Fold=2, K=66: already completed — skipping
Fold=2, K=67: already completed — skipping
Fold=2, K=68: already completed — skipping
Fold=2, K=69: already completed — skipping
Fold=2, K=70: already completed — skipping
Fold=2, K=71: already completed — skipping
Fold=2, K=72: already completed — skipping
Fold=2, K=73: already completed — skipping
Fold=2, K=74: already completed — skipping
Fold=2, K=75: already completed — skipping
Fold=2, K=76: already completed — skipping
Fold=2, K=77: already completed — skipping
Fold=2, K=78: already completed — skipping
Fold=2, K=79: already completed — skipping
Fold=2, K=80: already completed — skipping
Fold=2, K=81: already completed — skipping
Fold=2, K=82: already completed — skipping
Fold=2, K=83: already completed — skipping
Fold=2, K=84: already completed — skipping
Fold=2, K=85: already completed — skipping
Fold=2, K=86: already completed — skipping
Fold=2, K=87: already completed — skipping
Fold=2, K=88: already completed — skipping
Fold=2, K=89: already completed — skipping
Fold=2, K=90: already completed — skipping
✓ Fold=2, K=91 | UMass=-4.20202 | CV=0.56777 | UCI=-2.77643 | NPMI=-0.03991
✓ Fold=2, K=92 | UMass=-4.52346 | CV=0.56602 | UCI=-2.94673 | NPMI=-0.04400
✓ Fold=2, K=93 | UMass=-4.37335 | CV=0.58274 | UCI=-2.72391 | NPMI=-0.03590
✓ Fold=2, K=94 | UMass=-4.15128 | CV=0.59960 | UCI=-2.52615 | NPMI=-0.02654
✓ Fold=2, K=95 | UMass=-4.43697 | CV=0.56782 | UCI=-2.86532 | NPMI=-0.04166
✓ Fold=2, K=96 | UMass=-4.32298 | CV=0.56921 | UCI=-2.77658 | NPMI=-0.03778
✓ Fold=2, K=97 | UMass=-4.62714 | CV=0.57242 | UCI=-2.94054 | NPMI=-0.04261
✓ Fold=2, K=98 | UMass=-4.72419 | CV=0.58384 | UCI=-3.05641 | NPMI=-0.05040
✓ Fold=2, K=99 | UMass=-4.22384 | CV=0.59614 | UCI=-2.59067 | NPMI=-0.02868
✓ Fold=2, K=100 | UMass=-4.30477 | CV=0.56901 | UCI=-2.95162 | NPMI=-0.04626

======================================================================
FOLD 3
======================================================================
Training documents: 14638
Dictionary size   : 17589
✓ Fold=3, K=2 | UMass=-0.97850 | CV=0.72279 | UCI=0.35639 | NPMI=0.12191
✓ Fold=3, K=3 | UMass=-6.10281 | CV=0.60769 | UCI=-2.95902 | NPMI=-0.00036
✓ Fold=3, K=4 | UMass=-2.81969 | CV=0.69680 | UCI=-0.42811 | NPMI=0.08368
✓ Fold=3, K=5 | UMass=-1.47776 | CV=0.69530 | UCI=0.57708 | NPMI=0.12445
✓ Fold=3, K=6 | UMass=-1.40385 | CV=0.72991 | UCI=0.87312 | NPMI=0.13048
✓ Fold=3, K=7 | UMass=-1.43079 | CV=0.74131 | UCI=1.00556 | NPMI=0.13133
✓ Fold=3, K=8 | UMass=-1.51584 | CV=0.73822 | UCI=0.87816 | NPMI=0.12197
✓ Fold=3, K=9 | UMass=-1.52985 | CV=0.76103 | UCI=0.91519 | NPMI=0.13005
✓ Fold=3, K=10 | UMass=-1.57177 | CV=0.76340 | UCI=0.93646 | NPMI=0.12894
✓ Fold=3, K=11 | UMass=-1.65585 | CV=0.74168 | UCI=0.74303 | NPMI=0.11781
✓ Fold=3, K=12 | UMass=-1.67907 | CV=0.73722 | UCI=0.72875 | NPMI=0.12555
✓ Fold=3, K=13 | UMass=-2.35642 | CV=0.69320 | UCI=0.01248 | NPMI=0.08720
✓ Fold=3, K=14 | UMass=-2.05546 | CV=0.73075 | UCI=0.51589 | NPMI=0.10424
✓ Fold=3, K=15 | UMass=-2.25543 | CV=0.71895 | UCI=0.09176 | NPMI=0.09216
✓ Fold=3, K=16 | UMass=-2.43558 | CV=0.69407 | UCI=-0.09062 | NPMI=0.08572
✓ Fold=3, K=17 | UMass=-2.28360 | CV=0.69990 | UCI=-0.12314 | NPMI=0.07881
✓ Fold=3, K=18 | UMass=-2.25528 | CV=0.70307 | UCI=0.01953 | NPMI=0.08322
✓ Fold=3, K=19 | UMass=-2.03655 | CV=0.70149 | UCI=0.03075 | NPMI=0.08400
✓ Fold=3, K=20 | UMass=-2.28315 | CV=0.69765 | UCI=-0.12870 | NPMI=0.07669
✓ Fold=3, K=21 | UMass=-2.46080 | CV=0.68976 | UCI=-0.42030 | NPMI=0.06618
✓ Fold=3, K=22 | UMass=-2.68908 | CV=0.66449 | UCI=-0.58344 | NPMI=0.05974
✓ Fold=3, K=23 | UMass=-3.04740 | CV=0.64149 | UCI=-0.86967 | NPMI=0.04324
✓ Fold=3, K=24 | UMass=-2.57375 | CV=0.65734 | UCI=-0.48211 | NPMI=0.06111
✓ Fold=3, K=25 | UMass=-2.68264 | CV=0.65580 | UCI=-0.49393 | NPMI=0.05973
✓ Fold=3, K=26 | UMass=-2.29896 | CV=0.67954 | UCI=-0.08061 | NPMI=0.07329
✓ Fold=3, K=27 | UMass=-3.15449 | CV=0.66300 | UCI=-0.84442 | NPMI=0.04738
✓ Fold=3, K=28 | UMass=-2.44267 | CV=0.66544 | UCI=-0.34237 | NPMI=0.06522
✓ Fold=3, K=29 | UMass=-2.74096 | CV=0.67767 | UCI=-0.46265 | NPMI=0.06238
✓ Fold=3, K=30 | UMass=-2.99274 | CV=0.67599 | UCI=-0.60974 | NPMI=0.05335
✓ Fold=3, K=31 | UMass=-3.02521 | CV=0.65252 | UCI=-1.02189 | NPMI=0.03885
✓ Fold=3, K=32 | UMass=-3.17265 | CV=0.64565 | UCI=-1.14007 | NPMI=0.03083
✓ Fold=3, K=33 | UMass=-2.86057 | CV=0.63929 | UCI=-0.82425 | NPMI=0.04436
✓ Fold=3, K=34 | UMass=-2.44933 | CV=0.68834 | UCI=-0.15569 | NPMI=0.07396
✓ Fold=3, K=35 | UMass=-2.86396 | CV=0.68624 | UCI=-0.60082 | NPMI=0.05513
✓ Fold=3, K=36 | UMass=-3.37985 | CV=0.61499 | UCI=-1.43012 | NPMI=0.01907
✓ Fold=3, K=37 | UMass=-2.99087 | CV=0.65842 | UCI=-0.78011 | NPMI=0.05009
✓ Fold=3, K=38 | UMass=-3.56140 | CV=0.62038 | UCI=-1.52494 | NPMI=0.01473
✓ Fold=3, K=39 | UMass=-3.27359 | CV=0.63095 | UCI=-1.27608 | NPMI=0.02380
✓ Fold=3, K=40 | UMass=-3.34143 | CV=0.62577 | UCI=-1.28717 | NPMI=0.02440
✓ Fold=3, K=41 | UMass=-3.29952 | CV=0.62624 | UCI=-1.47134 | NPMI=0.01688
✓ Fold=3, K=42 | UMass=-3.29187 | CV=0.61867 | UCI=-1.47373 | NPMI=0.01587
✓ Fold=3, K=43 | UMass=-3.25149 | CV=0.61570 | UCI=-1.26756 | NPMI=0.02538
✓ Fold=3, K=44 | UMass=-3.44253 | CV=0.62467 | UCI=-1.35464 | NPMI=0.02282
✓ Fold=3, K=45 | UMass=-3.16146 | CV=0.62651 | UCI=-1.18052 | NPMI=0.02997
✓ Fold=3, K=46 | UMass=-3.69872 | CV=0.62113 | UCI=-1.67354 | NPMI=0.00652
✓ Fold=3, K=47 | UMass=-3.23827 | CV=0.61684 | UCI=-1.23285 | NPMI=0.02730
✓ Fold=3, K=48 | UMass=-3.05329 | CV=0.63129 | UCI=-1.00121 | NPMI=0.03836
✓ Fold=3, K=49 | UMass=-3.35202 | CV=0.59802 | UCI=-1.44235 | NPMI=0.01887
✓ Fold=3, K=50 | UMass=-3.52774 | CV=0.62329 | UCI=-1.45652 | NPMI=0.01673
✓ Fold=3, K=51 | UMass=-3.82847 | CV=0.60377 | UCI=-1.81877 | NPMI=0.00170
✓ Fold=3, K=52 | UMass=-3.36606 | CV=0.60393 | UCI=-1.46872 | NPMI=0.01687
✓ Fold=3, K=53 | UMass=-3.80364 | CV=0.60279 | UCI=-1.92534 | NPMI=-0.00120
✓ Fold=3, K=54 | UMass=-3.42488 | CV=0.60760 | UCI=-1.43758 | NPMI=0.01964
✓ Fold=3, K=55 | UMass=-3.39706 | CV=0.61812 | UCI=-1.49211 | NPMI=0.01590
✓ Fold=3, K=56 | UMass=-3.83610 | CV=0.58580 | UCI=-2.11019 | NPMI=-0.01190
✓ Fold=3, K=57 | UMass=-3.65615 | CV=0.60384 | UCI=-1.76055 | NPMI=0.00388
✓ Fold=3, K=58 | UMass=-3.66961 | CV=0.58283 | UCI=-1.80180 | NPMI=0.00395
✓ Fold=3, K=59 | UMass=-3.84003 | CV=0.60896 | UCI=-1.89587 | NPMI=0.00028
✓ Fold=3, K=60 | UMass=-4.09269 | CV=0.58010 | UCI=-2.09111 | NPMI=-0.00769
✓ Fold=3, K=61 | UMass=-3.76287 | CV=0.58698 | UCI=-1.94789 | NPMI=-0.00261
✓ Fold=3, K=62 | UMass=-3.77061 | CV=0.58045 | UCI=-2.11109 | NPMI=-0.01069
✓ Fold=3, K=63 | UMass=-4.04472 | CV=0.58834 | UCI=-2.20516 | NPMI=-0.01585
✓ Fold=3, K=64 | UMass=-3.78858 | CV=0.60003 | UCI=-1.96353 | NPMI=-0.00404
✓ Fold=3, K=65 | UMass=-3.71673 | CV=0.58939 | UCI=-1.83601 | NPMI=-0.00195
✓ Fold=3, K=66 | UMass=-3.79900 | CV=0.57335 | UCI=-2.00470 | NPMI=-0.00682
✓ Fold=3, K=67 | UMass=-3.72483 | CV=0.59968 | UCI=-1.82523 | NPMI=-0.00109
✓ Fold=3, K=68 | UMass=-4.13000 | CV=0.58264 | UCI=-2.39235 | NPMI=-0.02287
✓ Fold=3, K=69 | UMass=-3.65994 | CV=0.60389 | UCI=-1.80697 | NPMI=0.00300
✓ Fold=3, K=70 | UMass=-4.03390 | CV=0.58062 | UCI=-2.33234 | NPMI=-0.01957
✓ Fold=3, K=71 | UMass=-3.73566 | CV=0.58627 | UCI=-1.91529 | NPMI=-0.00408
✓ Fold=3, K=72 | UMass=-4.30182 | CV=0.58000 | UCI=-2.50892 | NPMI=-0.02423
✓ Fold=3, K=73 | UMass=-3.81851 | CV=0.57450 | UCI=-2.16375 | NPMI=-0.01095
✓ Fold=3, K=74 | UMass=-3.92068 | CV=0.60047 | UCI=-1.98596 | NPMI=-0.00492
✓ Fold=3, K=75 | UMass=-4.10071 | CV=0.57149 | UCI=-2.31047 | NPMI=-0.02030
✓ Fold=3, K=76 | UMass=-3.74934 | CV=0.58886 | UCI=-1.95470 | NPMI=-0.00400
✓ Fold=3, K=77 | UMass=-4.05271 | CV=0.58260 | UCI=-2.18172 | NPMI=-0.01209
✓ Fold=3, K=78 | UMass=-4.12542 | CV=0.57058 | UCI=-2.47538 | NPMI=-0.02540
✓ Fold=3, K=79 | UMass=-4.32052 | CV=0.57074 | UCI=-2.61342 | NPMI=-0.03019
✓ Fold=3, K=80 | UMass=-3.90463 | CV=0.58275 | UCI=-2.13681 | NPMI=-0.01224
✓ Fold=3, K=81 | UMass=-3.89720 | CV=0.57029 | UCI=-2.24450 | NPMI=-0.01740
✓ Fold=3, K=82 | UMass=-4.11567 | CV=0.56520 | UCI=-2.52460 | NPMI=-0.03007
✓ Fold=3, K=83 | UMass=-4.08205 | CV=0.54886 | UCI=-2.65215 | NPMI=-0.03487
✓ Fold=3, K=84 | UMass=-4.21080 | CV=0.57045 | UCI=-2.44348 | NPMI=-0.02592
✓ Fold=3, K=85 | UMass=-3.79039 | CV=0.56670 | UCI=-2.21522 | NPMI=-0.01790
✓ Fold=3, K=86 | UMass=-4.41891 | CV=0.56275 | UCI=-2.79937 | NPMI=-0.04022
✓ Fold=3, K=87 | UMass=-4.19826 | CV=0.56893 | UCI=-2.65145 | NPMI=-0.03452
✓ Fold=3, K=88 | UMass=-4.08364 | CV=0.57148 | UCI=-2.50776 | NPMI=-0.03045
✓ Fold=3, K=89 | UMass=-4.43885 | CV=0.54878 | UCI=-2.91620 | NPMI=-0.04833
✓ Fold=3, K=90 | UMass=-4.30941 | CV=0.56130 | UCI=-2.76863 | NPMI=-0.03996
✓ Fold=3, K=91 | UMass=-4.41073 | CV=0.53112 | UCI=-3.03929 | NPMI=-0.05161
✓ Fold=3, K=92 | UMass=-4.25189 | CV=0.54288 | UCI=-2.76358 | NPMI=-0.03993
✓ Fold=3, K=93 | UMass=-4.25539 | CV=0.54841 | UCI=-2.91398 | NPMI=-0.04582
✓ Fold=3, K=94 | UMass=-4.12198 | CV=0.56236 | UCI=-2.49480 | NPMI=-0.02979
✓ Fold=3, K=95 | UMass=-4.19232 | CV=0.56739 | UCI=-2.58375 | NPMI=-0.03250
✓ Fold=3, K=96 | UMass=-3.93637 | CV=0.55596 | UCI=-2.50859 | NPMI=-0.03047
✓ Fold=3, K=97 | UMass=-4.20093 | CV=0.54060 | UCI=-2.89775 | NPMI=-0.04760
✓ Fold=3, K=98 | UMass=-4.10794 | CV=0.55538 | UCI=-2.65099 | NPMI=-0.03700
✓ Fold=3, K=99 | UMass=-4.34069 | CV=0.54678 | UCI=-3.03497 | NPMI=-0.05053
✓ Fold=3, K=100 | UMass=-4.06559 | CV=0.56065 | UCI=-2.57650 | NPMI=-0.03240

======================================================================
FOLD 4
======================================================================
Training documents: 14638
Dictionary size   : 17883
✓ Fold=4, K=2 | UMass=-1.07443 | CV=0.71355 | UCI=1.02838 | NPMI=0.15853
✓ Fold=4, K=3 | UMass=-1.23426 | CV=0.71777 | UCI=0.94296 | NPMI=0.14239
✓ Fold=4, K=4 | UMass=-1.27065 | CV=0.72126 | UCI=0.83032 | NPMI=0.12295
✓ Fold=4, K=5 | UMass=-1.44222 | CV=0.74721 | UCI=0.84335 | NPMI=0.13172
✓ Fold=4, K=6 | UMass=-2.40148 | CV=0.72603 | UCI=0.09699 | NPMI=0.11001
✓ Fold=4, K=7 | UMass=-1.54479 | CV=0.74901 | UCI=0.80394 | NPMI=0.13863
✓ Fold=4, K=8 | UMass=-1.53118 | CV=0.74074 | UCI=0.75367 | NPMI=0.13065
✓ Fold=4, K=9 | UMass=-1.56491 | CV=0.74270 | UCI=0.78024 | NPMI=0.12157
✓ Fold=4, K=10 | UMass=-1.72617 | CV=0.73413 | UCI=0.68360 | NPMI=0.11446
✓ Fold=4, K=11 | UMass=-2.15633 | CV=0.68078 | UCI=0.16616 | NPMI=0.09453
✓ Fold=4, K=12 | UMass=-2.10547 | CV=0.70104 | UCI=0.13007 | NPMI=0.08614
✓ Fold=4, K=13 | UMass=-1.91029 | CV=0.71941 | UCI=0.42735 | NPMI=0.10120
✓ Fold=4, K=14 | UMass=-2.47039 | CV=0.70342 | UCI=-0.02094 | NPMI=0.08766
✓ Fold=4, K=15 | UMass=-2.81215 | CV=0.67728 | UCI=-0.29254 | NPMI=0.07666
✓ Fold=4, K=16 | UMass=-2.43162 | CV=0.71053 | UCI=0.10274 | NPMI=0.09233
✓ Fold=4, K=17 | UMass=-2.70935 | CV=0.69776 | UCI=-0.07568 | NPMI=0.08083
✓ Fold=4, K=18 | UMass=-2.87939 | CV=0.69097 | UCI=-0.36146 | NPMI=0.07272
✓ Fold=4, K=19 | UMass=-3.14901 | CV=0.65723 | UCI=-0.84809 | NPMI=0.04799
✓ Fold=4, K=20 | UMass=-2.43549 | CV=0.71116 | UCI=-0.12971 | NPMI=0.07944
✓ Fold=4, K=21 | UMass=-2.50807 | CV=0.69133 | UCI=-0.30715 | NPMI=0.06992
✓ Fold=4, K=22 | UMass=-2.39142 | CV=0.70509 | UCI=-0.20964 | NPMI=0.07916
✓ Fold=4, K=23 | UMass=-2.83875 | CV=0.68538 | UCI=-0.44707 | NPMI=0.06862
✓ Fold=4, K=24 | UMass=-2.67828 | CV=0.67921 | UCI=-0.52553 | NPMI=0.06196
✓ Fold=4, K=25 | UMass=-2.85260 | CV=0.68490 | UCI=-0.49190 | NPMI=0.06463
✓ Fold=4, K=26 | UMass=-2.41258 | CV=0.68775 | UCI=-0.18667 | NPMI=0.07305
✓ Fold=4, K=27 | UMass=-3.26251 | CV=0.64401 | UCI=-1.10683 | NPMI=0.03632
✓ Fold=4, K=28 | UMass=-2.89550 | CV=0.68259 | UCI=-0.49693 | NPMI=0.06166
✓ Fold=4, K=29 | UMass=-2.97796 | CV=0.68789 | UCI=-0.51071 | NPMI=0.06435
✓ Fold=4, K=30 | UMass=-3.19937 | CV=0.68526 | UCI=-0.86462 | NPMI=0.04761
✓ Fold=4, K=31 | UMass=-3.16002 | CV=0.66814 | UCI=-0.75007 | NPMI=0.05530
✓ Fold=4, K=32 | UMass=-2.56916 | CV=0.68939 | UCI=-0.20589 | NPMI=0.07518
✓ Fold=4, K=33 | UMass=-3.04396 | CV=0.65847 | UCI=-0.85232 | NPMI=0.04667
✓ Fold=4, K=34 | UMass=-2.63395 | CV=0.68737 | UCI=-0.28807 | NPMI=0.07583
✓ Fold=4, K=35 | UMass=-3.18546 | CV=0.67302 | UCI=-0.91916 | NPMI=0.04590
✓ Fold=4, K=36 | UMass=-2.91829 | CV=0.69246 | UCI=-0.39869 | NPMI=0.06789

,ExperimentID,Fold,Topics,Coherence_UMass,Coherence_CV,Coherence_UCI,Coherence_NPMI
0,NG_F1_K2,1,2,-6.624327,0.482003,-3.988233,-0.077489
1,NG_F1_K3,1,3,-1.259477,0.679111,0.346130,0.106190
2,NG_F1_K4,1,4,-1.392020,0.674515,0.317378,0.092768
3,NG_F1_K5,1,5,-1.521834,0.713990,0.531896,0.112504
4,NG_F1_K6,1,6,-1.502607,0.711919,0.554199,0.104472
5,NG_F1_K7,1,7,-1.848268,0.661607,0.029384,0.077049
6,NG_F1_K8,1,8,-2.852878,0.627860,-0.894749,0.038876
7,NG_F1_K9,1,9,-1.645164,0.691442,0.091416,0.089063
8,NG_F1_K10,1,10,-1.984278,0.685445,-0.150716,0.077739
9,NG_F1_K11,1,11,-1.840151,0.702560,0.168077,0.090852

In [ ]:
# ============================================================
# NG04-8R — Validate Raw Metrics and Build Master Metric Table
# ============================================================

import numpy as np
import pandas as pd

print("=" * 80)
print("NG04-8R — RAW METRIC VALIDATION AND MERGE")
print("=" * 80)

# ------------------------------------------------------------
# Reload final files
# ------------------------------------------------------------


METRIC_DIR = BASE_DIR / "metrics"

COHERENCE_FINAL = (
    METRIC_DIR
    / "ng04_coherence_all_models.csv"
)

PERPLEXITY_FINAL = (
    METRIC_DIR
    / "ng04_perplexity_all_models.csv"
)


perplexity_df = pd.read_csv(
    PERPLEXITY_FINAL
)

coherence_df = pd.read_csv(
    COHERENCE_FINAL
)

# ------------------------------------------------------------
# Basic integrity
# ------------------------------------------------------------

print("\nPerplexity rows :", len(perplexity_df))
print("Coherence rows  :", len(coherence_df))

assert len(perplexity_df) == 495
assert len(coherence_df) == 495

assert (
    perplexity_df[
        ["Fold", "Topics"]
    ].duplicated().sum()
    == 0
)

assert (
    coherence_df[
        ["Fold", "Topics"]
    ].duplicated().sum()
    == 0
)

# ------------------------------------------------------------
# Raw coherence sign/range analysis
# ------------------------------------------------------------

coherence_columns = [
    "Coherence_UMass",
    "Coherence_CV",
    "Coherence_UCI",
    "Coherence_NPMI"
]

sign_rows = []

for column in coherence_columns:

    values = coherence_df[column]

    sign_rows.append({

        "Metric":
            column,

        "Minimum":
            values.min(),

        "Maximum":
            values.max(),

        "Mean":
            values.mean(),

        "Negative":
            int((values < 0).sum()),

        "Zero":
            int((values == 0).sum()),

        "Positive":
            int((values > 0).sum()),

        "NegativePct":
            100 * (values < 0).mean(),

        "PositivePct":
            100 * (values > 0).mean()
    })


coherence_sign_summary = pd.DataFrame(
    sign_rows
)

print("\n" + "=" * 80)
print("RAW COHERENCE SIGN SUMMARY")
print("=" * 80)

display(
    coherence_sign_summary
)


# ------------------------------------------------------------
# Merge raw metric results
# ------------------------------------------------------------

metric_master_df = pd.merge(

    perplexity_df,

    coherence_df,

    on=[
        "ExperimentID",
        "Fold",
        "Topics"
    ],

    how="inner",

    validate="one_to_one"
)


metric_master_df = (
    metric_master_df
    .sort_values(
        ["Fold", "Topics"]
    )
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# Validate merge
# ------------------------------------------------------------

print("\n" + "=" * 80)
print("MASTER TABLE VALIDATION")
print("=" * 80)

print(
    "Rows              :",
    len(metric_master_df)
)

print(
    "Columns           :",
    len(metric_master_df.columns)
)

print(
    "Unique Fold-K     :",
    metric_master_df[
        ["Fold", "Topics"]
    ].drop_duplicates().shape[0]
)

print(
    "Missing values    :",
    metric_master_df.isna().sum().sum()
)


assert len(metric_master_df) == 495

assert (
    metric_master_df[
        ["Fold", "Topics"]
    ].drop_duplicates().shape[0]
    == 495
)

assert (
    metric_master_df
    .isna()
    .sum()
    .sum()
    == 0
)


# ------------------------------------------------------------
# Save raw master table
# ------------------------------------------------------------

RAW_MASTER_FILE = (
    METRIC_DIR
    / "ng04_raw_metric_master.csv"
)

metric_master_df.to_csv(
    RAW_MASTER_FILE,
    index=False
)


print("\nSaved:")
print(RAW_MASTER_FILE)

print("\n" + "=" * 80)
print("✓ RAW COHERENCE VALUES PRESERVED")
print("✓ PERPLEXITY + COHERENCE MERGED")
print("✓ 495 UNIQUE EXPERIMENTS VERIFIED")
print("=" * 80)

display(
    metric_master_df.head()
)

================================================================================
NG04-8R — RAW METRIC VALIDATION AND MERGE
================================================================================

Perplexity rows : 495
Coherence rows  : 495

================================================================================
RAW COHERENCE SIGN SUMMARY
================================================================================

,Metric,Minimum,Maximum,Mean,Negative,Zero,Positive,NegativePct,PositivePct
0,Coherence_UMass,-6.624327,-0.978500,-3.405733,495,0,0,100.000000,0.000000
1,Coherence_CV,0.482003,0.816420,0.631627,0,0,495,0.000000,100.000000
2,Coherence_UCI,-3.988233,1.343336,-1.459762,427,0,68,86.262626,13.737374
3,Coherence_NPMI,-0.077489,0.182041,0.020750,209,0,286,42.222222,57.777778

================================================================================
MASTER TABLE VALIDATION
================================================================================
Rows              : 495
Columns           : 11
Unique Fold-K     : 495
Missing values    : 0

Saved:
/content/drive/MyDrive/LDAChatGPT/NewsGroupsTopicEval/metrics/ng04_raw_metric_master.csv

================================================================================
✓ RAW COHERENCE VALUES PRESERVED
✓ PERPLEXITY + COHERENCE MERGED
✓ 495 UNIQUE EXPERIMENTS VERIFIED
================================================================================

,ExperimentID,Fold,Topics,TrainLogPerplexity,TestLogPerplexity,TrainPerplexity,TestPerplexity,Coherence_UMass,Coherence_CV,Coherence_UCI,Coherence_NPMI
0,NG_F1_K2,1,2,-8.166942,-8.218584,287.405039,297.879338,-6.624327,0.482003,-3.988233,-0.077489
1,NG_F1_K3,1,3,-8.017795,-8.114469,259.177277,277.139657,-1.259477,0.679111,0.346130,0.106190
2,NG_F1_K4,1,4,-7.962156,-8.111846,249.372131,276.636202,-1.392020,0.674515,0.317378,0.092768
3,NG_F1_K5,1,5,-7.929313,-8.109783,243.759208,276.240885,-1.521834,0.713990,0.531896,0.112504
4,NG_F1_K6,1,6,-7.908885,-8.111695,240.331941,276.607296,-1.502607,0.711919,0.554199,0.104472

In [ ]:
# ============================================================
# NG04-8S — Exact Original Fold-wise NAC and NAP
# ============================================================

import numpy as np
import pandas as pd

print("=" * 80)
print("NG04-8S — ORIGINAL NAC AND NAP TRANSFORMATIONS")
print("=" * 80)

# ------------------------------------------------------------
# Start from validated raw metric master table
# ------------------------------------------------------------

metric_df = pd.read_csv(
    RAW_MASTER_FILE
)

assert len(metric_df) == 495

assert (
    metric_df[
        ["Fold", "Topics"]
    ].duplicated().sum()
    == 0
)

# ============================================================
# 1. Absolute coherence values
# ============================================================

metric_df["AbsUMass"] = (
    metric_df["Coherence_UMass"].abs()
)

metric_df["AbsCV"] = (
    metric_df["Coherence_CV"].abs()
)

metric_df["AbsUCI"] = (
    metric_df["Coherence_UCI"].abs()
)

metric_df["AbsNPMI"] = (
    metric_df["Coherence_NPMI"].abs()
)

# ============================================================
# 2. Fold-wise NAC
# ============================================================

metric_df["NAC_UMass"] = (
    metric_df["AbsUMass"]
    /
    metric_df.groupby("Fold")[
        "AbsUMass"
    ].transform("max")
)

metric_df["NAC_CV"] = (
    metric_df["AbsCV"]
    /
    metric_df.groupby("Fold")[
        "AbsCV"
    ].transform("max")
)

metric_df["NAC_UCI"] = (
    metric_df["AbsUCI"]
    /
    metric_df.groupby("Fold")[
        "AbsUCI"
    ].transform("max")
)

metric_df["NAC_NPMI"] = (
    metric_df["AbsNPMI"]
    /
    metric_df.groupby("Fold")[
        "AbsNPMI"
    ].transform("max")
)

# ============================================================
# 3. Original NAP
# ============================================================
#
# Original notebook:
#
# MeanLogPerplexity
# -> absolute value
# -> divide by fold-wise maximum absolute log-perplexity
#
# For this replication, the corresponding held-out quantity is
# TestLogPerplexity computed in NG04-8O.
# ============================================================

metric_df["MeanLogPerplexity"] = (
    metric_df["TestLogPerplexity"]
)

metric_df["AbsLogPerplexity"] = (
    metric_df["MeanLogPerplexity"].abs()
)

metric_df["NAP"] = (
    metric_df["AbsLogPerplexity"]
    /
    metric_df.groupby("Fold")[
        "AbsLogPerplexity"
    ].transform("max")
)

# ============================================================
# Validation
# ============================================================

transformed_columns = [
    "NAC_UMass",
    "NAC_CV",
    "NAC_UCI",
    "NAC_NPMI",
    "NAP"
]

assert np.isfinite(
    metric_df[
        transformed_columns
    ].to_numpy()
).all()

for column in transformed_columns:

    assert (
        metric_df[column] >= 0
    ).all()

    assert (
        metric_df[column] <= 1
    ).all()


# Every fold should contain a maximum-normalized value of 1
for fold in range(1, 6):

    fold_df = metric_df[
        metric_df["Fold"] == fold
    ]

    for column in transformed_columns:

        assert np.isclose(
            fold_df[column].max(),
            1.0
        )


# ============================================================
# Save transformed master table
# ============================================================

TRANSFORMED_MASTER_FILE = (
    METRIC_DIR
    / "ng04_metric_master_with_nac_nap.csv"
)

metric_df.to_csv(
    TRANSFORMED_MASTER_FILE,
    index=False
)

print(
    "\nSaved:",
    TRANSFORMED_MASTER_FILE
)


# ============================================================
# Fold-wise maxima used for normalization
# ============================================================

normalization_summary = (
    metric_df
    .groupby("Fold")
    .agg(
        MaxAbsUMass=("AbsUMass", "max"),
        MaxAbsCV=("AbsCV", "max"),
        MaxAbsUCI=("AbsUCI", "max"),
        MaxAbsNPMI=("AbsNPMI", "max"),
        MaxAbsLogPerplexity=(
            "AbsLogPerplexity",
            "max"
        )
    )
)

print("\n" + "=" * 80)
print("FOLD-WISE NORMALIZATION DENOMINATORS")
print("=" * 80)

display(
    normalization_summary
)


# ============================================================
# Topic number selected by each transformed metric
# ============================================================

selection_rows = []

for fold in range(1, 6):

    fold_df = metric_df[
        metric_df["Fold"] == fold
    ]

    row = {
        "Fold": fold
    }

    for column in transformed_columns:

        selected_index = (
            fold_df[column]
            .idxmax()
        )

        row[column] = int(
            metric_df.loc[
                selected_index,
                "Topics"
            ]
        )

    selection_rows.append(
        row
    )


selection_summary = pd.DataFrame(
    selection_rows
)

print("\n" + "=" * 80)
print("K SELECTED BY ORIGINAL NAC/NAP")
print("=" * 80)

display(
    selection_summary
)


print("\n" + "=" * 80)
print("✓ ORIGINAL ABSOLUTE-VALUE TRANSFORMATION REPRODUCED")
print("✓ NAC NORMALIZED WITHIN EACH FOLD")
print("✓ NAP NORMALIZED WITHIN EACH FOLD")
print("✓ ALL TRANSFORMED VALUES ARE IN [0, 1]")
print("=" * 80)

display(
    metric_df[
        [
            "ExperimentID",
            "Fold",
            "Topics",

            "Coherence_UMass",
            "AbsUMass",
            "NAC_UMass",

            "Coherence_CV",
            "AbsCV",
            "NAC_CV",

            "Coherence_UCI",
            "AbsUCI",
            "NAC_UCI",

            "Coherence_NPMI",
            "AbsNPMI",
            "NAC_NPMI",

            "MeanLogPerplexity",
            "AbsLogPerplexity",
            "NAP"
        ]
    ].head(10)
)

================================================================================
NG04-8S — ORIGINAL NAC AND NAP TRANSFORMATIONS
================================================================================

Saved: /content/drive/MyDrive/LDAChatGPT/NewsGroupsTopicEval/metrics/ng04_metric_master_with_nac_nap.csv

================================================================================
FOLD-WISE NORMALIZATION DENOMINATORS
================================================================================

      MaxAbsUMass  MaxAbsCV  MaxAbsUCI  MaxAbsNPMI  MaxAbsLogPerplexity
Fold
1        6.624327  0.713990   3.988233    0.112504            15.484621
2        4.826798  0.771700   3.101405    0.155436            11.452576
3        6.102812  0.763401   3.039293    0.131329            12.210208
4        4.529384  0.749012   2.940584    0.158527            11.562086
5        4.786634  0.816420   3.215946    0.182041            11.861954

================================================================================
K SELECTED BY ORIGINAL NAC/NAP
================================================================================

   Fold  NAC_UMass  NAC_CV  NAC_UCI  NAC_NPMI  NAP
0     1          2       5        2         5  100
1     2         84       4       84         4  100
2     3          3      10       91         7  100
3     4         94       7       98         2  100
4     5         80       5       86         5  100

================================================================================
✓ ORIGINAL ABSOLUTE-VALUE TRANSFORMATION REPRODUCED
✓ NAC NORMALIZED WITHIN EACH FOLD
✓ NAP NORMALIZED WITHIN EACH FOLD
✓ ALL TRANSFORMED VALUES ARE IN [0, 1]
================================================================================

,ExperimentID,Fold,Topics,Coherence_UMass,AbsUMass,NAC_UMass,Coherence_CV,AbsCV,NAC_CV,Coherence_UCI,AbsUCI,NAC_UCI,Coherence_NPMI,AbsNPMI,NAC_NPMI,MeanLogPerplexity,AbsLogPerplexity,NAP
0,NG_F1_K2,1,2,-6.624327,6.624327,1.000000,0.482003,0.482003,0.675084,-3.988233,3.988233,1.000000,-0.077489,0.077489,0.688772,-8.218584,8.218584,0.530758
1,NG_F1_K3,1,3,-1.259477,1.259477,0.190129,0.679111,0.679111,0.951148,0.346130,0.346130,0.086788,0.106190,0.106190,0.943884,-8.114469,8.114469,0.524034
2,NG_F1_K4,1,4,-1.392020,1.392020,0.210138,0.674515,0.674515,0.944711,0.317378,0.317378,0.079579,0.092768,0.092768,0.824573,-8.111846,8.111846,0.523865
3,NG_F1_K5,1,5,-1.521834,1.521834,0.229734,0.713990,0.713990,1.000000,0.531896,0.531896,0.133366,0.112504,0.112504,1.000000,-8.109783,8.109783,0.523731
4,NG_F1_K6,1,6,-1.502607,1.502607,0.226832,0.711919,0.711919,0.997099,0.554199,0.554199,0.138959,0.104472,0.104472,0.928611,-8.111695,8.111695,0.523855
5,NG_F1_K7,1,7,-1.848268,1.848268,0.279012,0.661607,0.661607,0.926633,0.029384,0.029384,0.007368,0.077049,0.077049,0.684861,-8.142549,8.142549,0.525847
6,NG_F1_K8,1,8,-2.852878,2.852878,0.430667,0.627860,0.627860,0.879367,-0.894749,0.894749,0.224347,0.038876,0.038876,0.345551,-8.171427,8.171427,0.527712
7,NG_F1_K9,1,9,-1.645164,1.645164,0.248352,0.691442,0.691442,0.968419,0.091416,0.091416,0.022921,0.089063,0.089063,0.791647,-8.178067,8.178067,0.528141
8,NG_F1_K10,1,10,-1.984278,1.984278,0.299544,0.685445,0.685445,0.960020,-0.150716,0.150716,0.037790,0.077739,0.077739,0.690991,-8.215569,8.215569,0.530563
9,NG_F1_K11,1,11,-1.840151,1.840151,0.277787,0.702560,0.702560,0.983991,0.168077,0.168077,0.042143,0.090852,0.090852,0.807549,-8.323661,8.323661,0.537544

In [ ]:
# ============================================================
# NG04-8T — Raw vs Transformed Ranking Diagnostics
# ============================================================

import numpy as np
import pandas as pd
from scipy.stats import spearmanr

print("=" * 80)
print("NG04-8T — RAW VS TRANSFORMED RANKING DIAGNOSTICS")
print("=" * 80)

metric_df = pd.read_csv(
    TRANSFORMED_MASTER_FILE
)

# ------------------------------------------------------------
# Metric definitions
# ------------------------------------------------------------
#
# For coherence:
#   larger raw coherence = better
#
# For log-perplexity:
#   larger log-perplexity = better
#   because -8 is better than -12.
#
# Transformed NAC/NAP are selected by maximum.
# ------------------------------------------------------------

metric_pairs = {
    "NAC_UMass": (
        "Coherence_UMass",
        "NAC_UMass"
    ),

    "NAC_CV": (
        "Coherence_CV",
        "NAC_CV"
    ),

    "NAC_UCI": (
        "Coherence_UCI",
        "NAC_UCI"
    ),

    "NAC_NPMI": (
        "Coherence_NPMI",
        "NAC_NPMI"
    ),

    "NAP": (
        "MeanLogPerplexity",
        "NAP"
    )
}

diagnostic_rows = []

for fold in range(1, 6):

    fold_df = (
        metric_df[
            metric_df["Fold"] == fold
        ]
        .copy()
        .sort_values("Topics")
        .reset_index(drop=True)
    )

    for metric_name, (
        raw_column,
        transformed_column
    ) in metric_pairs.items():

        # ----------------------------------------------------
        # Original raw ranking
        # rank 1 = best
        # ----------------------------------------------------

        raw_rank = (
            fold_df[raw_column]
            .rank(
                ascending=False,
                method="average"
            )
        )

        # ----------------------------------------------------
        # Transformed ranking
        # rank 1 = best
        # ----------------------------------------------------

        transformed_rank = (
            fold_df[transformed_column]
            .rank(
                ascending=False,
                method="average"
            )
        )

        # ----------------------------------------------------
        # Best K under raw metric
        # ----------------------------------------------------

        raw_best_index = (
            fold_df[raw_column]
            .idxmax()
        )

        raw_best_k = int(
            fold_df.loc[
                raw_best_index,
                "Topics"
            ]
        )

        # ----------------------------------------------------
        # Best K under transformed metric
        # ----------------------------------------------------

        transformed_best_index = (
            fold_df[transformed_column]
            .idxmax()
        )

        transformed_best_k = int(
            fold_df.loc[
                transformed_best_index,
                "Topics"
            ]
        )

        # ----------------------------------------------------
        # Ranking agreement
        # ----------------------------------------------------

        spearman_rho, _ = spearmanr(
            raw_rank,
            transformed_rank
        )

        mean_abs_rank_difference = float(
            np.mean(
                np.abs(
                    raw_rank
                    - transformed_rank
                )
            )
        )

        max_abs_rank_difference = float(
            np.max(
                np.abs(
                    raw_rank
                    - transformed_rank
                )
            )
        )

        different_rank_positions = int(
            np.sum(
                raw_rank
                != transformed_rank
            )
        )

        diagnostic_rows.append({

            "Fold":
                fold,

            "Metric":
                metric_name,

            "RawMetric":
                raw_column,

            "TransformedMetric":
                transformed_column,

            "RawBestK":
                raw_best_k,

            "TransformedBestK":
                transformed_best_k,

            "BestKAgreement":
                int(
                    raw_best_k
                    == transformed_best_k
                ),

            "SpearmanRho":
                spearman_rho,

            "DifferentRankPositions":
                different_rank_positions,

            "MeanAbsoluteRankDifference":
                mean_abs_rank_difference,

            "MaxAbsoluteRankDifference":
                max_abs_rank_difference
        })


ranking_diagnostic_df = pd.DataFrame(
    diagnostic_rows
)

# ============================================================
# Save fold-level diagnostics
# ============================================================

RANKING_DIAGNOSTIC_FILE = (
    METRIC_DIR
    / "ng04_raw_vs_transformed_ranking.csv"
)

ranking_diagnostic_df.to_csv(
    RANKING_DIAGNOSTIC_FILE,
    index=False
)


# ============================================================
# Display fold-level results
# ============================================================

print("\n" + "=" * 80)
print("FOLD-LEVEL RANKING DIAGNOSTICS")
print("=" * 80)

display(
    ranking_diagnostic_df
)


# ============================================================
# Metric-level summary
# ============================================================

ranking_summary_df = (
    ranking_diagnostic_df
    .groupby("Metric")
    .agg(
        Folds=(
            "Fold",
            "count"
        ),

        BestKAgreements=(
            "BestKAgreement",
            "sum"
        ),

        BestKAgreementPct=(
            "BestKAgreement",
            lambda x: 100 * x.mean()
        ),

        MeanSpearmanRho=(
            "SpearmanRho",
            "mean"
        ),

        MeanDifferentRankPositions=(
            "DifferentRankPositions",
            "mean"
        ),

        MeanAbsoluteRankDifference=(
            "MeanAbsoluteRankDifference",
            "mean"
        ),

        MaximumRankDifference=(
            "MaxAbsoluteRankDifference",
            "max"
        )
    )
    .reset_index()
)


RANKING_SUMMARY_FILE = (
    METRIC_DIR
    / "ng04_raw_vs_transformed_ranking_summary.csv"
)

ranking_summary_df.to_csv(
    RANKING_SUMMARY_FILE,
    index=False
)

print("\n" + "=" * 80)
print("METRIC-LEVEL SUMMARY")
print("=" * 80)

display(
    ranking_summary_df
)


print("\nSaved:")
print(RANKING_DIAGNOSTIC_FILE)
print(RANKING_SUMMARY_FILE)

print("\n" + "=" * 80)
print("✓ RAW AND TRANSFORMED RANKINGS COMPARED")
print("✓ FOLD-LEVEL BEST-K AGREEMENT MEASURED")
print("✓ SPEARMAN RANK AGREEMENT MEASURED")
print("✓ RANK-POSITION DISTORTION MEASURED")
print("=" * 80)

================================================================================
NG04-8T — RAW VS TRANSFORMED RANKING DIAGNOSTICS
================================================================================

================================================================================
FOLD-LEVEL RANKING DIAGNOSTICS
================================================================================

,Fold,Metric,RawMetric,TransformedMetric,RawBestK,TransformedBestK,BestKAgreement,SpearmanRho,DifferentRankPositions,MeanAbsoluteRankDifference,MaxAbsoluteRankDifference
0,1,NAC_UMass,Coherence_UMass,NAC_UMass,3,2,0,-1.000000,98,49.494949,98.0
1,1,NAC_CV,Coherence_CV,NAC_CV,5,5,1,1.000000,0,0.000000,0.0
2,1,NAC_UCI,Coherence_UCI,NAC_UCI,6,2,0,-0.984552,98,49.494949,98.0
3,1,NAC_NPMI,Coherence_NPMI,NAC_NPMI,5,5,1,0.348918,82,24.484848,81.0
4,1,NAP,MeanLogPerplexity,NAP,5,100,0,-1.000000,98,49.494949,98.0
5,2,NAC_UMass,Coherence_UMass,NAC_UMass,2,84,0,-1.000000,98,49.494949,98.0
6,2,NAC_CV,Coherence_CV,NAC_CV,4,4,1,1.000000,0,0.000000,0.0
7,2,NAC_UCI,Coherence_UCI,NAC_UCI,4,84,0,-0.982362,98,49.494949,98.0
8,2,NAC_NPMI,Coherence_NPMI,NAC_NPMI,4,4,1,0.514051,74,20.000000,74.0
9,2,NAP,MeanLogPerplexity,NAP,5,100,0,-1.000000,98,49.494949,98.0
10,3,NAC_UMass,Coherence_UMass,NAC_UMass,2,3,0,-1.000000,98,49.494949,98.0
11,3,NAC_CV,Coherence_CV,NAC_CV,10,10,1,1.000000,0,0.000000,0.0
12,3,NAC_UCI,Coherence_UCI,NAC_UCI,7,91,0,-0.962165,98,49.494949,98.0
13,3,NAC_NPMI,Coherence_NPMI,NAC_NPMI,7,7,1,0.536487,71,19.959596,70.0
14,3,NAP,MeanLogPerplexity,NAP,5,100,0,-1.000000,98,49.494949,98.0
15,4,NAC_UMass,Coherence_UMass,NAC_UMass,2,94,0,-1.000000,98,49.494949,98.0
16,4,NAC_CV,Coherence_CV,NAC_CV,7,7,1,1.000000,0,0.000000,0.0
17,4,NAC_UCI,Coherence_UCI,NAC_UCI,2,98,0,-0.948275,98,49.494949,98.0
18,4,NAC_NPMI,Coherence_NPMI,NAC_NPMI,2,2,1,0.759518,59,12.767677,59.0
19,4,NAP,MeanLogPerplexity,NAP,4,100,0,-1.000000,98,49.494949,98.0
20,5,NAC_UMass,Coherence_UMass,NAC_UMass,2,80,0,-1.000000,98,49.494949,98.0
21,5,NAC_CV,Coherence_CV,NAC_CV,5,5,1,1.000000,0,0.000000,0.0
22,5,NAC_UCI,Coherence_UCI,NAC_UCI,5,86,0,-0.968831,98,49.494949,98.0
23,5,NAC_NPMI,Coherence_NPMI,NAC_NPMI,5,5,1,0.519270,71,20.121212,71.0
24,5,NAP,MeanLogPerplexity,NAP,7,100,0,-1.000000,98,49.494949,98.0

================================================================================
METRIC-LEVEL SUMMARY
================================================================================

,Metric,Folds,BestKAgreements,BestKAgreementPct,MeanSpearmanRho,MeanDifferentRankPositions,MeanAbsoluteRankDifference,MaximumRankDifference
0,NAC_CV,5,5,100.0,1.000000,0.0,0.000000,0.0
1,NAC_NPMI,5,5,100.0,0.535649,71.4,19.466667,81.0
2,NAC_UCI,5,0,0.0,-0.969237,98.0,49.494949,98.0
3,NAC_UMass,5,0,0.0,-1.000000,98.0,49.494949,98.0
4,NAP,5,0,0.0,-1.000000,98.0,49.494949,98.0

Saved:
/content/drive/MyDrive/LDAChatGPT/NewsGroupsTopicEval/metrics/ng04_raw_vs_transformed_ranking.csv
/content/drive/MyDrive/LDAChatGPT/NewsGroupsTopicEval/metrics/ng04_raw_vs_transformed_ranking_summary.csv

================================================================================
✓ RAW AND TRANSFORMED RANKINGS COMPARED
✓ FOLD-LEVEL BEST-K AGREEMENT MEASURED
✓ SPEARMAN RANK AGREEMENT MEASURED
✓ RANK-POSITION DISTORTION MEASURED
================================================================================

In [ ]:
# ============================================================
# NG04-8U — Correct NAP Ranking Direction
#          NAP is a MINIMIZATION criterion
# ============================================================

import numpy as np
import pandas as pd
from scipy.stats import spearmanr

print("=" * 80)
print("NG04-8U — CORRECT NAP RANKING DIAGNOSTIC")
print("=" * 80)

METRIC_FILE = (
    BASE_DIR
    / "metrics"
    / "ng04_metric_master_with_nac_nap.csv"
)

df = pd.read_csv(METRIC_FILE)

assert len(df) == 495

# ============================================================
# Correct direction:
#
# MeanLogPerplexity:
# higher / less negative = better
#
# NAP:
# smaller = better
#
# Therefore:
# raw ranking      -> descending MeanLogPerplexity
# transformed rank -> ascending NAP
# ============================================================

rows = []

for fold in sorted(df["Fold"].unique()):

    fold_df = (
        df[df["Fold"] == fold]
        .copy()
        .sort_values("Topics")
        .reset_index(drop=True)
    )

    # --------------------------------------------------------
    # Raw log-perplexity ranking:
    # larger / less negative is better
    # --------------------------------------------------------

    fold_df["RawRank"] = (
        fold_df["MeanLogPerplexity"]
        .rank(
            ascending=False,
            method="min"
        )
    )

    # --------------------------------------------------------
    # NAP ranking:
    # smaller is better
    # --------------------------------------------------------

    fold_df["NAPRank"] = (
        fold_df["NAP"]
        .rank(
            ascending=True,
            method="min"
        )
    )

    rho, _ = spearmanr(
        fold_df["RawRank"],
        fold_df["NAPRank"]
    )

    different_positions = (
        fold_df["RawRank"]
        !=
        fold_df["NAPRank"]
    ).sum()

    mean_abs_rank_difference = (
        fold_df["RawRank"]
        .sub(fold_df["NAPRank"])
        .abs()
        .mean()
    )

    max_abs_rank_difference = (
        fold_df["RawRank"]
        .sub(fold_df["NAPRank"])
        .abs()
        .max()
    )

    raw_best_k = int(
        fold_df.loc[
            fold_df[
                "MeanLogPerplexity"
            ].idxmax(),
            "Topics"
        ]
    )

    nap_best_k = int(
        fold_df.loc[
            fold_df[
                "NAP"
            ].idxmin(),
            "Topics"
        ]
    )

    rows.append(
        {
            "Fold": fold,
            "SpearmanRho":
                rho,

            "DifferentRankPositions":
                int(different_positions),

            "MeanAbsRankDifference":
                mean_abs_rank_difference,

            "MaxAbsRankDifference":
                max_abs_rank_difference,

            "RawBestK":
                raw_best_k,

            "NAPBestK":
                nap_best_k,

            "BestKAgreement":
                raw_best_k == nap_best_k
        }
    )

nap_corrected_diagnostic = pd.DataFrame(
    rows
)

# ============================================================
# Display
# ============================================================

print("\nCorrect NAP ranking diagnostic:")
display(
    nap_corrected_diagnostic
)

print(
    "\nBest-K agreement:",
    int(
        nap_corrected_diagnostic[
            "BestKAgreement"
        ].sum()
    ),
    "/",
    len(nap_corrected_diagnostic)
)

print(
    "Mean Spearman rho:",
    nap_corrected_diagnostic[
        "SpearmanRho"
    ].mean()
)

print(
    "Mean absolute rank difference:",
    nap_corrected_diagnostic[
        "MeanAbsRankDifference"
    ].mean()
)

# ============================================================
# Save
# ============================================================

OUTPUT_FILE = (
    BASE_DIR
    / "metrics"
    / "ng04_nap_corrected_ranking_diagnostic.csv"
)

nap_corrected_diagnostic.to_csv(
    OUTPUT_FILE,
    index=False
)

print("\nSaved:")
print(OUTPUT_FILE)

print("\n" + "=" * 80)
print("✓ NAP TREATED AS MINIMIZATION CRITERION")
print("✓ RAW AND TRANSFORMED RANKINGS COMPARED IN CORRECT DIRECTIONS")
print("=" * 80)

================================================================================
NG04-8U — CORRECT NAP RANKING DIAGNOSTIC
================================================================================

Correct NAP ranking diagnostic:

,Fold,SpearmanRho,DifferentRankPositions,MeanAbsRankDifference,MaxAbsRankDifference,RawBestK,NAPBestK,BestKAgreement
0,1,1.0,0,0.0,0.0,5,5,True
1,2,1.0,0,0.0,0.0,5,5,True
2,3,1.0,0,0.0,0.0,5,5,True
3,4,1.0,0,0.0,0.0,4,4,True
4,5,1.0,0,0.0,0.0,7,7,True

Best-K agreement: 5 / 5
Mean Spearman rho: 0.9999999999999998
Mean absolute rank difference: 0.0

Saved:
/content/drive/MyDrive/LDAChatGPT/NewsGroupsTopicEval/metrics/ng04_nap_corrected_ranking_diagnostic.csv

================================================================================
✓ NAP TREATED AS MINIMIZATION CRITERION
✓ RAW AND TRANSFORMED RANKINGS COMPARED IN CORRECT DIRECTIONS
================================================================================