Part 3A
Initialization & Configuration.

This part does not train LDA.

Its only responsibility is

load configuration;
load fold information;
create output folders;
create logger;
initialize experiment;
prepare for long execution;

In [83]:
# ============================================================
# TopicEvalBench
# Notebook 3
#
# Part 3A
# Initialization & Configuration
#
# This notebook trains LDA models and extracts topic
# representations for downstream evaluation.
#
# IMPORTANT
# ----------
# This notebook DOES NOT perform classification.
# Classification is performed in Notebook 4.
#
# Author : Mahedi Hasan
# ============================================================

In [84]:
!pip -q install \
gensim \
pyLDAvis \
openpyxl

In [85]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [86]:
import os
import gc
import json
import time
import pickle
import random
import logging
import warnings
import sys

from pathlib import Path

import numpy as np
import pandas as pd
import sklearn

from tqdm.auto import tqdm

import gensim

from gensim import corpora
from gensim.models import LdaModel
from gensim.models import CoherenceModel

from datetime import datetime

print("=" * 60)
print("Python :", sys.version)
print("NumPy  :", np.__version__)
print("Pandas :", pd.__version__)
print("Sklearn:", sklearn.__version__)
print("Gensim :", gensim.__version__)
print("=" * 60)

warnings.filterwarnings("ignore")

============================================================
Python : 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]
NumPy  : 2.0.2
Pandas : 2.2.2
Sklearn: 1.6.1
Gensim : 4.4.0
============================================================

In [87]:
# ------------------------------------------------------------
# Load configuration
# ------------------------------------------------------------

PROJECT_ROOT = Path("/content/drive/MyDrive/TopicEvalBench")

CONFIG_FILE = PROJECT_ROOT/"config"/"config.json"

with open(CONFIG_FILE) as f:

    CONFIG = json.load(f)

print("Configuration Loaded")

Configuration Loaded

In [88]:
NUM_FOLDS = CONFIG["n_folds"]

MIN_TOPICS=CONFIG["topic_range"]["minimum"]

MAX_TOPICS=CONFIG["topic_range"]["maximum"]


REMOVE_BELOW = CONFIG["remove_below"]

REMOVE_ABOVE = CONFIG["remove_above"]

RANDOM_STATE=CONFIG["random_seed"]

#LDA Parameters
LDA_CHUNKSIZE=CONFIG["lda"]["chunksize"]

TOP_WORDS=CONFIG["top_words"]

LDA_PASSES=CONFIG["lda"]["passes"]

LDA_ITERATIONS=CONFIG["lda"]["iterations"]

LDA_CHUNKSIZE=CONFIG["lda"]["chunksize"]

ALPHA=CONFIG["lda"]["alpha"]

ETA=CONFIG["lda"]["eta"]

LDA_UPDATE_EVERY=CONFIG["lda"]["update_every"]

LDA_DECAY=CONFIG["lda"]["decay"]

LDA_OFFSET=CONFIG["lda"]["offset"]

MINIMUM_PROBABILITY=CONFIG["lda"]["minimum_probability"]

PER_WORD_TOPICS=CONFIG["lda"]["per_word_topics"]

EVAL_EVERY=CONFIG["lda"]["eval_every"]

DTYPE=np.float32

print("Configuration Loaded")

print(CONFIG)

Configuration Loaded
{'project_name': 'TopicEvalBench', 'dataset_name': 'TREC', 'dataset_file': 'TREC.xlsx', 'text_column': 'Text', 'label_column': 'Label', 'document_id_column': 'DocumentID', 'label_id_column': 'LabelID', 'random_seed': 42, 'n_folds': 5, 'remove_below': 5, 'remove_above': 0.5, 'topic_range': {'minimum': 2, 'maximum': 100}, 'lda': {'passes': 20, 'iterations': 400, 'chunksize': 2000, 'alpha': 'symmetric', 'eta': 'auto', 'update_every': 1, 'decay': 0.5, 'offset': 1.0, 'minimum_probability': 0.0, 'per_word_topics': False, 'eval_every': None, 'dtype': 'float32'}, 'top_words': 20, 'classifier': {'name': 'LogisticRegression', 'solver': 'lbfgs', 'max_iter': 1000, 'random_state': 42}, 'created_by': 'Notebook_01'}

In [89]:
TOPIC_LIST = list(

    range(

        MIN_TOPICS,

        MAX_TOPICS+1

    )

)

print(TOPIC_LIST[:20])

print()

print("Total Topic Numbers =",len(TOPIC_LIST))

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]

Total Topic Numbers = 99

In [90]:
MODEL_DIR = PROJECT_ROOT/"models"

VECTOR_DIR = PROJECT_ROOT/"topic_vectors"

METRIC_DIR = PROJECT_ROOT/"intrinsic_metrics"

LOG_DIR = PROJECT_ROOT/"logs"

DICTIONARY_DIR = PROJECT_ROOT/"dictionary"

for directory in [

    MODEL_DIR,

    VECTOR_DIR,

    METRIC_DIR,

    LOG_DIR,

    DICTIONARY_DIR

]:

    directory.mkdir(

        parents=True,

        exist_ok=True

    )

print("Directories Ready")

Directories Ready

In [91]:
LOG_FILE = LOG_DIR/"Notebook3.log"

logging.basicConfig(

    filename=LOG_FILE,

    level=logging.INFO,

    format="%(asctime)s %(message)s"

)

logging.info("Notebook 3 Started")

print(LOG_FILE)

/content/drive/MyDrive/TopicEvalBench/logs/Notebook3.log

In [92]:
random.seed(RANDOM_STATE)

np.random.seed(RANDOM_STATE)

os.environ["PYTHONHASHSEED"]=str(RANDOM_STATE)

print("Seed =",RANDOM_STATE)

Seed = 42

In [93]:
def print_line():

    print("="*70)

In [94]:
def load_fold(fold):

    train_file = (

        PROJECT_ROOT/

        "folds"/

        f"Fold_{fold}"/

        "train.xlsx"

    )

    test_file = (

        PROJECT_ROOT/

        "folds"/

        f"Fold_{fold}"/

        "test.xlsx"

    )

    train = pd.read_excel(train_file)

    test = pd.read_excel(test_file)

    return train,test

In [95]:
train,test = load_fold(1)

print(train.shape)

print(test.shape)

train.head()

(240, 5)
(60, 5)

,DocumentID,Text,Label,LabelID,Tokens
0,8042410,Development of primary cultured chicken myogen...,108,0,"['development', 'primary', 'cultured', 'chicke..."
1,8132718,Constitutive centripetal transport of the acti...,108,0,"['constitutive', 'centripetal', 'transport', '..."
2,8673465,BACKGROUND: The green fluorescent protein (GFP...,108,0,"['background', 'green', 'fluorescent', 'protei..."
3,8707050,We report fluorescent resonance energy transfe...,108,0,"['report', 'fluorescent', 'resonance', 'energy..."
4,9175625,The trafficking of the androgen receptor (AR) ...,108,0,"['trafficking', 'androgen', 'receptor', 'ar', ..."

In [96]:
for fold in range(1,NUM_FOLDS+1):

    (MODEL_DIR/f"Fold_{fold}").mkdir(

        parents=True,

        exist_ok=True

    )

    (VECTOR_DIR/f"Fold_{fold}").mkdir(

        parents=True,

        exist_ok=True

    )

    (DICTIONARY_DIR/f"Fold_{fold}").mkdir(

        parents=True,

        exist_ok=True

    )

In [97]:
print_line()

print("Notebook 3")

print_line()

print("Number of folds :",NUM_FOLDS)

print("Topic Range :",MIN_TOPICS,"-",MAX_TOPICS)

print("Total Topic Numbers :",len(TOPIC_LIST))

print("LDA Passes :",LDA_PASSES)

print("Iterations :",LDA_ITERATIONS)

print_line()

======================================================================
Notebook 3
======================================================================
Number of folds : 5
Topic Range : 2 - 100
Total Topic Numbers : 99
LDA Passes : 20
Iterations : 400
======================================================================

In [98]:
TOTAL_JOBS = NUM_FOLDS * len(TOPIC_LIST)

print("Total LDA Models =",TOTAL_JOBS)

Total LDA Models = 495

In [99]:
gc.collect()

print("Initialization Completed Successfully.")

Initialization Completed Successfully.

Part 3B
Dictionary & Corpus Construction
Responsibilities

For each fold:

Load train/test data.
Convert token strings back to Python lists.
Build the dictionary using only the training fold.
Filter extreme words.
Save the dictionary.
Convert train/test documents into BoW using the same dictionary.
Save BoW corpora for later LDA training.

No LDA model is trained in this part.

In [100]:
# ============================================================
# Part 3B
# Dictionary & Corpus Construction
# ============================================================

print_line()
print("Part 3B : Dictionary & Corpus Construction")
print_line()

======================================================================
Part 3B : Dictionary & Corpus Construction
======================================================================

In [101]:
import ast

from gensim.corpora import Dictionary

In [102]:
def restore_tokens(token_column):
    """
    Convert token strings stored in Excel
    back to Python lists.
    """

    restored = []

    for item in token_column:

        if isinstance(item, list):

            restored.append(item)

        else:

            restored.append(ast.literal_eval(item))

    return restored

In [103]:
def build_dictionary(train_tokens):
    """
    Build dictionary using ONLY
    training documents.
    """

    dictionary = Dictionary(train_tokens)

    # Vocabulary size before filtering
    vocab_before = len(dictionary)

    dictionary.filter_extremes(
        no_below=REMOVE_BELOW,
        no_above=REMOVE_ABOVE
    )

    dictionary.compactify()

    # Vocabulary size after filtering
    vocab_after = len(dictionary)

    return dictionary, vocab_before, vocab_after

In [104]:
def create_bow(tokens, dictionary):
    """
    Convert tokenized documents
    into Bag-of-Words representation.
    """

    corpus = []

    for document in tokens:

        bow = dictionary.doc2bow(document)

        corpus.append(bow)

    return corpus

In [105]:
def save_dictionary(dictionary, fold):

    filename = (

        DICTIONARY_DIR /

        f"Fold_{fold}" /

        "dictionary.dict"

    )

    dictionary.save(str(filename))

    return filename

In [106]:
def save_corpus(corpus, filename):

    with open(filename, "wb") as f:

        pickle.dump(corpus, f)

In [107]:
import json

def save_dictionary_stats(
    dictionary,
    fold,
    train_docs,
    vocab_before,
    vocab_after,
    no_below,
    no_above
):
    """
    Save dictionary statistics for reproducibility.
    """

    stats = {

        "fold": fold,

        "num_documents_train": train_docs,

        "vocabulary_before_filtering": vocab_before,

        "vocabulary_after_filtering": vocab_after,

        "no_below": no_below,

        "no_above": no_above,

        "dictionary_size": len(dictionary),

        "random_seed": RANDOM_STATE,

        "created_by": "Notebook_03_Part3B"

    }

    output_file = (
        DICTIONARY_DIR /
        f"Fold_{fold}" /
        "dictionary_stats.json"
    )

    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(
            stats,
            f,
            indent=4
        )

    return output_file

In [108]:
def process_fold(fold):

    print_line()

    print(f"Processing Fold {fold}")

    train, test = load_fold(fold)

    train_tokens = restore_tokens(train["Tokens"])

    test_tokens = restore_tokens(test["Tokens"])

    dictionary, vocab_before, vocab_after = build_dictionary(
    train_tokens)

    dictionary_file = save_dictionary(

        dictionary,

        fold

    )

    stats_file = save_dictionary_stats(

    dictionary=dictionary,

    fold=fold,

    train_docs=len(train_tokens),

    vocab_before=vocab_before,

    vocab_after=vocab_after,

    no_below=REMOVE_BELOW,

    no_above=REMOVE_ABOVE)


    train_corpus = create_bow(

        train_tokens,

        dictionary

    )

    test_corpus = create_bow(

        test_tokens,

        dictionary

    )

    corpus_dir = MODEL_DIR / f"Fold_{fold}"

    save_corpus(

        train_corpus,

        corpus_dir / "train_corpus.pkl"

    )

    save_corpus(

        test_corpus,

        corpus_dir / "test_corpus.pkl"

    )

    print(f"Vocabulary Before Filtering : {vocab_before}")

    print(f"Vocabulary After Filtering  : {vocab_after}")

    print(f"Dictionary Size             : {len(dictionary)}")

    print(f"Training Docs   : {len(train_corpus)}")

    print(f"Testing Docs    : {len(test_corpus)}")

    logging.info(

        f"Fold {fold} processed."

    )

    print()

    print("Dictionary saved to")

    print(dictionary_file)

    print()

    print("Statistics saved to")

    print(stats_file)

    return dictionary

In [109]:
for fold in range(1, NUM_FOLDS + 1):

    process_fold(fold)

======================================================================
Processing Fold 1
Vocabulary Before Filtering : 4051
Vocabulary After Filtering  : 891
Dictionary Size             : 891
Training Docs   : 240
Testing Docs    : 60

Dictionary saved to
/content/drive/MyDrive/TopicEvalBench/dictionary/Fold_1/dictionary.dict

Statistics saved to
/content/drive/MyDrive/TopicEvalBench/dictionary/Fold_1/dictionary_stats.json
======================================================================
Processing Fold 2
Vocabulary Before Filtering : 4106
Vocabulary After Filtering  : 860
Dictionary Size             : 860
Training Docs   : 240
Testing Docs    : 60

Dictionary saved to
/content/drive/MyDrive/TopicEvalBench/dictionary/Fold_2/dictionary.dict

Statistics saved to
/content/drive/MyDrive/TopicEvalBench/dictionary/Fold_2/dictionary_stats.json
======================================================================
Processing Fold 3
Vocabulary Before Filtering : 4136
Vocabulary After Filtering  : 857
Dictionary Size             : 857
Training Docs   : 240
Testing Docs    : 60

Dictionary saved to
/content/drive/MyDrive/TopicEvalBench/dictionary/Fold_3/dictionary.dict

Statistics saved to
/content/drive/MyDrive/TopicEvalBench/dictionary/Fold_3/dictionary_stats.json
======================================================================
Processing Fold 4
Vocabulary Before Filtering : 4159
Vocabulary After Filtering  : 886
Dictionary Size             : 886
Training Docs   : 240
Testing Docs    : 60

Dictionary saved to
/content/drive/MyDrive/TopicEvalBench/dictionary/Fold_4/dictionary.dict

Statistics saved to
/content/drive/MyDrive/TopicEvalBench/dictionary/Fold_4/dictionary_stats.json
======================================================================
Processing Fold 5
Vocabulary Before Filtering : 4162
Vocabulary After Filtering  : 882
Dictionary Size             : 882
Training Docs   : 240
Testing Docs    : 60

Dictionary saved to
/content/drive/MyDrive/TopicEvalBench/dictionary/Fold_5/dictionary.dict

Statistics saved to
/content/drive/MyDrive/TopicEvalBench/dictionary/Fold_5/dictionary_stats.json

In [110]:
dictionary = Dictionary.load(

    str(

        DICTIONARY_DIR /

        "Fold_1" /

        "dictionary.dict"

    )

)

print("Dictionary Size :", len(dictionary))

print()

for token_id in range(min(20, len(dictionary))):

    print(token_id, "->", dictionary[token_id])

Dictionary Size : 891

0 -> absence
1 -> accumulation
2 -> addition
3 -> along
4 -> among
5 -> analysis
6 -> cellular
7 -> chain
8 -> change
9 -> chicken
10 -> cultured
11 -> cycle
12 -> development
13 -> differentiation
14 -> distribution
15 -> early
16 -> expressed
17 -> expression
18 -> first
19 -> found

In [111]:
with open(

    MODEL_DIR /

    "Fold_1" /

    "train_corpus.pkl",

    "rb"

) as f:

    corpus = pickle.load(f)

print("Number of Documents :", len(corpus))

print()

print("First Document")

print(corpus[0])

Number of Documents : 240

First Document
[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 1), (8, 1), (9, 1), (10, 1), (11, 1), (12, 1), (13, 2), (14, 1), (15, 1), (16, 3), (17, 1), (18, 3), (19, 2), (20, 1), (21, 1), (22, 1), (23, 1), (24, 1), (25, 2), (26, 2), (27, 1), (28, 1), (29, 1), (30, 2), (31, 1), (32, 1), (33, 1), (34, 1), (35, 1), (36, 2), (37, 1), (38, 1), (39, 1), (40, 1), (41, 1), (42, 1), (43, 1), (44, 1), (45, 1), (46, 1), (47, 1), (48, 2), (49, 1), (50, 1), (51, 1), (52, 1), (53, 1)]

In [112]:
print_line()

print("Dictionary & Corpus Construction Completed")

print()

print(f"Processed Folds : {NUM_FOLDS}")

print(f"Dictionary saved in : {DICTIONARY_DIR}")

print(f"Corpora saved in : {MODEL_DIR}")

print_line()

======================================================================
Dictionary & Corpus Construction Completed

Processed Folds : 5
Dictionary saved in : /content/drive/MyDrive/TopicEvalBench/dictionary
Corpora saved in : /content/drive/MyDrive/TopicEvalBench/models
======================================================================

In [113]:
dictionary_sizes = []

for fold in range(1, NUM_FOLDS + 1):

    dictionary = Dictionary.load(
        str(
            DICTIONARY_DIR /
            f"Fold_{fold}" /
            "dictionary.dict"
        )
    )

    dictionary_sizes.append(len(dictionary))

summary = pd.DataFrame({
    "Fold": range(1, NUM_FOLDS + 1),
    "Dictionary_Size": dictionary_sizes
})

print(summary)

print("\nMean Dictionary Size :", summary["Dictionary_Size"].mean())
print("Std Dev :", summary["Dictionary_Size"].std())
print("Min :", summary["Dictionary_Size"].min())
print("Max :", summary["Dictionary_Size"].max())

   Fold  Dictionary_Size
0     1              891
1     2              860
2     3              857
3     4              886
4     5              882

Mean Dictionary Size : 875.2
Std Dev : 15.61089363233252
Min : 857
Max : 891

Notebook 3C-1,

This section only prepares everything for LDA training. No LDA model is trained yet.

In [114]:
# ============================================================
# Part 3C
# LDA Model Training
#
# Responsibilities
# ----------------
# 1. Load dictionary
# 2. Load corpus
# 3. Train LDA
# 4. Save model
# 5. Save metadata
# 6. Save Phi matrix
# 7. Save Theta matrix
# 8. Save topic statistics
#
# No intrinsic evaluation here.
# No classification here.
# ============================================================

print_line()
print("Part 3C : LDA Model Training")
print_line()

======================================================================
Part 3C : LDA Model Training
======================================================================

In [115]:
import os
import gc
import json
import time
import pickle

import numpy as np
import pandas as pd

from pathlib import Path

from tqdm.auto import tqdm

from gensim.models import LdaModel
from gensim.corpora import Dictionary

In [116]:
def load_dictionary(fold):
    """
    Load dictionary of a fold.
    """

    dictionary_file = (
        DICTIONARY_DIR /
        f"Fold_{fold}" /
        "dictionary.dict"
    )

    dictionary = Dictionary.load(str(dictionary_file))

    return dictionary

In [117]:
def load_corpus(fold):
    """
    Load train and test corpus.
    """

    corpus_dir = MODEL_DIR / f"Fold_{fold}"

    with open(corpus_dir / "train_corpus.pkl", "rb") as f:
        train_corpus = pickle.load(f)

    with open(corpus_dir / "test_corpus.pkl", "rb") as f:
        test_corpus = pickle.load(f)

    return train_corpus, test_corpus

In [118]:
def load_training_dataframe(fold):

    train_df, _ = load_fold(fold)

    return train_df

In [119]:
def load_testing_dataframe(fold):

    _, test_df = load_fold(fold)

    return test_df

In [120]:
def create_model_directory(fold, K):

    model_dir = (
        MODEL_DIR /
        f"Fold_{fold}" /
        f"K_{K:03d}"
    )

    model_dir.mkdir(
        parents=True,
        exist_ok=True
    )

    return model_dir

In [121]:
training_summary = []

In [122]:
fold = 1

dictionary = load_dictionary(fold)

train_corpus, test_corpus = load_corpus(fold)

train_df = load_training_dataframe(fold)

print("Dictionary Size :", len(dictionary))

print("Training Docs   :", len(train_corpus))

print("Testing Docs    :", len(test_corpus))

print("Train DataFrame :", train_df.shape)

Dictionary Size : 891
Training Docs   : 240
Testing Docs    : 60
Train DataFrame : (240, 5)

In [123]:
folder = create_model_directory(1,20)

print(folder)

/content/drive/MyDrive/TopicEvalBench/models/Fold_1/K_020

In [124]:
gc.collect()

print("Part 3C-1 Completed Successfully.")

Part 3C-1 Completed Successfully.

Notebook 3C-2

Train and Save One LDA Model

In [125]:
import gensim

def save_metadata(
    model_dir,
    fold,
    K,
    dictionary,
    train_corpus,
    lda,
    training_time
):
    """
    Save metadata for one trained LDA model.
    """

    metadata = {

    # -----------------------------
    # Dataset
    # -----------------------------
    "fold": fold,
    "topics": K,
    "documents": len(train_corpus),
    "dictionary_size": len(dictionary),

    # -----------------------------
    # Training Parameters
    # -----------------------------
    "passes": LDA_PASSES,
    "iterations": LDA_ITERATIONS,
    "chunksize": LDA_CHUNKSIZE,

    "alpha": (
        lda.alpha.tolist()
        if hasattr(lda.alpha, "tolist")
        else str(lda.alpha)
    ),

    "eta": str(lda.eta),

    "update_every": LDA_UPDATE_EVERY,
    "decay": LDA_DECAY,
    "offset": LDA_OFFSET,

    "minimum_probability": MINIMUM_PROBABILITY,

    "per_word_topics": PER_WORD_TOPICS,

    "eval_every": EVAL_EVERY,

    "dtype": str(DTYPE),

    # -----------------------------
    # Reproducibility
    # -----------------------------
    "random_seed": RANDOM_STATE,
    "gensim_version": gensim.__version__,

    # -----------------------------
    # Performance
    # -----------------------------
    "training_time_seconds": round(training_time, 4),

    "log_perplexity_train":
        float(
            lda.log_perplexity(train_corpus)
        ),

    # -----------------------------
    # Notebook
    # -----------------------------
    "created_by": "Notebook_03_Part3C",

    "model_path": str(model_dir / "lda.model"),
    "theta_train_file": str(model_dir / "theta_train.csv"),
    "theta_test_file": str(model_dir / "theta_test.csv"),
    "phi_path": str(model_dir / "phi.csv"),
    "top_words_path": str(model_dir / "top_words.csv"),
    "topic_sizes_path": str(model_dir / "topic_sizes.csv"),

    "dictionary_path": str(
    DICTIONARY_DIR /
    f"Fold_{fold}" /
    "dictionary.dict"),

    "train_corpus_path": str(
    MODEL_DIR /
    f"Fold_{fold}" /
    "train_corpus.pkl"),
    }

    output_file = model_dir / "metadata.json"

    with open(output_file, "w", encoding="utf-8") as f:

        json.dump(
            metadata,
            f,
            indent=4
        )

In [126]:
def train_single_lda(
    fold,
    K
):
    """
    Train one LDA model.

    Returns
    -------
    lda
        Trained gensim LDA model.
    """

    dictionary = load_dictionary(fold)

    train_corpus, _ = load_corpus(fold)

    model_dir = create_model_directory(
        fold,
        K
    )

    print(f"Training Fold {fold}  K={K}")

    start_time = time.time()


    lda = LdaModel(

    corpus=train_corpus,

    id2word=dictionary,

    num_topics=K,

    random_state=RANDOM_STATE,

    passes=LDA_PASSES,

    iterations=LDA_ITERATIONS,

    chunksize=LDA_CHUNKSIZE,

    alpha=ALPHA,

    eta=ETA,

    update_every=LDA_UPDATE_EVERY,

    decay=LDA_DECAY,

    offset=LDA_OFFSET,

    eval_every=EVAL_EVERY,

    minimum_probability=MINIMUM_PROBABILITY,

    per_word_topics=PER_WORD_TOPICS,

    dtype=DTYPE
    )

    training_time = time.time() - start_time

    lda.save(
        str(
            model_dir /
            "lda.model"
        )
    )

    save_metadata(

        model_dir=model_dir,

        fold=fold,

        K=K,

        dictionary=dictionary,

        train_corpus=train_corpus,

        lda=lda,

        training_time=training_time

    )

    print(f"Finished in {training_time:.2f} seconds")

    return lda

In [127]:
lda = train_single_lda(

    fold=1,

    K=5

)

Training Fold 1  K=5
Finished in 6.02 seconds

In [128]:
model = LdaModel.load(

    str(

        MODEL_DIR /

        "Fold_1" /

        "K_005" /

        "lda.model"

    )

)

print(model)

LdaModel<num_terms=891, num_topics=5, decay=0.5, chunksize=2000>

In [129]:
metadata_file = (

    MODEL_DIR /

    "Fold_1" /

    "K_005" /

    "metadata.json"

)

with open(
    metadata_file,
    "r"
) as f:

    metadata = json.load(f)

metadata

{'fold': 1,
 'topics': 5,
 'documents': 240,
 'dictionary_size': 891,
 'passes': 20,
 'iterations': 400,
 'chunksize': 2000,
 'alpha': [0.20000000298023224,
  0.20000000298023224,
  0.20000000298023224,
  0.20000000298023224,
  0.20000000298023224],
 'eta': '[0.34800598 0.5017559  0.5347968  0.21995631 0.45029557 1.7414714\n 0.33190185 0.38513726 0.607558   0.1790911  0.24233264 0.38946405\n 0.65419203 0.30550027 0.30878255 0.75669134 0.4086989  1.7628483\n 0.34840432 1.6783191  0.18046997 0.3386618  0.21368214 0.2848632\n 0.29833418 0.3534899  0.21227327 1.1514271  0.43806693 0.26938173\n 1.5476742  0.22286184 0.49046603 0.6305704  1.1847092  0.43884432\n 0.6170383  0.22473352 0.3038548  0.20269312 0.67921674 0.3426452\n 0.47925767 0.26342994 0.20819435 0.47572625 0.24663693 0.8121762\n 0.3148815  0.21663071 0.32881653 0.20556524 0.9010773  1.3890481\n 0.32977772 0.35762116 1.0092175  0.20782049 1.8375325  0.6576163\n 0.4325214  0.23492591 0.25143126 0.2698252  0.27701473 0.29718402\n 0.38373396 0.66318107 0.7069511  0.3674875  0.2098975  0.7075143\n 0.19382414 0.335421   0.30181375 0.45782772 1.0671934  0.32321015\n 0.7823645  0.2582907  0.20378274 1.364878   0.3029169  0.9605517\n 0.37490726 0.75651777 0.265407   0.2768124  2.0255535  0.24945699\n 0.21729396 0.6756987  0.8714769  0.37559545 1.0768862  0.23683812\n 0.25295034 0.20448598 0.78669274 0.42965928 0.20509577 0.6724687\n 0.558197   0.5422872  2.3241093  0.93442005 0.41142085 0.38089743\n 1.2513983  0.28975472 0.3551026  0.30206993 0.39165422 0.26442868\n 0.27997756 0.22136484 0.5666592  0.25700086 0.64529306 0.32557794\n 0.34245634 0.493326   0.42439675 0.8604888  0.22042038 1.3233765\n 0.5492335  0.24346262 0.37296838 0.18192518 0.17402253 1.12498\n 0.39690533 0.28584933 0.20112269 0.20021857 0.2530978  0.25346228\n 0.35211423 0.5994433  0.2287434  0.2598951  0.46914154 0.6528544\n 0.20006907 0.22685596 0.2869022  0.37072992 1.9256535  0.19736928\n 0.3112684  0.86746705 0.23025808 0.33052468 0.3951756  0.28746992\n 0.20420901 0.30686674 0.34265253 0.29804397 0.2904169  0.43065292\n 0.53971124 0.18845752 2.05638    0.21085823 0.17931448 0.31799674\n 0.2913223  0.30545974 0.19859546 0.3140978  0.21802044 0.9545663\n 0.2660096  0.66945565 0.22639883 0.7956694  0.23511039 0.23382212\n 0.3260764  0.3984388  0.56068355 1.0883278  0.26286057 0.59159744\n 0.26077273 0.32318836 0.23982184 0.20449628 1.6304787  0.23236935\n 0.24956255 0.50424874 0.35497868 0.3771797  0.2514572  0.32168272\n 0.32117674 0.2821486  0.23822352 0.31896782 0.20504813 0.20763373\n 0.8613796  0.73594767 0.33813423 0.76629937 0.28655416 1.5526824\n 0.36056706 0.2917641  0.28044996 0.2637575  0.7796548  0.23983254\n 0.17255382 0.31586486 0.8589573  0.2625483  0.24151811 0.4290768\n 0.24560618 0.42474115 0.20269065 0.32099298 0.3536273  0.2668504\n 0.27069807 0.40815726 0.9023785  0.26102823 0.20513085 0.27885827\n 0.20098421 0.4091996  0.17044505 0.4638578  0.6748929  0.57787514\n 0.36950225 0.3017681  0.92687273 0.2428244  0.31346303 0.26906624\n 0.32095206 0.69443566 0.27904326 0.3972383  0.23857461 0.24787465\n 0.31375232 0.38434252 0.34231913 0.58144796 0.2436582  0.34809256\n 0.36387554 0.189832   0.20447978 0.3272706  0.25981575 0.30235878\n 0.4840936  0.2980055  0.23825465 0.25634733 0.43885472 0.3020665\n 0.71625346 0.2356867  0.28106177 0.21562466 0.4164287  0.66006494\n 0.46015576 0.85767543 0.21719404 0.38352865 0.258009   0.60968226\n 0.17568232 0.2558266  0.6134488  0.30784017 0.25335607 0.46273005\n 0.20832339 0.5363018  0.26910755 0.71930975 0.49599317 0.39499527\n 0.44141194 0.2725746  0.27859777 0.6501947  0.32655123 0.24434957\n 0.23934565 0.25041455 0.22595556 0.34087446 0.4412524  0.94364655\n 0.2626741  0.31440488 0.27748096 0.2930835  0.2967216  0.22504176\n 0.26712397 1.1520151  0.20749865 0.42781368 2.0368376  0.86024576\n 0.48918164 0.28958496 0.29578474 0.8181893  0.21937415 0.6818044\n 0.2440508  0.21575452 0.30511647 0.20367226 0.20292978 0.3181296\n 0.42353445 0.39628997 0.3950782  0.31129685 0.30238515 0.63271266\n 0.5585079  0.21615498 0.27297768 0.53376824 0.24311672 0.26441446\n 0.63647217 0.21011673 0.20575683 0.33344918 0.4668806  0.28970996\n 0.5726659  0.41740313 0.5864073  0.21010734 0.4878227  0.3754283\n 0.25106502 1.337333   0.2270086  0.2418972  0.20943254 0.4657552\n 0.45102698 0.3415975  0.30327794 0.40694493 0.5004151  0.21128431\n 0.45109636 0.21885917 0.24163476 0.3428676  0.33154604 0.24459377\n 0.5789153  0.25376505 0.26924834 0.20825765 0.18797621 0.24149762\n 0.26986602 0.2643833  0.43752205 0.24420168 1.1200356  0.3158142\n 0.41677898 0.46154672 0.21175732 0.26040906 0.5768211  0.23639727\n 0.29408228 0.2922122  0.24582696 0.36854553 0.36342594 0.21453312\n 0.7169856  0.3527516  0.5955185  0.26469812 0.20918845 0.6657997\n 0.2039589  0.20295513 0.30057642 0.32363182 0.21285705 0.31730118\n 0.3827429  0.31297156 0.516189   0.25706172 0.2705757  0.20033583\n 0.2564653  0.26462162 0.29126436 0.27358073 0.28904298 0.5809559\n 0.26559266 1.3223877  0.2538249  0.24904326 0.33755508 0.5008777\n 0.2604347  0.39859238 0.2100001  0.21956715 0.22643365 0.20181595\n 0.22906564 0.44355756 0.24236654 0.20106171 0.40018323 0.18213631\n 0.2900106  0.26590508 0.42573652 0.29897672 0.29127645 0.31941515\n 0.21121328 0.21871562 0.25292623 0.23988356 0.90152234 0.3706233\n 0.7003076  0.40209043 1.1603574  0.20146133 0.32753977 0.32187432\n 0.3297625  0.63703805 0.32659614 0.18248472 0.8609129  0.20123793\n 0.1992785  0.24408911 0.22874199 0.27290085 0.81907195 0.21396314\n 0.3792602  0.17502595 0.18204492 0.22861043 0.20641287 0.21834818\n 0.32141107 0.1941125  0.1821917  0.25291553 0.22249071 0.385548\n 0.21416979 0.4032117  0.19539346 0.6386469  0.19022842 0.20357545\n 0.23109175 0.21136805 0.33072934 0.26622838 0.23320106 0.20665377\n 0.22685108 0.22198546 0.24990465 0.4059801  0.27111375 0.3290464\n 0.20103525 0.39831427 0.19562574 0.17100042 0.2445374  0.2008263\n 0.18497935 0.40547395 0.21667175 0.3920184  0.37270945 0.28249678\n 0.5770952  0.39889634 0.3853342  0.4078009  0.2533394  0.20377336\n 0.23792726 0.18402255 0.32100683 0.26816005 1.0399271  0.25456724\n 0.2020329  0.22112913 0.21188757 0.22176199 0.27347836 0.1791466\n 0.2046829  0.20751303 0.23600148 0.6623853  0.33514947 0.17646219\n 0.5457775  0.90256095 0.34380457 0.30061543 0.22559744 0.4354228\n 0.24596608 0.21170056 0.252093   0.4251333  0.24307145 1.437167\n 0.17466539 0.45709655 0.222017   0.41527295 0.24860795 0.27533472\n 0.26868537 0.20810746 0.2029995  0.2311511  0.18630187 0.23940562\n 0.2389359  0.42651752 0.25157112 0.30184606 0.21408492 0.20194384\n 0.9707434  0.3750561  0.21652928 1.6283686  0.26333392 0.88430667\n 0.3812016  0.26240587 0.21234132 0.22332354 0.21820712 0.3602777\n 0.18798238 0.25407478 0.2880237  0.22021486 0.2657383  0.96476406\n 0.20010795 0.22436959 0.29158205 0.24177931 0.27843776 0.4059049\n 0.34464222 0.40752336 0.21852505 0.25633872 0.28993717 0.2654354\n 0.30498084 0.36769506 0.25322428 0.27783766 0.80571437 0.24417342\n 0.3090259  0.24662906 0.24918558 0.2638896  0.2823456  0.71646565\n 0.24801876 0.3300031  0.18899462 0.24081361 0.2810242  0.20758629\n 0.2912843  0.18024842 0.33457005 1.1183804  0.26018992 0.18997139\n 0.19254175 0.24763468 0.3007814  0.2767656  0.62950474 0.16893679\n 0.25103095 0.8543125  0.17591886 0.32842728 0.44121602 0.41227198\n 0.17321536 0.24929729 0.17890285 0.29419437 0.35587853 0.25593016\n 0.28253946 0.16823748 0.17621908 0.18972033 0.81316036 0.3431088\n 0.2612806  0.568089   1.0465851  0.23117925 0.26929086 0.25913042\n 0.2774961  0.29400268 0.25447813 0.24239045 0.5675999  0.24062984\n 0.20155506 0.21232334 0.20408623 0.3817545  0.22702266 0.42420465\n 0.42117217 0.27806264 0.26519287 0.24271232 0.207246   0.2510607\n 0.20238976 0.26399937 0.17702052 0.48758554 0.20263556 0.29952613\n 0.3936259  0.20113428 0.35760272 0.2741156  0.2229208  0.31620303\n 0.29131404 0.35365468 0.24858008 0.24284567 0.24450721 0.26446187\n 0.2007503  0.5994609  0.2539541  0.40679574 0.25249273 0.24744858\n 0.2075714  0.3221316  0.23378228 0.3833448  0.41330472 0.21925227\n 0.44991517 0.19341324 0.17433375 0.29478875 0.2032145  0.37728062\n 0.20651361 0.29908362 0.26869446 0.8032657  0.26759174 0.18488532\n 0.25667128 0.2400396  0.392618   0.51020515 0.35554522 0.2216849\n 0.21335132 0.25850606 0.27034312 0.20180115 0.33295062 0.22926216\n 0.284183   0.24347755 0.30984342 0.32397297 0.36088887 0.30976704\n 0.29924092 0.34434372 0.1845529  0.23794936 0.18318158 0.25895151\n 0.21136256 0.19434878 0.24711116 0.48770306 0.19913739 0.24033865\n 0.23904088 0.18222558 0.20495766 0.24636312 0.20829086 0.19648167\n 0.33615747 0.21361636 0.31500238 0.19052523 0.34708717 0.32449266\n 0.33792356 0.21843062 0.3479993  0.20610054 0.34966484 0.31396347\n 0.2627381  0.24112591 0.41017756 0.21310526 0.21611007 0.21269543\n 0.37173122 0.31092533 0.18726899 0.22737862 0.41491613 0.35493407\n 0.45546058 0.19905812 0.19898027 0.19379696 0.19990742 0.21955185\n 0.20343165 0.19987005 0.26216048 0.24078557 0.24620515 0.24885277\n 0.250716   0.23807746 0.275308   0.23227452 0.33062792 0.24579038\n 0.27217692 0.20426041 0.27214608 0.18591593 0.17224808 0.26199204\n 0.20764478 0.19699366 0.21046086 0.18843932 0.18815659 0.18602476\n 0.32560423 0.20859846 0.26551628 0.20324928 0.18243289 0.21135373\n 0.17366095 0.26029423 0.21365798 0.24594307 0.22966334 0.27448726\n 0.261692   0.24276604 0.21328697 0.24032399 0.18191767 0.17390864\n 0.17425063 0.20805296 0.22570714 0.35537326 0.24859913 0.18937416\n 0.20481257 0.19859733 0.400645   0.25129408 0.31618872 0.20403124\n 0.1698579  0.25708997 0.17531522 0.29073456 0.23166116 0.17530335\n 0.20493625 0.2587335  0.28623906 0.21610518 0.31692895 0.17230852\n 0.21197061 0.25379145 0.35165092 0.25757208 0.28461924 0.26412013\n 0.19684754 0.20388211 0.28221208 0.22289693 0.31167307 0.30493337\n 0.17638415 0.1762703  0.34422207 0.2825143  0.25675628 0.39579794\n 0.23037791 0.17745881 0.19988367 0.21128744 0.21243021 0.25097388\n 0.20615341 0.1828946  0.206933   0.17886472 0.20465267 0.17785574\n 0.2282151  0.2434906  0.26298234 0.26496822 0.16898099 0.17613992\n 0.17555022 0.1883012  0.17986742 0.17856394 0.19787683 0.18795726\n 0.18191445 0.17612484 0.17224483 0.16986334 0.17955376 0.17033394\n 0.22765018 0.24112819 0.16841544]',
 'update_every': 1,
 'decay': 0.5,
 'offset': 1.0,
 'minimum_probability': 0.0,
 'per_word_topics': False,
 'eval_every': None,
 'dtype': "<class 'numpy.float32'>",
 'random_seed': 42,
 'gensim_version': '4.4.0',
 'training_time_seconds': 6.0153,
 'log_perplexity_train': -6.191917452868002,
 'created_by': 'Notebook_03_Part3C',
 'model_path': '/content/drive/MyDrive/TopicEvalBench/models/Fold_1/K_005/lda.model',
 'theta_train_file': '/content/drive/MyDrive/TopicEvalBench/models/Fold_1/K_005/theta_train.csv',
 'theta_test_file': '/content/drive/MyDrive/TopicEvalBench/models/Fold_1/K_005/theta_test.csv',
 'phi_path': '/content/drive/MyDrive/TopicEvalBench/models/Fold_1/K_005/phi.csv',
 'top_words_path': '/content/drive/MyDrive/TopicEvalBench/models/Fold_1/K_005/top_words.csv',
 'topic_sizes_path': '/content/drive/MyDrive/TopicEvalBench/models/Fold_1/K_005/topic_sizes.csv',
 'dictionary_path': '/content/drive/MyDrive/TopicEvalBench/dictionary/Fold_1/dictionary.dict',
 'train_corpus_path': '/content/drive/MyDrive/TopicEvalBench/models/Fold_1/train_corpus.pkl'}

In [130]:
del lda
del model

gc.collect()

print("Part 3C-2 Completed Successfully.")

Part 3C-2 Completed Successfully.

Part 3C-3

Responsibilities of 3C-3

For each trained LDA model, we will generate and save:

θ (Theta): Document–Topic Distribution (theta_train.csv)
Φ (Phi): Topic–Word Distribution (phi.csv)
Topic Size Statistics (topic_sizes.csv)

No new model is trained in this part.

In [131]:
# ============================================================
# Part 3C-3
# Extract LDA Representations
#
# 1. Theta (Document-Topic Matrix)
# 2. Phi (Topic-Word Matrix)
# 3. Topic Size Statistics
# ============================================================

print_line()
print("Part 3C-3 : Extract LDA Representations")
print_line()

======================================================================
Part 3C-3 : Extract LDA Representations
======================================================================

In [132]:
def load_lda_model(fold, K):
    """
    Load a trained LDA model.
    """

    model_path = (
        MODEL_DIR /
        f"Fold_{fold}" /
        f"K_{K:03d}" /
        "lda.model"
    )

    lda = LdaModel.load(str(model_path))

    return lda

In [133]:
def save_theta_train(
    lda,
    train_corpus,
    train_df,
    model_dir):
    """
    Save document-topic probability matrix.
    """

    theta = []

    for bow in train_corpus:

        topic_vector = lda.get_document_topics(
            bow,
            minimum_probability=0.0
        )

        topic_vector = [
            probability
            for _, probability in topic_vector
        ]

        theta.append(topic_vector)

    theta = np.array(theta)

    columns = [
        f"Topic_{i+1}"
        for i in range(theta.shape[1])
    ]

    theta_df = pd.DataFrame(
        theta,
        columns=columns
    )

    # Keep document information
    theta_df.insert(
        0,
        "LabelID",
        train_df["LabelID"].values
    )

    theta_df.insert(
        0,
        "Label",
        train_df["Label"].values
    )

    theta_df.insert(
        0,
        "DocumentID",
        train_df["DocumentID"].values
    )

    output_file = model_dir / "theta_train.csv"

    theta_df.to_csv(
        output_file,
        index=False
    )

    return theta_df

In [134]:
def save_theta_test(
    lda,
    test_corpus,
    test_df,
    model_dir):
    """
    Save document-topic probability matrix for the testing corpus.
    """

    theta = []

    for bow in test_corpus:

        topic_vector = lda.get_document_topics(
            bow,
            minimum_probability=0.0
        )

        topic_vector = [
            probability
            for _, probability in topic_vector
        ]

        theta.append(topic_vector)

    theta = np.array(theta)

    columns = [
        f"Topic_{i+1}"
        for i in range(theta.shape[1])
    ]

    theta_df = pd.DataFrame(
        theta,
        columns=columns
    )

    # Keep document information
    theta_df.insert(
        0,
        "LabelID",
        test_df["LabelID"].values
    )

    theta_df.insert(
        0,
        "Label",
        test_df["Label"].values
    )

    theta_df.insert(
        0,
        "DocumentID",
        test_df["DocumentID"].values
    )

    output_file = model_dir / "theta_test.csv"

    theta_df.to_csv(
        output_file,
        index=False
    )

    return theta_df

In [135]:
def save_phi(
    lda,
    dictionary,
    model_dir):
    """
    Save topic-word probability matrix.
    """

    phi = lda.get_topics()

    vocabulary = [
        dictionary[i]
        for i in range(len(dictionary))
    ]

    phi_df = pd.DataFrame(
        phi,
        columns=vocabulary
    )

    phi_df.index = [
        f"Topic_{i+1}"
        for i in range(phi.shape[0])
    ]

    output_file = model_dir / "phi.csv"

    phi_df.to_csv(output_file)

    return phi_df

In [136]:
def save_top_words(
    lda,
    model_dir,
    topn=20):
    """
    Save the top-N words for each topic.

    Parameters
    ----------
    lda : gensim.models.LdaModel
        Trained LDA model.

    model_dir : pathlib.Path
        Output directory.

    topn : int
        Number of top words per topic.
    """

    rows = []

    for topic_id in range(lda.num_topics):

        words = lda.show_topic(
            topic_id,
            topn=topn
        )

        for rank, (word, prob) in enumerate(words, start=1):

            # Get the dictionary ID of the word
            word_id = lda.id2word.token2id[word]

            rows.append({

                "TopicID": topic_id,

                "Topic": f"Topic_{topic_id+1}",

                "Rank": rank,

                "WordID": word_id,

                "Word": word,

                "Probability": prob

            })

    top_words_df = pd.DataFrame(rows)

    output_file = model_dir / "top_words.csv"

    top_words_df.to_csv(
        output_file,
        index=False
    )

    return top_words_df

In [137]:
def save_topic_sizes(
    theta_df,
    model_dir):
    """
    Compute dominant topic counts.
    """

    topic_columns = [
        c for c in theta_df.columns
        if c.startswith("Topic_")
    ]

    dominant_topics = (
        theta_df[topic_columns]
        .idxmax(axis=1)
    )

    topic_sizes = (
        dominant_topics
        .value_counts()
        .sort_index()
    )

    topic_size_df = pd.DataFrame({

        "Topic": topic_sizes.index,

        "Documents": topic_sizes.values

    })

    output_file = (
        model_dir /
        "topic_sizes.csv"
    )

    topic_size_df.to_csv(
        output_file,
        index=False
    )

    return topic_size_df

In [138]:
def extract_lda_outputs(
    fold,
    K):
    """
    Extract theta, phi and topic sizes.
    """

    model_dir = create_model_directory(
        fold,
        K
    )

    dictionary = load_dictionary(fold)

    train_corpus, test_corpus = load_corpus(fold)

    train_df = load_training_dataframe(fold)
    test_df = load_testing_dataframe(fold)

    lda = load_lda_model(
        fold,
        K
    )

    theta_df = save_theta_train(
        lda,
        train_corpus,
        train_df,
        model_dir
    )

    # Save document-topic distributions for testing documents
    theta_test_df = save_theta_test(
        lda=lda,
        test_corpus=test_corpus,
        test_df=test_df,
        model_dir=model_dir
)

    print("="*60)
    print("Fold:", fold)
    print("K:", K)

    print("Dictionary Size :", len(dictionary))
    print("Max Dictionary ID:", max(dictionary.keys()))

    print("LDA Topic Matrix :", lda.get_topics().shape)

    print("="*60)

    phi_df = save_phi(
        lda,
        dictionary,
        model_dir
    )

    top_words_df = save_top_words(
        lda,
        model_dir,
        topn=20
    )

    topic_size_df = save_topic_sizes(
        theta_df,
        model_dir
    )

    print("Theta Shape      :", theta_df.shape)

    print("Phi Shape        :", phi_df.shape)

    print("Top Words Rows   :", len(top_words_df))

    print("Topic Statistics :")

    print(topic_size_df.head())

    del lda

    gc.collect()

In [139]:
extract_lda_outputs(
    fold=1,
    K=5)

============================================================
Fold: 1
K: 5
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (5, 891)
============================================================
Theta Shape      : (240, 8)
Phi Shape        : (5, 891)
Top Words Rows   : 100
Topic Statistics :
     Topic  Documents
0  Topic_1         50
1  Topic_2         34
2  Topic_3         71
3  Topic_4         54
4  Topic_5         31

Part 3C-4
Purpose

For each fold:

Train all LDA models;
Save metadata;
Save theta;
Save phi;
Save top words;
Save topic sizes;
Record training summary;
Continue if one topic fails

In [140]:
def process_fold(fold):
    """
    Train all LDA models for one fold.

    Parameters
    ----------
    fold : int
        Fold number (1-5)

    Returns
    -------
    summary_df : pandas.DataFrame
    """

    print_line()
    print(f"Processing Fold {fold}")
    print_line()

    fold_summary = []

    for K in tqdm(
        range(MIN_TOPICS, MAX_TOPICS + 1),
        desc=f"Fold {fold}"
    ):

        model_dir = (
            MODEL_DIR /
            f"Fold_{fold}" /
            f"K_{K:03d}"
        )

        # --------------------------------------------------
        # Required output files
        # --------------------------------------------------

        required_files = [

            model_dir / "lda.model",

            model_dir / "metadata.json",

            model_dir / "theta_train.csv",

            model_dir / "theta_test.csv",

            model_dir / "phi.csv",

            model_dir / "topic_sizes.csv",

            model_dir / "top_words.csv"

        ]

        # --------------------------------------------------
        # Resume capability
        # --------------------------------------------------

        if all(f.exists() for f in required_files):

            print(f"Fold {fold} | K={K:03d} already completed. Skipping.")

            try:

                with open(
                    model_dir / "metadata.json",
                    "r",
                    encoding="utf-8"
                ) as f:

                    metadata = json.load(f)

                fold_summary.append({

                    "Fold": fold,

                    "Topics": K,

                    "DictionarySize":
                        metadata["dictionary_size"],

                    "Documents":
                        metadata["documents"],

                    "TrainingTime":
                        metadata["training_time_seconds"],

                    "LogPerplexityTrain":
                        metadata["log_perplexity_train"],

                    "Status": "Already Exists"

                })

            except Exception:

                fold_summary.append({

                    "Fold": fold,

                    "Topics": K,

                    "DictionarySize": np.nan,

                    "Documents": np.nan,

                    "TrainingTime": np.nan,

                    "LogPerplexityTrain": np.nan,

                    "Status": "Already Exists"

                })

            continue

        # --------------------------------------------------
        # Train Model
        # --------------------------------------------------

        try:

            lda = train_single_lda(
                fold,
                K
            )

            extract_lda_outputs(
                fold,
                K
            )

            with open(
                model_dir / "metadata.json",
                "r",
                encoding="utf-8"
            ) as f:

                metadata = json.load(f)

            fold_summary.append({

                "Fold": fold,

                "Topics": K,

                "DictionarySize":
                    metadata["dictionary_size"],

                "Documents":
                    metadata["documents"],

                "TrainingTime":
                    metadata["training_time_seconds"],

                "LogPerplexityTrain":
                    metadata["log_perplexity_train"],

                "Status": "Success"

            })

            del lda

            gc.collect()

        except Exception as e:

            print(f"\nError while processing Fold={fold}, K={K}")

            print(e)

            fold_summary.append({

                "Fold": fold,

                "Topics": K,

                "DictionarySize": np.nan,

                "Documents": np.nan,

                "TrainingTime": np.nan,

                "LogPerplexityTrain": np.nan,

                "Status": str(e)

            })

            gc.collect()

            continue

    summary_df = pd.DataFrame(fold_summary)

    summary_file = (
        MODEL_DIR /
        f"Fold_{fold}" /
        "training_summary.csv"
    )

    summary_df.to_csv(
        summary_file,
        index=False
    )

    print("\nFold Summary")
    print(summary_df.head())

    return summary_df

In [141]:
summary_fold1 = process_fold(
    fold=1
)

======================================================================
Processing Fold 1
======================================================================

Fold 1:   0%|          | 0/99 [00:00<?, ?it/s]

Training Fold 1  K=2
Finished in 3.31 seconds
============================================================
Fold: 1
K: 2
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (2, 891)
============================================================
Theta Shape      : (240, 5)
Phi Shape        : (2, 891)
Top Words Rows   : 40
Topic Statistics :
     Topic  Documents
0  Topic_1        124
1  Topic_2        116
Training Fold 1  K=3
Finished in 4.63 seconds
============================================================
Fold: 1
K: 3
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (3, 891)
============================================================
Theta Shape      : (240, 6)
Phi Shape        : (3, 891)
Top Words Rows   : 60
Topic Statistics :
     Topic  Documents
0  Topic_1         97
1  Topic_2         70
2  Topic_3         73
Training Fold 1  K=4
Finished in 2.79 seconds
============================================================
Fold: 1
K: 4
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (4, 891)
============================================================
Theta Shape      : (240, 7)
Phi Shape        : (4, 891)
Top Words Rows   : 80
Topic Statistics :
     Topic  Documents
0  Topic_1         67
1  Topic_2         44
2  Topic_3         61
3  Topic_4         68
Fold 1 | K=005 already completed. Skipping.
Training Fold 1  K=6
Finished in 2.58 seconds
============================================================
Fold: 1
K: 6
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (6, 891)
============================================================
Theta Shape      : (240, 9)
Phi Shape        : (6, 891)
Top Words Rows   : 120
Topic Statistics :
     Topic  Documents
0  Topic_1         62
1  Topic_2         15
2  Topic_3         65
3  Topic_4         51
4  Topic_5         19
Training Fold 1  K=7
Finished in 3.34 seconds
============================================================
Fold: 1
K: 7
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (7, 891)
============================================================
Theta Shape      : (240, 10)
Phi Shape        : (7, 891)
Top Words Rows   : 140
Topic Statistics :
     Topic  Documents
0  Topic_1         62
1  Topic_2         15
2  Topic_3         55
3  Topic_4         37
4  Topic_5         26
Training Fold 1  K=8
Finished in 3.51 seconds
============================================================
Fold: 1
K: 8
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (8, 891)
============================================================
Theta Shape      : (240, 11)
Phi Shape        : (8, 891)
Top Words Rows   : 160
Topic Statistics :
     Topic  Documents
0  Topic_1         51
1  Topic_2         16
2  Topic_3         48
3  Topic_4         44
4  Topic_5         20
Training Fold 1  K=9
Finished in 2.48 seconds
============================================================
Fold: 1
K: 9
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (9, 891)
============================================================
Theta Shape      : (240, 12)
Phi Shape        : (9, 891)
Top Words Rows   : 180
Topic Statistics :
     Topic  Documents
0  Topic_1         50
1  Topic_2         28
2  Topic_3         52
3  Topic_4         23
4  Topic_5         16
Training Fold 1  K=10
Finished in 2.47 seconds
============================================================
Fold: 1
K: 10
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (10, 891)
============================================================
Theta Shape      : (240, 13)
Phi Shape        : (10, 891)
Top Words Rows   : 200
Topic Statistics :
      Topic  Documents
0   Topic_1         41
1  Topic_10         35
2   Topic_2          9
3   Topic_3         47
4   Topic_4         22
Training Fold 1  K=11
Finished in 3.44 seconds
============================================================
Fold: 1
K: 11
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (11, 891)
============================================================
Theta Shape      : (240, 14)
Phi Shape        : (11, 891)
Top Words Rows   : 220
Topic Statistics :
      Topic  Documents
0   Topic_1         27
1  Topic_10         22
2  Topic_11         36
3   Topic_2         10
4   Topic_3         42
Training Fold 1  K=12
Finished in 3.49 seconds
============================================================
Fold: 1
K: 12
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (12, 891)
============================================================
Theta Shape      : (240, 15)
Phi Shape        : (12, 891)
Top Words Rows   : 240
Topic Statistics :
      Topic  Documents
0   Topic_1         29
1  Topic_10         21
2  Topic_11         31
3  Topic_12         18
4   Topic_2         13
Training Fold 1  K=13
Finished in 2.65 seconds
============================================================
Fold: 1
K: 13
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (13, 891)
============================================================
Theta Shape      : (240, 16)
Phi Shape        : (13, 891)
Top Words Rows   : 260
Topic Statistics :
      Topic  Documents
0   Topic_1         24
1  Topic_10         20
2  Topic_11         22
3  Topic_12         34
4  Topic_13          9
Training Fold 1  K=14
Finished in 2.73 seconds
============================================================
Fold: 1
K: 14
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (14, 891)
============================================================
Theta Shape      : (240, 17)
Phi Shape        : (14, 891)
Top Words Rows   : 280
Topic Statistics :
      Topic  Documents
0   Topic_1         22
1  Topic_10         15
2  Topic_11         34
3  Topic_12         26
4  Topic_13         15
Training Fold 1  K=15
Finished in 4.22 seconds
============================================================
Fold: 1
K: 15
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (15, 891)
============================================================
Theta Shape      : (240, 18)
Phi Shape        : (15, 891)
Top Words Rows   : 300
Topic Statistics :
      Topic  Documents
0   Topic_1         30
1  Topic_10         25
2  Topic_11         18
3  Topic_12         19
4  Topic_13          9
Training Fold 1  K=16
Finished in 2.70 seconds
============================================================
Fold: 1
K: 16
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (16, 891)
============================================================
Theta Shape      : (240, 19)
Phi Shape        : (16, 891)
Top Words Rows   : 320
Topic Statistics :
      Topic  Documents
0   Topic_1         24
1  Topic_10         15
2  Topic_11         19
3  Topic_12         20
4  Topic_13         19
Training Fold 1  K=17
Finished in 2.59 seconds
============================================================
Fold: 1
K: 17
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (17, 891)
============================================================
Theta Shape      : (240, 20)
Phi Shape        : (17, 891)
Top Words Rows   : 340
Topic Statistics :
      Topic  Documents
0   Topic_1         23
1  Topic_10         17
2  Topic_11         14
3  Topic_12          8
4  Topic_13         10
Training Fold 1  K=18
Finished in 2.58 seconds
============================================================
Fold: 1
K: 18
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (18, 891)
============================================================
Theta Shape      : (240, 21)
Phi Shape        : (18, 891)
Top Words Rows   : 360
Topic Statistics :
      Topic  Documents
0   Topic_1         28
1  Topic_10          7
2  Topic_11         17
3  Topic_12         17
4  Topic_13          5
Training Fold 1  K=19
Finished in 4.08 seconds
============================================================
Fold: 1
K: 19
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (19, 891)
============================================================
Theta Shape      : (240, 22)
Phi Shape        : (19, 891)
Top Words Rows   : 380
Topic Statistics :
      Topic  Documents
0   Topic_1         20
1  Topic_10         18
2  Topic_11         10
3  Topic_12         10
4  Topic_13         20
Training Fold 1  K=20
Finished in 2.57 seconds
============================================================
Fold: 1
K: 20
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (20, 891)
============================================================
Theta Shape      : (240, 23)
Phi Shape        : (20, 891)
Top Words Rows   : 400
Topic Statistics :
      Topic  Documents
0   Topic_1         18
1  Topic_10         17
2  Topic_11         13
3  Topic_12         13
4  Topic_13          9
Training Fold 1  K=21
Finished in 2.82 seconds
============================================================
Fold: 1
K: 21
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (21, 891)
============================================================
Theta Shape      : (240, 24)
Phi Shape        : (21, 891)
Top Words Rows   : 420
Topic Statistics :
      Topic  Documents
0   Topic_1         20
1  Topic_10         18
2  Topic_11         14
3  Topic_12         14
4  Topic_13          9
Training Fold 1  K=22
Finished in 3.50 seconds
============================================================
Fold: 1
K: 22
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (22, 891)
============================================================
Theta Shape      : (240, 25)
Phi Shape        : (22, 891)
Top Words Rows   : 440
Topic Statistics :
      Topic  Documents
0   Topic_1         10
1  Topic_10         19
2  Topic_11         10
3  Topic_12         14
4  Topic_13          7
Training Fold 1  K=23
Finished in 3.57 seconds
============================================================
Fold: 1
K: 23
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (23, 891)
============================================================
Theta Shape      : (240, 26)
Phi Shape        : (23, 891)
Top Words Rows   : 460
Topic Statistics :
      Topic  Documents
0   Topic_1         12
1  Topic_10         17
2  Topic_11         11
3  Topic_12         12
4  Topic_13          9
Training Fold 1  K=24
Finished in 2.50 seconds
============================================================
Fold: 1
K: 24
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (24, 891)
============================================================
Theta Shape      : (240, 27)
Phi Shape        : (24, 891)
Top Words Rows   : 480
Topic Statistics :
      Topic  Documents
0   Topic_1         12
1  Topic_10          8
2  Topic_11         17
3  Topic_12         12
4  Topic_13         12
Training Fold 1  K=25
Finished in 2.52 seconds
============================================================
Fold: 1
K: 25
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (25, 891)
============================================================
Theta Shape      : (240, 28)
Phi Shape        : (25, 891)
Top Words Rows   : 500
Topic Statistics :
      Topic  Documents
0   Topic_1          7
1  Topic_10         10
2  Topic_11         13
3  Topic_12         15
4  Topic_13         12
Training Fold 1  K=26
Finished in 3.25 seconds
============================================================
Fold: 1
K: 26
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (26, 891)
============================================================
Theta Shape      : (240, 29)
Phi Shape        : (26, 891)
Top Words Rows   : 520
Topic Statistics :
      Topic  Documents
0   Topic_1          9
1  Topic_10         21
2  Topic_11         12
3  Topic_12         10
4  Topic_13         10
Training Fold 1  K=27
Finished in 4.02 seconds
============================================================
Fold: 1
K: 27
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (27, 891)
============================================================
Theta Shape      : (240, 30)
Phi Shape        : (27, 891)
Top Words Rows   : 540
Topic Statistics :
      Topic  Documents
0   Topic_1          9
1  Topic_10         10
2  Topic_11          8
3  Topic_12         11
4  Topic_13          7
Training Fold 1  K=28
Finished in 2.42 seconds
============================================================
Fold: 1
K: 28
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (28, 891)
============================================================
Theta Shape      : (240, 31)
Phi Shape        : (28, 891)
Top Words Rows   : 560
Topic Statistics :
      Topic  Documents
0   Topic_1         18
1  Topic_10         14
2  Topic_11          8
3  Topic_12          8
4  Topic_13          7
Training Fold 1  K=29
Finished in 2.55 seconds
============================================================
Fold: 1
K: 29
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (29, 891)
============================================================
Theta Shape      : (240, 32)
Phi Shape        : (29, 891)
Top Words Rows   : 580
Topic Statistics :
      Topic  Documents
0   Topic_1         11
1  Topic_10         15
2  Topic_11         11
3  Topic_12          9
4  Topic_13         10
Training Fold 1  K=30
Finished in 3.90 seconds
============================================================
Fold: 1
K: 30
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (30, 891)
============================================================
Theta Shape      : (240, 33)
Phi Shape        : (30, 891)
Top Words Rows   : 600
Topic Statistics :
      Topic  Documents
0   Topic_1         14
1  Topic_10         10
2  Topic_11          3
3  Topic_12          9
4  Topic_13          8
Training Fold 1  K=31
Finished in 2.86 seconds
============================================================
Fold: 1
K: 31
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (31, 891)
============================================================
Theta Shape      : (240, 34)
Phi Shape        : (31, 891)
Top Words Rows   : 620
Topic Statistics :
      Topic  Documents
0   Topic_1         13
1  Topic_10          9
2  Topic_11          4
3  Topic_12         18
4  Topic_13          6
Training Fold 1  K=32
Finished in 2.46 seconds
============================================================
Fold: 1
K: 32
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (32, 891)
============================================================
Theta Shape      : (240, 35)
Phi Shape        : (32, 891)
Top Words Rows   : 640
Topic Statistics :
      Topic  Documents
0   Topic_1         10
1  Topic_10          5
2  Topic_11          7
3  Topic_12          6
4  Topic_13         10
Training Fold 1  K=33
Finished in 2.57 seconds
============================================================
Fold: 1
K: 33
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (33, 891)
============================================================
Theta Shape      : (240, 36)
Phi Shape        : (33, 891)
Top Words Rows   : 660
Topic Statistics :
      Topic  Documents
0   Topic_1          9
1  Topic_10          8
2  Topic_11          6
3  Topic_12         16
4  Topic_13          7
Training Fold 1  K=34
Finished in 4.22 seconds
============================================================
Fold: 1
K: 34
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (34, 891)
============================================================
Theta Shape      : (240, 37)
Phi Shape        : (34, 891)
Top Words Rows   : 680
Topic Statistics :
      Topic  Documents
0   Topic_1         11
1  Topic_10         12
2  Topic_11          3
3  Topic_12         13
4  Topic_13          6
Training Fold 1  K=35
Finished in 2.61 seconds
============================================================
Fold: 1
K: 35
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (35, 891)
============================================================
Theta Shape      : (240, 38)
Phi Shape        : (35, 891)
Top Words Rows   : 700
Topic Statistics :
      Topic  Documents
0   Topic_1         14
1  Topic_10          3
2  Topic_11          6
3  Topic_12         14
4  Topic_13         11
Training Fold 1  K=36
Finished in 2.85 seconds
============================================================
Fold: 1
K: 36
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (36, 891)
============================================================
Theta Shape      : (240, 39)
Phi Shape        : (36, 891)
Top Words Rows   : 720
Topic Statistics :
      Topic  Documents
0   Topic_1          7
1  Topic_10          4
2  Topic_11          7
3  Topic_12         16
4  Topic_13          7
Training Fold 1  K=37
Finished in 2.50 seconds
============================================================
Fold: 1
K: 37
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (37, 891)
============================================================
Theta Shape      : (240, 40)
Phi Shape        : (37, 891)
Top Words Rows   : 740
Topic Statistics :
      Topic  Documents
0   Topic_1         10
1  Topic_10          8
2  Topic_11         15
3  Topic_12          7
4  Topic_13          8
Training Fold 1  K=38
Finished in 4.74 seconds
============================================================
Fold: 1
K: 38
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (38, 891)
============================================================
Theta Shape      : (240, 41)
Phi Shape        : (38, 891)
Top Words Rows   : 760
Topic Statistics :
      Topic  Documents
0   Topic_1          6
1  Topic_10          9
2  Topic_11          5
3  Topic_12          9
4  Topic_13          8
Training Fold 1  K=39
Finished in 3.80 seconds
============================================================
Fold: 1
K: 39
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (39, 891)
============================================================
Theta Shape      : (240, 42)
Phi Shape        : (39, 891)
Top Words Rows   : 780
Topic Statistics :
      Topic  Documents
0   Topic_1          9
1  Topic_10          8
2  Topic_11          5
3  Topic_12          9
4  Topic_13          6
Training Fold 1  K=40
Finished in 3.87 seconds
============================================================
Fold: 1
K: 40
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (40, 891)
============================================================
Theta Shape      : (240, 43)
Phi Shape        : (40, 891)
Top Words Rows   : 800
Topic Statistics :
      Topic  Documents
0   Topic_1         10
1  Topic_10          4
2  Topic_11          4
3  Topic_12          6
4  Topic_13          3
Training Fold 1  K=41
Finished in 5.14 seconds
============================================================
Fold: 1
K: 41
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (41, 891)
============================================================
Theta Shape      : (240, 44)
Phi Shape        : (41, 891)
Top Words Rows   : 820
Topic Statistics :
      Topic  Documents
0   Topic_1          7
1  Topic_10          5
2  Topic_11          4
3  Topic_12          8
4  Topic_13          8
Training Fold 1  K=42
Finished in 4.40 seconds
============================================================
Fold: 1
K: 42
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (42, 891)
============================================================
Theta Shape      : (240, 45)
Phi Shape        : (42, 891)
Top Words Rows   : 840
Topic Statistics :
      Topic  Documents
0   Topic_1          4
1  Topic_10          3
2  Topic_11          3
3  Topic_12         12
4  Topic_13          4
Training Fold 1  K=43
Finished in 5.60 seconds
============================================================
Fold: 1
K: 43
Dictionary Size : 891
Max Dictionary ID: 890
LDA Topic Matrix : (43, 891)
============================================================
Theta Shape      : (240, 46)
Phi Shape        : (43, 891)
Top Words Rows   : 860
Topic Statistics :

In [142]:
summary_fold1.head()

,Fold,Topics,DictionarySize,Documents,TrainingTime,LogPerplexityTrain,Status
0,1,2,891,240,3.3123,-6.298535,Success
1,1,3,891,240,4.6282,-6.214306,Success
2,1,4,891,240,2.7942,-6.193754,Success
3,1,5,891,240,6.0153,-6.191917,Already Exists
4,1,6,891,240,2.5762,-6.224693,Success

In [143]:
print_line()

print("Models Trained :",
      len(summary_fold1))

print()

print(summary_fold1["TrainingTime"].describe())

print()

print("Failures :")

print(
    (summary_fold1["Status"] != "Success").sum()
)

print_line()

======================================================================
Models Trained : 99

count    99.000000
mean      5.285724
std       3.243076
min       2.415700
25%       3.052850
50%       3.947000
75%       6.089700
max      12.816600
Name: TrainingTime, dtype: float64

Failures :
1
======================================================================

In [144]:
gc.collect()

print("Part 3C-4 Completed Successfully.")

Part 3C-4 Completed Successfully.

Part 3C-5

Responsibilities,
Run all 5 folds,
Merge all fold summaries,
Validate outputs,
Save training_summary_all_folds.csv,
Produce an experiment report

In [145]:
print_line()
print("Starting LDA Training for All Folds")
print_line()

all_fold_summaries = []

for fold in range(1, NUM_FOLDS + 1):

    summary_df = process_fold(fold)

    all_fold_summaries.append(summary_df)

print()

print("All folds completed.")

======================================================================
Starting LDA Training for All Folds
======================================================================
======================================================================
Processing Fold 1
======================================================================

Fold 1:   0%|          | 0/99 [00:00<?, ?it/s]

Fold 1 | K=002 already completed. Skipping.
Fold 1 | K=003 already completed. Skipping.
Fold 1 | K=004 already completed. Skipping.
Fold 1 | K=005 already completed. Skipping.
Fold 1 | K=006 already completed. Skipping.
Fold 1 | K=007 already completed. Skipping.
Fold 1 | K=008 already completed. Skipping.
Fold 1 | K=009 already completed. Skipping.
Fold 1 | K=010 already completed. Skipping.
Fold 1 | K=011 already completed. Skipping.
Fold 1 | K=012 already completed. Skipping.
Fold 1 | K=013 already completed. Skipping.
Fold 1 | K=014 already completed. Skipping.
Fold 1 | K=015 already completed. Skipping.
Fold 1 | K=016 already completed. Skipping.
Fold 1 | K=017 already completed. Skipping.
Fold 1 | K=018 already completed. Skipping.
Fold 1 | K=019 already completed. Skipping.
Fold 1 | K=020 already completed. Skipping.
Fold 1 | K=021 already completed. Skipping.
Fold 1 | K=022 already completed. Skipping.
Fold 1 | K=023 already completed. Skipping.
Fold 1 | K=024 already completed. Skipping.
Fold 1 | K=025 already completed. Skipping.
Fold 1 | K=026 already completed. Skipping.
Fold 1 | K=027 already completed. Skipping.
Fold 1 | K=028 already completed. Skipping.
Fold 1 | K=029 already completed. Skipping.
Fold 1 | K=030 already completed. Skipping.
Fold 1 | K=031 already completed. Skipping.
Fold 1 | K=032 already completed. Skipping.
Fold 1 | K=033 already completed. Skipping.
Fold 1 | K=034 already completed. Skipping.
Fold 1 | K=035 already completed. Skipping.
Fold 1 | K=036 already completed. Skipping.
Fold 1 | K=037 already completed. Skipping.
Fold 1 | K=038 already completed. Skipping.
Fold 1 | K=039 already completed. Skipping.
Fold 1 | K=040 already completed. Skipping.
Fold 1 | K=041 already completed. Skipping.
Fold 1 | K=042 already completed. Skipping.
Fold 1 | K=043 already completed. Skipping.
Fold 1 | K=044 already completed. Skipping.
Fold 1 | K=045 already completed. Skipping.
Fold 1 | K=046 already completed. Skipping.
Fold 1 | K=047 already completed. Skipping.
Fold 1 | K=048 already completed. Skipping.
Fold 1 | K=049 already completed. Skipping.
Fold 1 | K=050 already completed. Skipping.
Fold 1 | K=051 already completed. Skipping.
Fold 1 | K=052 already completed. Skipping.
Fold 1 | K=053 already completed. Skipping.
Fold 1 | K=054 already completed. Skipping.
Fold 1 | K=055 already completed. Skipping.
Fold 1 | K=056 already completed. Skipping.
Fold 1 | K=057 already completed. Skipping.
Fold 1 | K=058 already completed. Skipping.
Fold 1 | K=059 already completed. Skipping.
Fold 1 | K=060 already completed. Skipping.
Fold 1 | K=061 already completed. Skipping.
Fold 1 | K=062 already completed. Skipping.
Fold 1 | K=063 already completed. Skipping.
Fold 1 | K=064 already completed. Skipping.
Fold 1 | K=065 already completed. Skipping.
Fold 1 | K=066 already completed. Skipping.
Fold 1 | K=067 already completed. Skipping.
Fold 1 | K=068 already completed. Skipping.
Fold 1 | K=069 already completed. Skipping.
Fold 1 | K=070 already completed. Skipping.
Fold 1 | K=071 already completed. Skipping.
Fold 1 | K=072 already completed. Skipping.
Fold 1 | K=073 already completed. Skipping.
Fold 1 | K=074 already completed. Skipping.
Fold 1 | K=075 already completed. Skipping.
Fold 1 | K=076 already completed. Skipping.
Fold 1 | K=077 already completed. Skipping.
Fold 1 | K=078 already completed. Skipping.
Fold 1 | K=079 already completed. Skipping.
Fold 1 | K=080 already completed. Skipping.
Fold 1 | K=081 already completed. Skipping.
Fold 1 | K=082 already completed. Skipping.
Fold 1 | K=083 already completed. Skipping.
Fold 1 | K=084 already completed. Skipping.
Fold 1 | K=085 already completed. Skipping.
Fold 1 | K=086 already completed. Skipping.
Fold 1 | K=087 already completed. Skipping.
Fold 1 | K=088 already completed. Skipping.
Fold 1 | K=089 already completed. Skipping.
Fold 1 | K=090 already completed. Skipping.
Fold 1 | K=091 already completed. Skipping.
Fold 1 | K=092 already completed. Skipping.
Fold 1 | K=093 already completed. Skipping.
Fold 1 | K=094 already completed. Skipping.
Fold 1 | K=095 already completed. Skipping.
Fold 1 | K=096 already completed. Skipping.
Fold 1 | K=097 already completed. Skipping.
Fold 1 | K=098 already completed. Skipping.
Fold 1 | K=099 already completed. Skipping.
Fold 1 | K=100 already completed. Skipping.

Fold Summary
   Fold  Topics  DictionarySize  Documents  TrainingTime  LogPerplexityTrain  \
0     1       2             891        240        3.3123           -6.298535
1     1       3             891        240        4.6282           -6.214306
2     1       4             891        240        2.7942           -6.193754
3     1       5             891        240        6.0153           -6.191917
4     1       6             891        240        2.5762           -6.224693

           Status
0  Already Exists
1  Already Exists
2  Already Exists
3  Already Exists
4  Already Exists
======================================================================
Processing Fold 2
======================================================================

Fold 2:   0%|          | 0/99 [00:00<?, ?it/s]

Training Fold 2  K=2
Finished in 4.80 seconds
============================================================
Fold: 2
K: 2
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (2, 860)
============================================================
Theta Shape      : (240, 5)
Phi Shape        : (2, 860)
Top Words Rows   : 40
Topic Statistics :
     Topic  Documents
0  Topic_1        120
1  Topic_2        120
Training Fold 2  K=3
Finished in 2.59 seconds
============================================================
Fold: 2
K: 3
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (3, 860)
============================================================
Theta Shape      : (240, 6)
Phi Shape        : (3, 860)
Top Words Rows   : 60
Topic Statistics :
     Topic  Documents
0  Topic_1         77
1  Topic_2         95
2  Topic_3         68
Training Fold 2  K=4
Finished in 2.34 seconds
============================================================
Fold: 2
K: 4
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (4, 860)
============================================================
Theta Shape      : (240, 7)
Phi Shape        : (4, 860)
Top Words Rows   : 80
Topic Statistics :
     Topic  Documents
0  Topic_1         50
1  Topic_2         78
2  Topic_3         67
3  Topic_4         45
Training Fold 2  K=5
Finished in 2.50 seconds
============================================================
Fold: 2
K: 5
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (5, 860)
============================================================
Theta Shape      : (240, 8)
Phi Shape        : (5, 860)
Top Words Rows   : 100
Topic Statistics :
     Topic  Documents
0  Topic_1         37
1  Topic_2         76
2  Topic_3         63
3  Topic_4         36
4  Topic_5         28
Training Fold 2  K=6
Finished in 3.85 seconds
============================================================
Fold: 2
K: 6
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (6, 860)
============================================================
Theta Shape      : (240, 9)
Phi Shape        : (6, 860)
Top Words Rows   : 120
Topic Statistics :
     Topic  Documents
0  Topic_1         37
1  Topic_2         75
2  Topic_3         48
3  Topic_4         11
4  Topic_5         24
Training Fold 2  K=7
Finished in 2.40 seconds
============================================================
Fold: 2
K: 7
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (7, 860)
============================================================
Theta Shape      : (240, 10)
Phi Shape        : (7, 860)
Top Words Rows   : 140
Topic Statistics :
     Topic  Documents
0  Topic_1         26
1  Topic_2         74
2  Topic_3         45
3  Topic_4          8
4  Topic_5         23
Training Fold 2  K=8
Finished in 2.24 seconds
============================================================
Fold: 2
K: 8
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (8, 860)
============================================================
Theta Shape      : (240, 11)
Phi Shape        : (8, 860)
Top Words Rows   : 160
Topic Statistics :
     Topic  Documents
0  Topic_1          8
1  Topic_2         61
2  Topic_3         19
3  Topic_4          5
4  Topic_5         24
Training Fold 2  K=9
Finished in 2.30 seconds
============================================================
Fold: 2
K: 9
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (9, 860)
============================================================
Theta Shape      : (240, 12)
Phi Shape        : (9, 860)
Top Words Rows   : 180
Topic Statistics :
     Topic  Documents
0  Topic_1          5
1  Topic_2         58
2  Topic_3         17
3  Topic_4          7
4  Topic_5         20
Training Fold 2  K=10
Finished in 3.30 seconds
============================================================
Fold: 2
K: 10
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (10, 860)
============================================================
Theta Shape      : (240, 13)
Phi Shape        : (10, 860)
Top Words Rows   : 200
Topic Statistics :
      Topic  Documents
0   Topic_1         14
1  Topic_10         13
2   Topic_2         55
3   Topic_3         11
4   Topic_4          6
Training Fold 2  K=11
Finished in 3.31 seconds
============================================================
Fold: 2
K: 11
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (11, 860)
============================================================
Theta Shape      : (240, 14)
Phi Shape        : (11, 860)
Top Words Rows   : 220
Topic Statistics :
      Topic  Documents
0   Topic_1          4
1  Topic_10         10
2  Topic_11         16
3   Topic_2         59
4   Topic_3         13
Training Fold 2  K=12
Finished in 2.27 seconds
============================================================
Fold: 2
K: 12
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (12, 860)
============================================================
Theta Shape      : (240, 15)
Phi Shape        : (12, 860)
Top Words Rows   : 240
Topic Statistics :
      Topic  Documents
0   Topic_1          6
1  Topic_10         12
2  Topic_11          4
3  Topic_12         22
4   Topic_2         50
Training Fold 2  K=13
Finished in 2.52 seconds
============================================================
Fold: 2
K: 13
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (13, 860)
============================================================
Theta Shape      : (240, 16)
Phi Shape        : (13, 860)
Top Words Rows   : 260
Topic Statistics :
      Topic  Documents
0   Topic_1          6
1  Topic_10         10
2  Topic_11          6
3  Topic_12         25
4  Topic_13         17
Training Fold 2  K=14
Finished in 3.37 seconds
============================================================
Fold: 2
K: 14
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (14, 860)
============================================================
Theta Shape      : (240, 17)
Phi Shape        : (14, 860)
Top Words Rows   : 280
Topic Statistics :
      Topic  Documents
0   Topic_1          7
1  Topic_10         14
2  Topic_11          3
3  Topic_12         10
4  Topic_13         19
Training Fold 2  K=15
Finished in 3.11 seconds
============================================================
Fold: 2
K: 15
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (15, 860)
============================================================
Theta Shape      : (240, 18)
Phi Shape        : (15, 860)
Top Words Rows   : 300
Topic Statistics :
      Topic  Documents
0   Topic_1          4
1  Topic_10         10
2  Topic_11          3
3  Topic_12          6
4  Topic_13         18
Training Fold 2  K=16
Finished in 2.30 seconds
============================================================
Fold: 2
K: 16
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (16, 860)
============================================================
Theta Shape      : (240, 19)
Phi Shape        : (16, 860)
Top Words Rows   : 320
Topic Statistics :
      Topic  Documents
0   Topic_1          4
1  Topic_10         11
2  Topic_11          6
3  Topic_12          7
4  Topic_13         19
Training Fold 2  K=17
Finished in 2.46 seconds
============================================================
Fold: 2
K: 17
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (17, 860)
============================================================
Theta Shape      : (240, 20)
Phi Shape        : (17, 860)
Top Words Rows   : 340
Topic Statistics :
      Topic  Documents
0   Topic_1          2
1  Topic_10         12
2  Topic_11          2
3  Topic_12         12
4  Topic_13          5
Training Fold 2  K=18
Finished in 3.34 seconds
============================================================
Fold: 2
K: 18
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (18, 860)
============================================================
Theta Shape      : (240, 21)
Phi Shape        : (18, 860)
Top Words Rows   : 360
Topic Statistics :
      Topic  Documents
0   Topic_1          3
1  Topic_10         11
2  Topic_11          4
3  Topic_12         10
4  Topic_13          8
Training Fold 2  K=19
Finished in 3.38 seconds
============================================================
Fold: 2
K: 19
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (19, 860)
============================================================
Theta Shape      : (240, 22)
Phi Shape        : (19, 860)
Top Words Rows   : 380
Topic Statistics :
      Topic  Documents
0   Topic_1          4
1  Topic_10         12
2  Topic_11          3
3  Topic_12          6
4  Topic_13         12
Training Fold 2  K=20
Finished in 2.41 seconds
============================================================
Fold: 2
K: 20
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (20, 860)
============================================================
Theta Shape      : (240, 23)
Phi Shape        : (20, 860)
Top Words Rows   : 400
Topic Statistics :
      Topic  Documents
0   Topic_1          4
1  Topic_10          8
2  Topic_11          4
3  Topic_12          4
4  Topic_13          8
Training Fold 2  K=21
Finished in 2.46 seconds
============================================================
Fold: 2
K: 21
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (21, 860)
============================================================
Theta Shape      : (240, 24)
Phi Shape        : (21, 860)
Top Words Rows   : 420
Topic Statistics :
      Topic  Documents
0   Topic_1          1
1  Topic_10         11
2  Topic_11          5
3  Topic_12          6
4  Topic_13         12
Training Fold 2  K=22
Finished in 3.47 seconds
============================================================
Fold: 2
K: 22
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (22, 860)
============================================================
Theta Shape      : (240, 25)
Phi Shape        : (22, 860)
Top Words Rows   : 440
Topic Statistics :
      Topic  Documents
0   Topic_1          4
1  Topic_10          7
2  Topic_11          4
3  Topic_12          8
4  Topic_13          7
Training Fold 2  K=23
Finished in 3.39 seconds
============================================================
Fold: 2
K: 23
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (23, 860)
============================================================
Theta Shape      : (240, 26)
Phi Shape        : (23, 860)
Top Words Rows   : 460
Topic Statistics :
      Topic  Documents
0   Topic_1          2
1  Topic_10          9
2  Topic_11          3
3  Topic_12          5
4  Topic_13          4
Training Fold 2  K=24
Finished in 2.41 seconds
============================================================
Fold: 2
K: 24
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (24, 860)
============================================================
Theta Shape      : (240, 27)
Phi Shape        : (24, 860)
Top Words Rows   : 480
Topic Statistics :
      Topic  Documents
0   Topic_1          5
1  Topic_10         10
2  Topic_11          3
3  Topic_12          5
4  Topic_13          4
Training Fold 2  K=25
Finished in 2.54 seconds
============================================================
Fold: 2
K: 25
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (25, 860)
============================================================
Theta Shape      : (240, 28)
Phi Shape        : (25, 860)
Top Words Rows   : 500
Topic Statistics :
      Topic  Documents
0   Topic_1          7
1  Topic_10          8
2  Topic_11          1
3  Topic_12          1
4  Topic_13          5
Training Fold 2  K=26
Finished in 3.90 seconds
============================================================
Fold: 2
K: 26
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (26, 860)
============================================================
Theta Shape      : (240, 29)
Phi Shape        : (26, 860)
Top Words Rows   : 520
Topic Statistics :
      Topic  Documents
0   Topic_1          9
1  Topic_10         10
2  Topic_11          2
3  Topic_12          3
4  Topic_13          4
Training Fold 2  K=27
Finished in 2.75 seconds
============================================================
Fold: 2
K: 27
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (27, 860)
============================================================
Theta Shape      : (240, 30)
Phi Shape        : (27, 860)
Top Words Rows   : 540
Topic Statistics :
      Topic  Documents
0   Topic_1          4
1  Topic_10         10
2  Topic_11          3
3  Topic_12          3
4  Topic_13          5
Training Fold 2  K=28
Finished in 2.49 seconds
============================================================
Fold: 2
K: 28
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (28, 860)
============================================================
Theta Shape      : (240, 31)
Phi Shape        : (28, 860)
Top Words Rows   : 560
Topic Statistics :
      Topic  Documents
0   Topic_1          3
1  Topic_10          9
2  Topic_11          3
3  Topic_12          6
4  Topic_13          6
Training Fold 2  K=29
Finished in 2.39 seconds
============================================================
Fold: 2
K: 29
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (29, 860)
============================================================
Theta Shape      : (240, 32)
Phi Shape        : (29, 860)
Top Words Rows   : 580
Topic Statistics :
      Topic  Documents
0   Topic_1          5
1  Topic_10         10
2  Topic_11         10
3  Topic_12          5
4  Topic_13          4
Training Fold 2  K=30
Finished in 4.04 seconds
============================================================
Fold: 2
K: 30
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (30, 860)
============================================================
Theta Shape      : (240, 33)
Phi Shape        : (30, 860)
Top Words Rows   : 600
Topic Statistics :
      Topic  Documents
0   Topic_1          2
1  Topic_10          5
2  Topic_11          4
3  Topic_12          3
4  Topic_13          7
Training Fold 2  K=31
Finished in 2.61 seconds
============================================================
Fold: 2
K: 31
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (31, 860)
============================================================
Theta Shape      : (240, 34)
Phi Shape        : (31, 860)
Top Words Rows   : 620
Topic Statistics :
      Topic  Documents
0   Topic_1          3
1  Topic_10          8
2  Topic_11          8
3  Topic_12          3
4  Topic_13         12
Training Fold 2  K=32
Finished in 2.43 seconds
============================================================
Fold: 2
K: 32
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (32, 860)
============================================================
Theta Shape      : (240, 35)
Phi Shape        : (32, 860)
Top Words Rows   : 640
Topic Statistics :
      Topic  Documents
0   Topic_1          4
1  Topic_10          8
2  Topic_11          3
3  Topic_12          3
4  Topic_13          3
Training Fold 2  K=33
Finished in 2.43 seconds
============================================================
Fold: 2
K: 33
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (33, 860)
============================================================
Theta Shape      : (240, 36)
Phi Shape        : (33, 860)
Top Words Rows   : 660
Topic Statistics :
      Topic  Documents
0   Topic_1          3
1  Topic_10         10
2  Topic_11          2
3  Topic_12          3
4  Topic_13          4
Training Fold 2  K=34
Finished in 4.10 seconds
============================================================
Fold: 2
K: 34
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (34, 860)
============================================================
Theta Shape      : (240, 37)
Phi Shape        : (34, 860)
Top Words Rows   : 680
Topic Statistics :
      Topic  Documents
0   Topic_1          2
1  Topic_10          6
2  Topic_11          1
3  Topic_12          7
4  Topic_13          3
Training Fold 2  K=35
Finished in 2.60 seconds
============================================================
Fold: 2
K: 35
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (35, 860)
============================================================
Theta Shape      : (240, 38)
Phi Shape        : (35, 860)
Top Words Rows   : 700
Topic Statistics :
      Topic  Documents
0   Topic_1          4
1  Topic_10          7
2  Topic_11          4
3  Topic_12          3
4  Topic_13          3
Training Fold 2  K=36
Finished in 2.43 seconds
============================================================
Fold: 2
K: 36
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (36, 860)
============================================================
Theta Shape      : (240, 39)
Phi Shape        : (36, 860)
Top Words Rows   : 720
Topic Statistics :
      Topic  Documents
0   Topic_1          4
1  Topic_10          7
2  Topic_11          1
3  Topic_12          2
4  Topic_13          3
Training Fold 2  K=37
Finished in 2.46 seconds
============================================================
Fold: 2
K: 37
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (37, 860)
============================================================
Theta Shape      : (240, 40)
Phi Shape        : (37, 860)
Top Words Rows   : 740
Topic Statistics :
      Topic  Documents
0   Topic_1          3
1  Topic_10          7
2  Topic_11          4
3  Topic_12          2
4  Topic_13          3
Training Fold 2  K=38
Finished in 4.54 seconds
============================================================
Fold: 2
K: 38
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (38, 860)
============================================================
Theta Shape      : (240, 41)
Phi Shape        : (38, 860)
Top Words Rows   : 760
Topic Statistics :
      Topic  Documents
0   Topic_1          1
1  Topic_10          4
2  Topic_11          2
3  Topic_12          2
4  Topic_13          5
Training Fold 2  K=39
Finished in 3.80 seconds
============================================================
Fold: 2
K: 39
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (39, 860)
============================================================
Theta Shape      : (240, 42)
Phi Shape        : (39, 860)
Top Words Rows   : 780
Topic Statistics :
      Topic  Documents
0   Topic_1          8
1  Topic_10          4
2  Topic_11          3
3  Topic_12          1
4  Topic_13          4
Training Fold 2  K=40
Finished in 3.62 seconds
============================================================
Fold: 2
K: 40
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (40, 860)
============================================================
Theta Shape      : (240, 43)
Phi Shape        : (40, 860)
Top Words Rows   : 800
Topic Statistics :
      Topic  Documents
0   Topic_1          8
1  Topic_10          6
2  Topic_11          2
3  Topic_12         12
4  Topic_13          5
Training Fold 2  K=41
Finished in 5.68 seconds
============================================================
Fold: 2
K: 41
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (41, 860)
============================================================
Theta Shape      : (240, 44)
Phi Shape        : (41, 860)
Top Words Rows   : 820
Topic Statistics :
      Topic  Documents
0   Topic_1          5
1  Topic_10          5
2  Topic_11          4
3  Topic_13          1
4  Topic_14         17
Training Fold 2  K=42
Finished in 4.08 seconds
============================================================
Fold: 2
K: 42
Dictionary Size : 860
Max Dictionary ID: 859
LDA Topic Matrix : (42, 860)
============================================================
Theta Shape      : (240, 45)
Phi Shape        : (42, 860)
Top Words Rows   : 840
Topic Statistics :
      Topic  Documents
0  Topic_10          3

Fold 3:   0%|          | 0/99 [00:00<?, ?it/s]

Training Fold 3  K=2
Finished in 3.68 seconds
============================================================
Fold: 3
K: 2
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (2, 857)
============================================================
Theta Shape      : (240, 5)
Phi Shape        : (2, 857)
Top Words Rows   : 40
Topic Statistics :
     Topic  Documents
0  Topic_1        106
1  Topic_2        134
Training Fold 3  K=3
Finished in 3.79 seconds
============================================================
Fold: 3
K: 3
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (3, 857)
============================================================
Theta Shape      : (240, 6)
Phi Shape        : (3, 857)
Top Words Rows   : 60
Topic Statistics :
     Topic  Documents
0  Topic_1        100
1  Topic_2         68
2  Topic_3         72
Training Fold 3  K=4
Finished in 2.54 seconds
============================================================
Fold: 3
K: 4
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (4, 857)
============================================================
Theta Shape      : (240, 7)
Phi Shape        : (4, 857)
Top Words Rows   : 80
Topic Statistics :
     Topic  Documents
0  Topic_1         93
1  Topic_2         53
2  Topic_3         63
3  Topic_4         31
Training Fold 3  K=5
Finished in 2.58 seconds
============================================================
Fold: 3
K: 5
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (5, 857)
============================================================
Theta Shape      : (240, 8)
Phi Shape        : (5, 857)
Top Words Rows   : 100
Topic Statistics :
     Topic  Documents
0  Topic_1         95
1  Topic_2         23
2  Topic_3         55
3  Topic_4         27
4  Topic_5         40
Training Fold 3  K=6
Finished in 3.79 seconds
============================================================
Fold: 3
K: 6
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (6, 857)
============================================================
Theta Shape      : (240, 9)
Phi Shape        : (6, 857)
Top Words Rows   : 120
Topic Statistics :
     Topic  Documents
0  Topic_1         93
1  Topic_2         32
2  Topic_3         33
3  Topic_4         24
4  Topic_5         34
Training Fold 3  K=7
Finished in 3.01 seconds
============================================================
Fold: 3
K: 7
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (7, 857)
============================================================
Theta Shape      : (240, 10)
Phi Shape        : (7, 857)
Top Words Rows   : 140
Topic Statistics :
     Topic  Documents
0  Topic_1         49
1  Topic_2         28
2  Topic_3         24
3  Topic_4         15
4  Topic_5         30
Training Fold 3  K=8
Finished in 2.42 seconds
============================================================
Fold: 3
K: 8
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (8, 857)
============================================================
Theta Shape      : (240, 11)
Phi Shape        : (8, 857)
Top Words Rows   : 160
Topic Statistics :
     Topic  Documents
0  Topic_1         45
1  Topic_2         24
2  Topic_3         32
3  Topic_4          9
4  Topic_5         29
Training Fold 3  K=9
Finished in 2.51 seconds
============================================================
Fold: 3
K: 9
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (9, 857)
============================================================
Theta Shape      : (240, 12)
Phi Shape        : (9, 857)
Top Words Rows   : 180
Topic Statistics :
     Topic  Documents
0  Topic_1         40
1  Topic_2         21
2  Topic_3         13
3  Topic_4         17
4  Topic_5         24
Training Fold 3  K=10
Finished in 3.93 seconds
============================================================
Fold: 3
K: 10
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (10, 857)
============================================================
Theta Shape      : (240, 13)
Phi Shape        : (10, 857)
Top Words Rows   : 200
Topic Statistics :
      Topic  Documents
0   Topic_1         34
1  Topic_10         23
2   Topic_2         15
3   Topic_3         12
4   Topic_4         18
Training Fold 3  K=11
Finished in 2.86 seconds
============================================================
Fold: 3
K: 11
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (11, 857)
============================================================
Theta Shape      : (240, 14)
Phi Shape        : (11, 857)
Top Words Rows   : 220
Topic Statistics :
      Topic  Documents
0   Topic_1         35
1  Topic_10         22
2  Topic_11          8
3   Topic_2         16
4   Topic_3         13
Training Fold 3  K=12
Finished in 2.37 seconds
============================================================
Fold: 3
K: 12
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (12, 857)
============================================================
Theta Shape      : (240, 15)
Phi Shape        : (12, 857)
Top Words Rows   : 240
Topic Statistics :
      Topic  Documents
0   Topic_1         35
1  Topic_10         25
2  Topic_11         11
3  Topic_12         21
4   Topic_2         19
Training Fold 3  K=13
Finished in 2.46 seconds
============================================================
Fold: 3
K: 13
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (13, 857)
============================================================
Theta Shape      : (240, 16)
Phi Shape        : (13, 857)
Top Words Rows   : 260
Topic Statistics :
      Topic  Documents
0   Topic_1         37
1  Topic_10         23
2  Topic_11         10
3  Topic_12         12
4  Topic_13         18
Training Fold 3  K=14
Finished in 4.20 seconds
============================================================
Fold: 3
K: 14
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (14, 857)
============================================================
Theta Shape      : (240, 17)
Phi Shape        : (14, 857)
Top Words Rows   : 280
Topic Statistics :
      Topic  Documents
0   Topic_1         30
1  Topic_10         23
2  Topic_11         10
3  Topic_12         14
4  Topic_13         11
Training Fold 3  K=15
Finished in 2.67 seconds
============================================================
Fold: 3
K: 15
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (15, 857)
============================================================
Theta Shape      : (240, 18)
Phi Shape        : (15, 857)
Top Words Rows   : 300
Topic Statistics :
      Topic  Documents
0   Topic_1         22
1  Topic_10         18
2  Topic_11         11
3  Topic_12         10
4  Topic_13         10
Training Fold 3  K=16
Finished in 2.42 seconds
============================================================
Fold: 3
K: 16
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (16, 857)
============================================================
Theta Shape      : (240, 19)
Phi Shape        : (16, 857)
Top Words Rows   : 320
Topic Statistics :
      Topic  Documents
0   Topic_1         26
1  Topic_10         20
2  Topic_11          8
3  Topic_12         13
4  Topic_13         11
Training Fold 3  K=17
Finished in 2.40 seconds
============================================================
Fold: 3
K: 17
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (17, 857)
============================================================
Theta Shape      : (240, 20)
Phi Shape        : (17, 857)
Top Words Rows   : 340
Topic Statistics :
      Topic  Documents
0   Topic_1          5
1  Topic_10         18
2  Topic_11          7
3  Topic_12         11
4  Topic_13         19
Training Fold 3  K=18
Finished in 4.15 seconds
============================================================
Fold: 3
K: 18
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (18, 857)
============================================================
Theta Shape      : (240, 21)
Phi Shape        : (18, 857)
Top Words Rows   : 360
Topic Statistics :
      Topic  Documents
0   Topic_1          5
1  Topic_10          9
2  Topic_11          6
3  Topic_12          9
4  Topic_13          7
Training Fold 3  K=19
Finished in 2.47 seconds
============================================================
Fold: 3
K: 19
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (19, 857)
============================================================
Theta Shape      : (240, 22)
Phi Shape        : (19, 857)
Top Words Rows   : 380
Topic Statistics :
      Topic  Documents
0   Topic_1          5
1  Topic_10         14
2  Topic_11          7
3  Topic_12         15
4  Topic_13         18
Training Fold 3  K=20
Finished in 2.45 seconds
============================================================
Fold: 3
K: 20
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (20, 857)
============================================================
Theta Shape      : (240, 23)
Phi Shape        : (20, 857)
Top Words Rows   : 400
Topic Statistics :
      Topic  Documents
0   Topic_1          4
1  Topic_10         19
2  Topic_11          5
3  Topic_12         10
4  Topic_13         17
Training Fold 3  K=21
Finished in 2.39 seconds
============================================================
Fold: 3
K: 21
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (21, 857)
============================================================
Theta Shape      : (240, 24)
Phi Shape        : (21, 857)
Top Words Rows   : 420
Topic Statistics :
      Topic  Documents
0   Topic_1         11
1  Topic_10         15
2  Topic_11          4
3  Topic_12         10
4  Topic_13          4
Training Fold 3  K=22
Finished in 4.15 seconds
============================================================
Fold: 3
K: 22
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (22, 857)
============================================================
Theta Shape      : (240, 25)
Phi Shape        : (22, 857)
Top Words Rows   : 440
Topic Statistics :
      Topic  Documents
0   Topic_1          4
1  Topic_10         15
2  Topic_11          3
3  Topic_12         16
4  Topic_13         15
Training Fold 3  K=23
Finished in 2.54 seconds
============================================================
Fold: 3
K: 23
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (23, 857)
============================================================
Theta Shape      : (240, 26)
Phi Shape        : (23, 857)
Top Words Rows   : 460
Topic Statistics :
      Topic  Documents
0   Topic_1          4
1  Topic_10         12
2  Topic_11          9
3  Topic_12          2
4  Topic_13          5
Training Fold 3  K=24
Finished in 2.38 seconds
============================================================
Fold: 3
K: 24
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (24, 857)
============================================================
Theta Shape      : (240, 27)
Phi Shape        : (24, 857)
Top Words Rows   : 480
Topic Statistics :
      Topic  Documents
0   Topic_1          2
1  Topic_10         13
2  Topic_11          6
3  Topic_12         12
4  Topic_13          7
Training Fold 3  K=25
Finished in 2.43 seconds
============================================================
Fold: 3
K: 25
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (25, 857)
============================================================
Theta Shape      : (240, 28)
Phi Shape        : (25, 857)
Top Words Rows   : 500
Topic Statistics :
      Topic  Documents
0   Topic_1          2
1  Topic_10         16
2  Topic_11          8
3  Topic_12         15
4  Topic_13         11
Training Fold 3  K=26
Finished in 3.82 seconds
============================================================
Fold: 3
K: 26
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (26, 857)
============================================================
Theta Shape      : (240, 29)
Phi Shape        : (26, 857)
Top Words Rows   : 520
Topic Statistics :
      Topic  Documents
0   Topic_1          2
1  Topic_10         16
2  Topic_11          6
3  Topic_12          6
4  Topic_13          4
Training Fold 3  K=27
Finished in 2.36 seconds
============================================================
Fold: 3
K: 27
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (27, 857)
============================================================
Theta Shape      : (240, 30)
Phi Shape        : (27, 857)
Top Words Rows   : 540
Topic Statistics :
      Topic  Documents
0   Topic_1          3
1  Topic_10         19
2  Topic_11          5
3  Topic_12          4
4  Topic_13         11
Training Fold 3  K=28
Finished in 2.83 seconds
============================================================
Fold: 3
K: 28
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (28, 857)
============================================================
Theta Shape      : (240, 31)
Phi Shape        : (28, 857)
Top Words Rows   : 560
Topic Statistics :
      Topic  Documents
0   Topic_1          4
1  Topic_10         20
2  Topic_11          3
3  Topic_12          8
4  Topic_13          3
Training Fold 3  K=29
Finished in 2.60 seconds
============================================================
Fold: 3
K: 29
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (29, 857)
============================================================
Theta Shape      : (240, 32)
Phi Shape        : (29, 857)
Top Words Rows   : 580
Topic Statistics :
      Topic  Documents
0   Topic_1          5
1  Topic_10          8
2  Topic_11          3
3  Topic_12          9
4  Topic_13          5
Training Fold 3  K=30
Finished in 4.15 seconds
============================================================
Fold: 3
K: 30
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (30, 857)
============================================================
Theta Shape      : (240, 33)
Phi Shape        : (30, 857)
Top Words Rows   : 600
Topic Statistics :
      Topic  Documents
0   Topic_1          3
1  Topic_10          8
2  Topic_11          7
3  Topic_12          5
4  Topic_13          4
Training Fold 3  K=31
Finished in 2.55 seconds
============================================================
Fold: 3
K: 31
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (31, 857)
============================================================
Theta Shape      : (240, 34)
Phi Shape        : (31, 857)
Top Words Rows   : 620
Topic Statistics :
      Topic  Documents
0   Topic_1          4
1  Topic_10          3
2  Topic_11          2
3  Topic_12          4
4  Topic_13          3
Training Fold 3  K=32
Finished in 2.46 seconds
============================================================
Fold: 3
K: 32
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (32, 857)
============================================================
Theta Shape      : (240, 35)
Phi Shape        : (32, 857)
Top Words Rows   : 640
Topic Statistics :
      Topic  Documents
0   Topic_1          4
1  Topic_10         12
2  Topic_11          5
3  Topic_12          5
4  Topic_13          3
Training Fold 3  K=33
Finished in 3.45 seconds
============================================================
Fold: 3
K: 33
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (33, 857)
============================================================
Theta Shape      : (240, 36)
Phi Shape        : (33, 857)
Top Words Rows   : 660
Topic Statistics :
      Topic  Documents
0   Topic_1          2
1  Topic_10         14
2  Topic_11          4
3  Topic_12          7
4  Topic_13          3
Training Fold 3  K=34
Finished in 3.53 seconds
============================================================
Fold: 3
K: 34
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (34, 857)
============================================================
Theta Shape      : (240, 37)
Phi Shape        : (34, 857)
Top Words Rows   : 680
Topic Statistics :
      Topic  Documents
0   Topic_1          6
1  Topic_10          5
2  Topic_11          2
3  Topic_12          8
4  Topic_13          8
Training Fold 3  K=35
Finished in 2.56 seconds
============================================================
Fold: 3
K: 35
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (35, 857)
============================================================
Theta Shape      : (240, 38)
Phi Shape        : (35, 857)
Top Words Rows   : 700
Topic Statistics :
      Topic  Documents
0   Topic_1          4
1  Topic_10          4
2  Topic_11          9
3  Topic_12          9
4  Topic_13          5
Training Fold 3  K=36
Finished in 2.46 seconds
============================================================
Fold: 3
K: 36
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (36, 857)
============================================================
Theta Shape      : (240, 39)
Phi Shape        : (36, 857)
Top Words Rows   : 720
Topic Statistics :
      Topic  Documents
0   Topic_1          6
1  Topic_10          9
2  Topic_11          6
3  Topic_12          8
4  Topic_13          3
Training Fold 3  K=37
Finished in 3.83 seconds
============================================================
Fold: 3
K: 37
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (37, 857)
============================================================
Theta Shape      : (240, 40)
Phi Shape        : (37, 857)
Top Words Rows   : 740
Topic Statistics :
      Topic  Documents
0   Topic_1          2
1  Topic_10          4
2  Topic_11          5
3  Topic_12          8
4  Topic_13          3
Training Fold 3  K=38
Finished in 3.75 seconds
============================================================
Fold: 3
K: 38
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (38, 857)
============================================================
Theta Shape      : (240, 41)
Phi Shape        : (38, 857)
Top Words Rows   : 760
Topic Statistics :
      Topic  Documents
0   Topic_1          2
1  Topic_10          7
2  Topic_11          3
3  Topic_12          4
4  Topic_13          5
Training Fold 3  K=39
Finished in 4.21 seconds
============================================================
Fold: 3
K: 39
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (39, 857)
============================================================
Theta Shape      : (240, 42)
Phi Shape        : (39, 857)
Top Words Rows   : 780
Topic Statistics :
      Topic  Documents
0   Topic_1          5
1  Topic_10         11
2  Topic_11          5
3  Topic_12          3
4  Topic_13          4
Training Fold 3  K=40
Finished in 6.01 seconds
============================================================
Fold: 3
K: 40
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (40, 857)
============================================================
Theta Shape      : (240, 43)
Phi Shape        : (40, 857)
Top Words Rows   : 800
Topic Statistics :
      Topic  Documents
0   Topic_1          5
1  Topic_10          4
2  Topic_11          2
3  Topic_12         12
4  Topic_13          3
Training Fold 3  K=41
Finished in 3.83 seconds
============================================================
Fold: 3
K: 41
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (41, 857)
============================================================
Theta Shape      : (240, 44)
Phi Shape        : (41, 857)
Top Words Rows   : 820
Topic Statistics :
      Topic  Documents
0   Topic_1          4
1  Topic_10          7
2  Topic_11          2
3  Topic_12          3
4  Topic_13          5
Training Fold 3  K=42
Finished in 3.97 seconds
============================================================
Fold: 3
K: 42
Dictionary Size : 857
Max Dictionary ID: 856
LDA Topic Matrix : (42, 857)
============================================================
Theta Shape      : (240, 45)
Phi Shape        : (42, 857)
Top Words Rows   : 840
Topic Statistics :
      Topic  Documents
0   Topic_1          8

Fold 4:   0%|          | 0/99 [00:00<?, ?it/s]

Training Fold 4  K=2
Finished in 3.47 seconds
============================================================
Fold: 4
K: 2
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (2, 886)
============================================================
Theta Shape      : (240, 5)
Phi Shape        : (2, 886)
Top Words Rows   : 40
Topic Statistics :
     Topic  Documents
0  Topic_1        133
1  Topic_2        107
Training Fold 4  K=3
Finished in 4.60 seconds
============================================================
Fold: 4
K: 3
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (3, 886)
============================================================
Theta Shape      : (240, 6)
Phi Shape        : (3, 886)
Top Words Rows   : 60
Topic Statistics :
     Topic  Documents
0  Topic_1         95
1  Topic_2         78
2  Topic_3         67
Training Fold 4  K=4
Finished in 2.42 seconds
============================================================
Fold: 4
K: 4
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (4, 886)
============================================================
Theta Shape      : (240, 7)
Phi Shape        : (4, 886)
Top Words Rows   : 80
Topic Statistics :
     Topic  Documents
0  Topic_1         72
1  Topic_2         30
2  Topic_3         44
3  Topic_4         94
Training Fold 4  K=5
Finished in 2.38 seconds
============================================================
Fold: 4
K: 5
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (5, 886)
============================================================
Theta Shape      : (240, 8)
Phi Shape        : (5, 886)
Top Words Rows   : 100
Topic Statistics :
     Topic  Documents
0  Topic_1         69
1  Topic_2         15
2  Topic_3         47
3  Topic_4         59
4  Topic_5         50
Training Fold 4  K=6
Finished in 2.97 seconds
============================================================
Fold: 4
K: 6
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (6, 886)
============================================================
Theta Shape      : (240, 9)
Phi Shape        : (6, 886)
Top Words Rows   : 120
Topic Statistics :
     Topic  Documents
0  Topic_1         69
1  Topic_2         24
2  Topic_3         26
3  Topic_4         45
4  Topic_5         50
Training Fold 4  K=7
Finished in 3.63 seconds
============================================================
Fold: 4
K: 7
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (7, 886)
============================================================
Theta Shape      : (240, 10)
Phi Shape        : (7, 886)
Top Words Rows   : 140
Topic Statistics :
     Topic  Documents
0  Topic_1         64
1  Topic_2         13
2  Topic_3         28
3  Topic_4         38
4  Topic_5         46
Training Fold 4  K=8
Finished in 2.52 seconds
============================================================
Fold: 4
K: 8
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (8, 886)
============================================================
Theta Shape      : (240, 11)
Phi Shape        : (8, 886)
Top Words Rows   : 160
Topic Statistics :
     Topic  Documents
0  Topic_1         65
1  Topic_2         14
2  Topic_3         15
3  Topic_4         39
4  Topic_5         43
Training Fold 4  K=9
Finished in 2.50 seconds
============================================================
Fold: 4
K: 9
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (9, 886)
============================================================
Theta Shape      : (240, 12)
Phi Shape        : (9, 886)
Top Words Rows   : 180
Topic Statistics :
     Topic  Documents
0  Topic_1         60
1  Topic_2         18
2  Topic_3         15
3  Topic_4         32
4  Topic_5         42
Training Fold 4  K=10
Finished in 2.93 seconds
============================================================
Fold: 4
K: 10
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (10, 886)
============================================================
Theta Shape      : (240, 13)
Phi Shape        : (10, 886)
Top Words Rows   : 200
Topic Statistics :
      Topic  Documents
0   Topic_1         47
1  Topic_10         21
2   Topic_2         12
3   Topic_3         28
4   Topic_4         42
Training Fold 4  K=11
Finished in 3.63 seconds
============================================================
Fold: 4
K: 11
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (11, 886)
============================================================
Theta Shape      : (240, 14)
Phi Shape        : (11, 886)
Top Words Rows   : 220
Topic Statistics :
      Topic  Documents
0   Topic_1         47
1  Topic_10         26
2  Topic_11         21
3   Topic_2          7
4   Topic_3          7
Training Fold 4  K=12
Finished in 2.49 seconds
============================================================
Fold: 4
K: 12
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (12, 886)
============================================================
Theta Shape      : (240, 15)
Phi Shape        : (12, 886)
Top Words Rows   : 240
Topic Statistics :
      Topic  Documents
0   Topic_1         41
1  Topic_10         12
2  Topic_11         20
3  Topic_12          9
4   Topic_2         10
Training Fold 4  K=13
Finished in 2.60 seconds
============================================================
Fold: 4
K: 13
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (13, 886)
============================================================
Theta Shape      : (240, 16)
Phi Shape        : (13, 886)
Top Words Rows   : 260
Topic Statistics :
      Topic  Documents
0   Topic_1         24
1  Topic_10         27
2  Topic_11         19
3  Topic_12         22
4  Topic_13         23
Training Fold 4  K=14
Finished in 3.56 seconds
============================================================
Fold: 4
K: 14
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (14, 886)
============================================================
Theta Shape      : (240, 17)
Phi Shape        : (14, 886)
Top Words Rows   : 280
Topic Statistics :
      Topic  Documents
0   Topic_1         20
1  Topic_10         29
2  Topic_11         21
3  Topic_12         24
4  Topic_13         24
Training Fold 4  K=15
Finished in 3.48 seconds
============================================================
Fold: 4
K: 15
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (15, 886)
============================================================
Theta Shape      : (240, 18)
Phi Shape        : (15, 886)
Top Words Rows   : 300
Topic Statistics :
      Topic  Documents
0   Topic_1         33
1  Topic_10         28
2  Topic_11         19
3  Topic_12         22
4  Topic_13         15
Training Fold 4  K=16
Finished in 2.59 seconds
============================================================
Fold: 4
K: 16
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (16, 886)
============================================================
Theta Shape      : (240, 19)
Phi Shape        : (16, 886)
Top Words Rows   : 320
Topic Statistics :
      Topic  Documents
0   Topic_1         26
1  Topic_10         26
2  Topic_11         21
3  Topic_12         23
4  Topic_13         22
Training Fold 4  K=17
Finished in 2.57 seconds
============================================================
Fold: 4
K: 17
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (17, 886)
============================================================
Theta Shape      : (240, 20)
Phi Shape        : (17, 886)
Top Words Rows   : 340
Topic Statistics :
      Topic  Documents
0   Topic_1         13
1  Topic_10         27
2  Topic_11          5
3  Topic_12         15
4  Topic_13         22
Training Fold 4  K=18
Finished in 4.00 seconds
============================================================
Fold: 4
K: 18
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (18, 886)
============================================================
Theta Shape      : (240, 21)
Phi Shape        : (18, 886)
Top Words Rows   : 360
Topic Statistics :
      Topic  Documents
0   Topic_1         19
1  Topic_10         21
2  Topic_11          7
3  Topic_12         20
4  Topic_13         14
Training Fold 4  K=19
Finished in 2.81 seconds
============================================================
Fold: 4
K: 19
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (19, 886)
============================================================
Theta Shape      : (240, 22)
Phi Shape        : (19, 886)
Top Words Rows   : 380
Topic Statistics :
      Topic  Documents
0   Topic_1         18
1  Topic_10         17
2  Topic_11          6
3  Topic_12         18
4  Topic_13         11
Training Fold 4  K=20
Finished in 2.62 seconds
============================================================
Fold: 4
K: 20
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (20, 886)
============================================================
Theta Shape      : (240, 23)
Phi Shape        : (20, 886)
Top Words Rows   : 400
Topic Statistics :
      Topic  Documents
0   Topic_1         11
1  Topic_10         23
2  Topic_11          7
3  Topic_12         16
4  Topic_13         13
Training Fold 4  K=21
Finished in 2.48 seconds
============================================================
Fold: 4
K: 21
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (21, 886)
============================================================
Theta Shape      : (240, 24)
Phi Shape        : (21, 886)
Top Words Rows   : 420
Topic Statistics :
      Topic  Documents
0   Topic_1         13
1  Topic_10         26
2  Topic_11          5
3  Topic_12         12
4  Topic_13         11
Training Fold 4  K=22
Finished in 4.00 seconds
============================================================
Fold: 4
K: 22
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (22, 886)
============================================================
Theta Shape      : (240, 25)
Phi Shape        : (22, 886)
Top Words Rows   : 440
Topic Statistics :
      Topic  Documents
0   Topic_1         12
1  Topic_10         23
2  Topic_11          6
3  Topic_12         18
4  Topic_13         11
Training Fold 4  K=23
Finished in 2.59 seconds
============================================================
Fold: 4
K: 23
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (23, 886)
============================================================
Theta Shape      : (240, 26)
Phi Shape        : (23, 886)
Top Words Rows   : 460
Topic Statistics :
      Topic  Documents
0   Topic_1         15
1  Topic_10         19
2  Topic_11          5
3  Topic_12         15
4  Topic_13         11
Training Fold 4  K=24
Finished in 2.47 seconds
============================================================
Fold: 4
K: 24
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (24, 886)
============================================================
Theta Shape      : (240, 27)
Phi Shape        : (24, 886)
Top Words Rows   : 480
Topic Statistics :
      Topic  Documents
0   Topic_1          8
1  Topic_10         12
2  Topic_11          7
3  Topic_12         23
4  Topic_13         13
Training Fold 4  K=25
Finished in 2.52 seconds
============================================================
Fold: 4
K: 25
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (25, 886)
============================================================
Theta Shape      : (240, 28)
Phi Shape        : (25, 886)
Top Words Rows   : 500
Topic Statistics :
      Topic  Documents
0   Topic_1         14
1  Topic_10         12
2  Topic_11         11
3  Topic_12         11
4  Topic_13         13
Training Fold 4  K=26
Finished in 4.16 seconds
============================================================
Fold: 4
K: 26
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (26, 886)
============================================================
Theta Shape      : (240, 29)
Phi Shape        : (26, 886)
Top Words Rows   : 520
Topic Statistics :
      Topic  Documents
0   Topic_1          8
1  Topic_10         16
2  Topic_11          6
3  Topic_12         15
4  Topic_13          8
Training Fold 4  K=27
Finished in 2.61 seconds
============================================================
Fold: 4
K: 27
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (27, 886)
============================================================
Theta Shape      : (240, 30)
Phi Shape        : (27, 886)
Top Words Rows   : 540
Topic Statistics :
      Topic  Documents
0   Topic_1         11
1  Topic_10         13
2  Topic_11          5
3  Topic_12         19
4  Topic_13          7
Training Fold 4  K=28
Finished in 2.56 seconds
============================================================
Fold: 4
K: 28
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (28, 886)
============================================================
Theta Shape      : (240, 31)
Phi Shape        : (28, 886)
Top Words Rows   : 560
Topic Statistics :
      Topic  Documents
0   Topic_1          7
1  Topic_10         15
2  Topic_11         10
3  Topic_12         19
4  Topic_13          8
Training Fold 4  K=29
Finished in 3.26 seconds
============================================================
Fold: 4
K: 29
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (29, 886)
============================================================
Theta Shape      : (240, 32)
Phi Shape        : (29, 886)
Top Words Rows   : 580
Topic Statistics :
      Topic  Documents
0   Topic_1          8
1  Topic_10         16
2  Topic_11         15
3  Topic_12         18
4  Topic_13         11
Training Fold 4  K=30
Finished in 3.83 seconds
============================================================
Fold: 4
K: 30
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (30, 886)
============================================================
Theta Shape      : (240, 33)
Phi Shape        : (30, 886)
Top Words Rows   : 600
Topic Statistics :
      Topic  Documents
0   Topic_1          7
1  Topic_10         13
2  Topic_11          4
3  Topic_12         22
4  Topic_13          8
Training Fold 4  K=31
Finished in 2.59 seconds
============================================================
Fold: 4
K: 31
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (31, 886)
============================================================
Theta Shape      : (240, 34)
Phi Shape        : (31, 886)
Top Words Rows   : 620
Topic Statistics :
      Topic  Documents
0   Topic_1         15
1  Topic_10         12
2  Topic_11          7
3  Topic_12         18
4  Topic_13          6
Training Fold 4  K=32
Finished in 2.65 seconds
============================================================
Fold: 4
K: 32
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (32, 886)
============================================================
Theta Shape      : (240, 35)
Phi Shape        : (32, 886)
Top Words Rows   : 640
Topic Statistics :
      Topic  Documents
0   Topic_1          7
1  Topic_10         17
2  Topic_11          6
3  Topic_12         15
4  Topic_13          9
Training Fold 4  K=33
Finished in 4.84 seconds
============================================================
Fold: 4
K: 33
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (33, 886)
============================================================
Theta Shape      : (240, 36)
Phi Shape        : (33, 886)
Top Words Rows   : 660
Topic Statistics :
      Topic  Documents
0   Topic_1         12
1  Topic_10         10
2  Topic_11         13
3  Topic_12         17
4  Topic_13          5
Training Fold 4  K=34
Finished in 2.68 seconds
============================================================
Fold: 4
K: 34
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (34, 886)
============================================================
Theta Shape      : (240, 37)
Phi Shape        : (34, 886)
Top Words Rows   : 680
Topic Statistics :
      Topic  Documents
0   Topic_1         10
1  Topic_10         14
2  Topic_11          3
3  Topic_12         18
4  Topic_13         15
Training Fold 4  K=35
Finished in 2.73 seconds
============================================================
Fold: 4
K: 35
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (35, 886)
============================================================
Theta Shape      : (240, 38)
Phi Shape        : (35, 886)
Top Words Rows   : 700
Topic Statistics :
      Topic  Documents
0   Topic_1          9
1  Topic_10          8
2  Topic_11          4
3  Topic_12          8
4  Topic_13         11
Training Fold 4  K=36
Finished in 2.71 seconds
============================================================
Fold: 4
K: 36
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (36, 886)
============================================================
Theta Shape      : (240, 39)
Phi Shape        : (36, 886)
Top Words Rows   : 720
Topic Statistics :
      Topic  Documents
0   Topic_1          8
1  Topic_10          8
2  Topic_11          4
3  Topic_12         13
4  Topic_13          8
Training Fold 4  K=37
Finished in 4.31 seconds
============================================================
Fold: 4
K: 37
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (37, 886)
============================================================
Theta Shape      : (240, 40)
Phi Shape        : (37, 886)
Top Words Rows   : 740
Topic Statistics :
      Topic  Documents
0   Topic_1          8
1  Topic_10         16
2  Topic_11          7
3  Topic_12         15
4  Topic_13         12
Training Fold 4  K=38
Finished in 3.25 seconds
============================================================
Fold: 4
K: 38
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (38, 886)
============================================================
Theta Shape      : (240, 41)
Phi Shape        : (38, 886)
Top Words Rows   : 760
Topic Statistics :
      Topic  Documents
0   Topic_1          8
1  Topic_10          9
2  Topic_11          5
3  Topic_12          5
4  Topic_13          6
Training Fold 4  K=39
Finished in 4.12 seconds
============================================================
Fold: 4
K: 39
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (39, 886)
============================================================
Theta Shape      : (240, 42)
Phi Shape        : (39, 886)
Top Words Rows   : 780
Topic Statistics :
      Topic  Documents
0   Topic_1          9
1  Topic_10          9
2  Topic_11          3
3  Topic_12         12
4  Topic_13          5
Training Fold 4  K=40
Finished in 5.56 seconds
============================================================
Fold: 4
K: 40
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (40, 886)
============================================================
Theta Shape      : (240, 43)
Phi Shape        : (40, 886)
Top Words Rows   : 800
Topic Statistics :
      Topic  Documents
0   Topic_1         10
1  Topic_10          8
2  Topic_11          6
3  Topic_12          8
4  Topic_13          6
Training Fold 4  K=41
Finished in 3.84 seconds
============================================================
Fold: 4
K: 41
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (41, 886)
============================================================
Theta Shape      : (240, 44)
Phi Shape        : (41, 886)
Top Words Rows   : 820
Topic Statistics :
      Topic  Documents
0   Topic_1          6
1  Topic_10         10
2  Topic_11          8
3  Topic_12          4
4  Topic_13          9
Training Fold 4  K=42
Finished in 4.90 seconds
============================================================
Fold: 4
K: 42
Dictionary Size : 886
Max Dictionary ID: 885
LDA Topic Matrix : (42, 886)
============================================================
Theta Shape      : (240, 45)
Phi Shape        : (42, 886)
Top Words Rows   : 840
Topic Statistics :
      Topic  Documents
0   Topic_1          9

Fold 5:   0%|          | 0/99 [00:00<?, ?it/s]

Training Fold 5  K=2
Finished in 3.01 seconds
============================================================
Fold: 5
K: 2
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (2, 882)
============================================================
Theta Shape      : (240, 5)
Phi Shape        : (2, 882)
Top Words Rows   : 40
Topic Statistics :
     Topic  Documents
0  Topic_1        141
1  Topic_2         99
Training Fold 5  K=3
Finished in 2.76 seconds
============================================================
Fold: 5
K: 3
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (3, 882)
============================================================
Theta Shape      : (240, 6)
Phi Shape        : (3, 882)
Top Words Rows   : 60
Topic Statistics :
     Topic  Documents
0  Topic_1         53
1  Topic_2         73
2  Topic_3        114
Training Fold 5  K=4
Finished in 3.33 seconds
============================================================
Fold: 5
K: 4
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (4, 882)
============================================================
Theta Shape      : (240, 7)
Phi Shape        : (4, 882)
Top Words Rows   : 80
Topic Statistics :
     Topic  Documents
0  Topic_1         28
1  Topic_2         71
2  Topic_3         72
3  Topic_4         69
Training Fold 5  K=5
Finished in 3.33 seconds
============================================================
Fold: 5
K: 5
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (5, 882)
============================================================
Theta Shape      : (240, 8)
Phi Shape        : (5, 882)
Top Words Rows   : 100
Topic Statistics :
     Topic  Documents
0  Topic_1         28
1  Topic_2         29
2  Topic_3         64
3  Topic_4         64
4  Topic_5         55
Training Fold 5  K=6
Finished in 2.32 seconds
============================================================
Fold: 5
K: 6
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (6, 882)
============================================================
Theta Shape      : (240, 9)
Phi Shape        : (6, 882)
Top Words Rows   : 120
Topic Statistics :
     Topic  Documents
0  Topic_1         36
1  Topic_2         15
2  Topic_3         29
3  Topic_4         54
4  Topic_5         61
Training Fold 5  K=7
Finished in 2.32 seconds
============================================================
Fold: 5
K: 7
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (7, 882)
============================================================
Theta Shape      : (240, 10)
Phi Shape        : (7, 882)
Top Words Rows   : 140
Topic Statistics :
     Topic  Documents
0  Topic_1         20
1  Topic_2         14
2  Topic_3         26
3  Topic_4         57
4  Topic_5         53
Training Fold 5  K=8
Finished in 2.87 seconds
============================================================
Fold: 5
K: 8
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (8, 882)
============================================================
Theta Shape      : (240, 11)
Phi Shape        : (8, 882)
Top Words Rows   : 160
Topic Statistics :
     Topic  Documents
0  Topic_1         24
1  Topic_2         15
2  Topic_3         24
3  Topic_4         38
4  Topic_5         54
Training Fold 5  K=9
Finished in 3.46 seconds
============================================================
Fold: 5
K: 9
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (9, 882)
============================================================
Theta Shape      : (240, 12)
Phi Shape        : (9, 882)
Top Words Rows   : 180
Topic Statistics :
     Topic  Documents
0  Topic_1          8
1  Topic_2         12
2  Topic_3         24
3  Topic_4         34
4  Topic_5         56
Training Fold 5  K=10
Finished in 2.31 seconds
============================================================
Fold: 5
K: 10
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (10, 882)
============================================================
Theta Shape      : (240, 13)
Phi Shape        : (10, 882)
Top Words Rows   : 200
Topic Statistics :
      Topic  Documents
0   Topic_1          7
1  Topic_10         15
2   Topic_2         12
3   Topic_3         23
4   Topic_4         24
Training Fold 5  K=11
Finished in 2.30 seconds
============================================================
Fold: 5
K: 11
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (11, 882)
============================================================
Theta Shape      : (240, 14)
Phi Shape        : (11, 882)
Top Words Rows   : 220
Topic Statistics :
      Topic  Documents
0   Topic_1          8
1  Topic_10         15
2  Topic_11         35
3   Topic_2         12
4   Topic_3         23
Training Fold 5  K=12
Finished in 2.78 seconds
============================================================
Fold: 5
K: 12
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (12, 882)
============================================================
Theta Shape      : (240, 15)
Phi Shape        : (12, 882)
Top Words Rows   : 240
Topic Statistics :
      Topic  Documents
0   Topic_1          7
1  Topic_10         12
2  Topic_11         35
3  Topic_12          9
4   Topic_2         17
Training Fold 5  K=13
Finished in 3.61 seconds
============================================================
Fold: 5
K: 13
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (13, 882)
============================================================
Theta Shape      : (240, 16)
Phi Shape        : (13, 882)
Top Words Rows   : 260
Topic Statistics :
      Topic  Documents
0   Topic_1          6
1  Topic_10         11
2  Topic_11         36
3  Topic_12          8
4  Topic_13          5
Training Fold 5  K=14
Finished in 2.48 seconds
============================================================
Fold: 5
K: 14
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (14, 882)
============================================================
Theta Shape      : (240, 17)
Phi Shape        : (14, 882)
Top Words Rows   : 280
Topic Statistics :
      Topic  Documents
0   Topic_1          5
1  Topic_10         14
2  Topic_11         34
3  Topic_12          5
4  Topic_13          4
Training Fold 5  K=15
Finished in 2.34 seconds
============================================================
Fold: 5
K: 15
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (15, 882)
============================================================
Theta Shape      : (240, 18)
Phi Shape        : (15, 882)
Top Words Rows   : 300
Topic Statistics :
      Topic  Documents
0   Topic_1          6
1  Topic_10         11
2  Topic_11         35
3  Topic_12          8
4  Topic_13          4
Training Fold 5  K=16
Finished in 2.80 seconds
============================================================
Fold: 5
K: 16
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (16, 882)
============================================================
Theta Shape      : (240, 19)
Phi Shape        : (16, 882)
Top Words Rows   : 320
Topic Statistics :
      Topic  Documents
0   Topic_1          4
1  Topic_10          7
2  Topic_11         35
3  Topic_12         11
4  Topic_13          4
Training Fold 5  K=17
Finished in 3.58 seconds
============================================================
Fold: 5
K: 17
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (17, 882)
============================================================
Theta Shape      : (240, 20)
Phi Shape        : (17, 882)
Top Words Rows   : 340
Topic Statistics :
      Topic  Documents
0   Topic_1          3
1  Topic_10          6
2  Topic_11         33
3  Topic_12         10
4  Topic_13          7
Training Fold 5  K=18
Finished in 2.44 seconds
============================================================
Fold: 5
K: 18
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (18, 882)
============================================================
Theta Shape      : (240, 21)
Phi Shape        : (18, 882)
Top Words Rows   : 360
Topic Statistics :
      Topic  Documents
0   Topic_1          7
1  Topic_10          6
2  Topic_11         34
3  Topic_12         12
4  Topic_13          4
Training Fold 5  K=19
Finished in 2.34 seconds
============================================================
Fold: 5
K: 19
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (19, 882)
============================================================
Theta Shape      : (240, 22)
Phi Shape        : (19, 882)
Top Words Rows   : 380
Topic Statistics :
      Topic  Documents
0   Topic_1          2
1  Topic_10          3
2  Topic_11         33
3  Topic_12         14
4  Topic_13          4
Training Fold 5  K=20
Finished in 2.60 seconds
============================================================
Fold: 5
K: 20
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (20, 882)
============================================================
Theta Shape      : (240, 23)
Phi Shape        : (20, 882)
Top Words Rows   : 400
Topic Statistics :
      Topic  Documents
0   Topic_1          4
1  Topic_10          4
2  Topic_11         38
3  Topic_12         15
4  Topic_13          5
Training Fold 5  K=21
Finished in 3.60 seconds
============================================================
Fold: 5
K: 21
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (21, 882)
============================================================
Theta Shape      : (240, 24)
Phi Shape        : (21, 882)
Top Words Rows   : 420
Topic Statistics :
      Topic  Documents
0   Topic_1          2
1  Topic_10          1
2  Topic_11         39
3  Topic_12         16
4  Topic_13          5
Training Fold 5  K=22
Finished in 2.40 seconds
============================================================
Fold: 5
K: 22
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (22, 882)
============================================================
Theta Shape      : (240, 25)
Phi Shape        : (22, 882)
Top Words Rows   : 440
Topic Statistics :
      Topic  Documents
0   Topic_1          5
1  Topic_10          4
2  Topic_11         30
3  Topic_12          8
4  Topic_13          4
Training Fold 5  K=23
Finished in 2.37 seconds
============================================================
Fold: 5
K: 23
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (23, 882)
============================================================
Theta Shape      : (240, 26)
Phi Shape        : (23, 882)
Top Words Rows   : 460
Topic Statistics :
      Topic  Documents
0   Topic_1          4
1  Topic_10          4
2  Topic_11         34
3  Topic_12          6
4  Topic_13          4
Training Fold 5  K=24
Finished in 2.66 seconds
============================================================
Fold: 5
K: 24
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (24, 882)
============================================================
Theta Shape      : (240, 27)
Phi Shape        : (24, 882)
Top Words Rows   : 480
Topic Statistics :
      Topic  Documents
0   Topic_1          3
1  Topic_10          4
2  Topic_11         27
3  Topic_12          7
4  Topic_13          4
Training Fold 5  K=25
Finished in 3.70 seconds
============================================================
Fold: 5
K: 25
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (25, 882)
============================================================
Theta Shape      : (240, 28)
Phi Shape        : (25, 882)
Top Words Rows   : 500
Topic Statistics :
      Topic  Documents
0   Topic_1          3
1  Topic_10          3
2  Topic_11         30
3  Topic_12          9
4  Topic_13          2
Training Fold 5  K=26
Finished in 2.30 seconds
============================================================
Fold: 5
K: 26
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (26, 882)
============================================================
Theta Shape      : (240, 29)
Phi Shape        : (26, 882)
Top Words Rows   : 520
Topic Statistics :
      Topic  Documents
0   Topic_1          1
1  Topic_10          2
2  Topic_11         28
3  Topic_12          6
4  Topic_13         11
Training Fold 5  K=27
Finished in 2.32 seconds
============================================================
Fold: 5
K: 27
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (27, 882)
============================================================
Theta Shape      : (240, 30)
Phi Shape        : (27, 882)
Top Words Rows   : 540
Topic Statistics :
      Topic  Documents
0   Topic_1          4
1  Topic_10          5
2  Topic_11         32
3  Topic_12          4
4  Topic_13          1
Training Fold 5  K=28
Finished in 2.46 seconds
============================================================
Fold: 5
K: 28
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (28, 882)
============================================================
Theta Shape      : (240, 31)
Phi Shape        : (28, 882)
Top Words Rows   : 560
Topic Statistics :
      Topic  Documents
0   Topic_1          3
1  Topic_10          2
2  Topic_11         27
3  Topic_12          6
4  Topic_13          2
Training Fold 5  K=29
Finished in 4.31 seconds
============================================================
Fold: 5
K: 29
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (29, 882)
============================================================
Theta Shape      : (240, 32)
Phi Shape        : (29, 882)
Top Words Rows   : 580
Topic Statistics :
      Topic  Documents
0   Topic_1          3
1  Topic_10          7
2  Topic_11         31
3  Topic_12          6
4  Topic_13          1
Training Fold 5  K=30
Finished in 2.60 seconds
============================================================
Fold: 5
K: 30
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (30, 882)
============================================================
Theta Shape      : (240, 33)
Phi Shape        : (30, 882)
Top Words Rows   : 600
Topic Statistics :
      Topic  Documents
0   Topic_1          3
1  Topic_10          4
2  Topic_11         23
3  Topic_12          6
4  Topic_13          6
Training Fold 5  K=31
Finished in 2.43 seconds
============================================================
Fold: 5
K: 31
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (31, 882)
============================================================
Theta Shape      : (240, 34)
Phi Shape        : (31, 882)
Top Words Rows   : 620
Topic Statistics :
      Topic  Documents
0   Topic_1          5
1  Topic_10          1
2  Topic_11         30
3  Topic_12          3
4  Topic_13          2
Training Fold 5  K=32
Finished in 2.78 seconds
============================================================
Fold: 5
K: 32
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (32, 882)
============================================================
Theta Shape      : (240, 35)
Phi Shape        : (32, 882)
Top Words Rows   : 640
Topic Statistics :
      Topic  Documents
0   Topic_1          2
1  Topic_10          3
2  Topic_11         25
3  Topic_12          3
4  Topic_14          2
Training Fold 5  K=33
Finished in 4.09 seconds
============================================================
Fold: 5
K: 33
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (33, 882)
============================================================
Theta Shape      : (240, 36)
Phi Shape        : (33, 882)
Top Words Rows   : 660
Topic Statistics :
      Topic  Documents
0   Topic_1          4
1  Topic_10          3
2  Topic_11         31
3  Topic_12          2
4  Topic_13          3
Training Fold 5  K=34
Finished in 2.45 seconds
============================================================
Fold: 5
K: 34
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (34, 882)
============================================================
Theta Shape      : (240, 37)
Phi Shape        : (34, 882)
Top Words Rows   : 680
Topic Statistics :
      Topic  Documents
0   Topic_1          4
1  Topic_10          3
2  Topic_11         25
3  Topic_12          4
4  Topic_13          1
Training Fold 5  K=35
Finished in 2.47 seconds
============================================================
Fold: 5
K: 35
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (35, 882)
============================================================
Theta Shape      : (240, 38)
Phi Shape        : (35, 882)
Top Words Rows   : 700
Topic Statistics :
      Topic  Documents
0   Topic_1          2
1  Topic_10          3
2  Topic_11         24
3  Topic_12          2
4  Topic_14          2
Training Fold 5  K=36
Finished in 3.07 seconds
============================================================
Fold: 5
K: 36
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (36, 882)
============================================================
Theta Shape      : (240, 39)
Phi Shape        : (36, 882)
Top Words Rows   : 720
Topic Statistics :
      Topic  Documents
0   Topic_1          4
1  Topic_10          2
2  Topic_11         26
3  Topic_12          5
4  Topic_13          2
Training Fold 5  K=37
Finished in 3.65 seconds
============================================================
Fold: 5
K: 37
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (37, 882)
============================================================
Theta Shape      : (240, 40)
Phi Shape        : (37, 882)
Top Words Rows   : 740
Topic Statistics :
      Topic  Documents
0   Topic_1          2
1  Topic_10          1
2  Topic_11         20
3  Topic_12          5
4  Topic_13          5
Training Fold 5  K=38
Finished in 3.26 seconds
============================================================
Fold: 5
K: 38
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (38, 882)
============================================================
Theta Shape      : (240, 41)
Phi Shape        : (38, 882)
Top Words Rows   : 760
Topic Statistics :
      Topic  Documents
0   Topic_1          1
1  Topic_10          8
2  Topic_11         28
3  Topic_12          4
4  Topic_13          1
Training Fold 5  K=39
Finished in 4.24 seconds
============================================================
Fold: 5
K: 39
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (39, 882)
============================================================
Theta Shape      : (240, 42)
Phi Shape        : (39, 882)
Top Words Rows   : 780
Topic Statistics :
      Topic  Documents
0   Topic_1          3
1  Topic_10          4
2  Topic_11         30
3  Topic_12          8
4  Topic_13          1
Training Fold 5  K=40
Finished in 4.69 seconds
============================================================
Fold: 5
K: 40
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (40, 882)
============================================================
Theta Shape      : (240, 43)
Phi Shape        : (40, 882)
Top Words Rows   : 800
Topic Statistics :
      Topic  Documents
0   Topic_1          2
1  Topic_10          1
2  Topic_11         21
3  Topic_12          6
4  Topic_13          1
Training Fold 5  K=41
Finished in 3.54 seconds
============================================================
Fold: 5
K: 41
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (41, 882)
============================================================
Theta Shape      : (240, 44)
Phi Shape        : (41, 882)
Top Words Rows   : 820
Topic Statistics :
      Topic  Documents
0   Topic_1          5
1  Topic_10          2
2  Topic_11         22
3  Topic_12          4
4  Topic_13          4
Training Fold 5  K=42
Finished in 4.86 seconds
============================================================
Fold: 5
K: 42
Dictionary Size : 882
Max Dictionary ID: 881
LDA Topic Matrix : (42, 882)
============================================================
Theta Shape      : (240, 45)
Phi Shape        : (42, 882)
Top Words Rows   : 840
Topic Statistics :
      Topic  Documents
0   Topic_1          3

In [146]:
overall_summary = pd.concat(
    all_fold_summaries,
    ignore_index=True
)

overall_summary_file = (
    MODEL_DIR /
    "training_summary_all_folds.csv"
)

overall_summary.to_csv(
    overall_summary_file,
    index=False
)

print("Overall summary saved.")
print(overall_summary.shape)

Overall summary saved.
(495, 7)

In [147]:
# ============================================================
# Overall Training Statistics
# ============================================================

print_line()
print("Overall Training Statistics")
print_line()

# ------------------------------------------------------------
# Calculate statistics
# ------------------------------------------------------------

total_models = len(overall_summary)

new_models = (
    overall_summary["Status"] == "Success"
).sum()

existing_models = (
    overall_summary["Status"] == "Already Exists"
).sum()

successful_models = new_models + existing_models

failed_models = (
    ~overall_summary["Status"].isin(
        ["Success", "Already Exists"]
    )
).sum()

average_training_time = (
    overall_summary["TrainingTime"]
    .dropna()
    .mean()
)

# ------------------------------------------------------------
# Print statistics
# ------------------------------------------------------------

print(f"Total Models             : {total_models}")

print(f"Newly Trained            : {new_models}")

print(f"Already Existing         : {existing_models}")

print(f"Successful Models        : {successful_models}")

print(f"Failed Models            : {failed_models}")

print()

print(
    f"Success Rate             : "
    f"{100 * successful_models / total_models:.2f}%"
)

print(
    f"Failure Rate             : "
    f"{100 * failed_models / total_models:.2f}%"
)

print()

if pd.notna(average_training_time):

    print(
        f"Average Training Time    : "
        f"{average_training_time:.2f} seconds/model"
    )

else:

    print(
        "Average Training Time    : N/A"
    )

print_line()

======================================================================
Overall Training Statistics
======================================================================
Total Models             : 495
Newly Trained            : 396
Already Existing         : 99
Successful Models        : 495
Failed Models            : 0

Success Rate             : 100.00%
Failure Rate             : 0.00%

Average Training Time    : 5.19 seconds/model
======================================================================

In [148]:
missing = []

for fold in range(1, NUM_FOLDS + 1):

    for K in range(
        MIN_TOPICS,
        MAX_TOPICS + 1
    ):

        model_dir = (
            MODEL_DIR /
            f"Fold_{fold}" /
            f"K_{K:03d}"
        )

        required = [

            "lda.model",

            "metadata.json",

            "theta_train.csv",

            "phi.csv",

            "topic_sizes.csv",

            "top_words.csv"

        ]

        for file in required:

            if not (model_dir / file).exists():

                missing.append(

                    [fold,K,file]

                )

missing_df = pd.DataFrame(

    missing,

    columns=[

        "Fold",

        "Topics",

        "Missing File"

    ]

)

print()

print("Missing Files")

print(len(missing_df))

missing_df.head()

Missing Files
0

Empty DataFrame
Columns: [Fold, Topics, Missing File]
Index: []

In [149]:
# ============================================================
# Save Validation Report and Experiment Summary
# ============================================================

# ------------------------------------------------------------
# Save validation report (CSV)
# ------------------------------------------------------------

validation_file = (
    MODEL_DIR /
    "validation_report.csv"
)

missing_df.to_csv(
    validation_file,
    index=False
)

print(f"Validation report saved to:\n{validation_file}")

# ------------------------------------------------------------
# Calculate experiment statistics
# ------------------------------------------------------------

total_models = len(overall_summary)

successful_models = (
    overall_summary["Status"]
    .isin(["Success", "Already Exists"])
    .sum()
)

failed_models = (
    ~overall_summary["Status"]
    .isin(["Success", "Already Exists"])
).sum()

average_training_time = float(
    overall_summary["TrainingTime"].mean()
)

# ------------------------------------------------------------
# Save experiment summary (JSON)
# ------------------------------------------------------------

experiment_summary = {

    # Dataset
    "n_folds": NUM_FOLDS,
    "min_topics": MIN_TOPICS,
    "max_topics": MAX_TOPICS,

    # Experiment statistics
    "total_models": total_models,
    "successful_models": int(successful_models),
    "failed_models": int(failed_models),

    # Performance
    "average_training_time_seconds":
        round(average_training_time, 4),

    # Validation
    "missing_output_files":
        int(len(missing_df)),

    #Date and Time of Experiment
    "completed_at":datetime.now().strftime("%Y-%m-%d %H:%M:%S"),

    # Notebook
    "created_by": "Notebook_03_Part3C"

}

experiment_summary_file = (
    MODEL_DIR /
    "experiment_summary.json"
)

with open(
    experiment_summary_file,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        experiment_summary,
        f,
        indent=4
    )

print(f"Experiment summary saved to:\n{experiment_summary_file}")

Validation report saved to:
/content/drive/MyDrive/TopicEvalBench/models/validation_report.csv
Experiment summary saved to:
/content/drive/MyDrive/TopicEvalBench/models/experiment_summary.json

In [150]:
# ============================================================
# Create Master Experiment Manifest
# ============================================================

manifest_rows = []

for fold in range(1, NUM_FOLDS + 1):

    for K in range(MIN_TOPICS, MAX_TOPICS + 1):

        model_dir = (
            MODEL_DIR /
            f"Fold_{fold}" /
            f"K_{K:03d}"
        )

        metadata_file = model_dir / "metadata.json"

        metadata = {}

        if metadata_file.exists():

            with open(
                metadata_file,
                "r",
                encoding="utf-8"
            ) as f:

                metadata = json.load(f)

            status = "Available"

        else:

            status = "Missing"

        manifest_rows.append({

            # =====================================================
            # Experiment Identification
            # =====================================================

            "ExperimentID": f"F{fold}_K{K:03d}",

            "Fold": fold,

            "Topics": K,

            "Status": status,

            # =====================================================
            # Dataset Information
            # =====================================================

            "TrainingDocuments":
                metadata.get("documents", np.nan),

            "DictionarySize":
                metadata.get("dictionary_size", np.nan),

            # =====================================================
            # LDA Hyperparameters
            # =====================================================

            "RandomSeed":
                metadata.get("random_seed", np.nan),

            "Passes":
                metadata.get("passes", np.nan),

            "Iterations":
                metadata.get("iterations", np.nan),

            "Alpha":
                metadata.get("alpha", np.nan),

            "Eta":
                metadata.get("eta", np.nan),

            # =====================================================
            # Training Statistics
            # =====================================================

            "TrainingTimeSeconds":
                metadata.get(
                    "training_time_seconds",
                    np.nan
                ),

            "LogPerplexityTrain":
                metadata.get(
                    "log_perplexity_train",
                    np.nan
                ),

            # =====================================================
            # Output Files
            # =====================================================

            "ModelDirectory":
                str(model_dir),

            "ModelFile":
                str(model_dir / "lda.model"),

            "MetadataFile":
                str(metadata_file),

            "ThetaTrainFile":
                str(model_dir / "theta_train.csv"),

            "ThetaTestFile": str(model_dir / "theta_test.csv"),


            "PhiFile":
                str(model_dir / "phi.csv"),

            "TopicSizesFile":
                str(model_dir / "topic_sizes.csv"),

            "TopWordsFile":
                str(model_dir / "top_words.csv")

        })

# ------------------------------------------------------------
# Create DataFrame
# ------------------------------------------------------------

manifest_df = pd.DataFrame(manifest_rows)

manifest_df = manifest_df.sort_values(
    by=["Fold", "Topics"]
).reset_index(drop=True)

# ------------------------------------------------------------
# Save Manifest
# ------------------------------------------------------------

manifest_file = (
    MODEL_DIR /
    "experiment_manifest.csv"
)

manifest_df.to_csv(
    manifest_file,
    index=False
)

# ------------------------------------------------------------
# Display Summary
# ------------------------------------------------------------

print_line()

print("Master Experiment Manifest Created")

print()

print(f"Manifest File : {manifest_file}")

print(f"Experiments   : {len(manifest_df)}")

print(f"Available     : {(manifest_df['Status'] == 'Available').sum()}")

print(f"Missing       : {(manifest_df['Status'] == 'Missing').sum()}")

print_line()

display(manifest_df.head())

======================================================================
Master Experiment Manifest Created

Manifest File : /content/drive/MyDrive/TopicEvalBench/models/experiment_manifest.csv
Experiments   : 495
Available     : 495
Missing       : 0
======================================================================

,ExperimentID,Fold,Topics,Status,TrainingDocuments,DictionarySize,RandomSeed,Passes,Iterations,Alpha,...,TrainingTimeSeconds,LogPerplexityTrain,ModelDirectory,ModelFile,MetadataFile,ThetaTrainFile,ThetaTestFile,PhiFile,TopicSizesFile,TopWordsFile
0,F1_K002,1,2,Available,240,891,42,20,400,"[0.5, 0.5]",...,3.3123,-6.298535,/content/drive/MyDrive/TopicEvalBench/models/F...,/content/drive/MyDrive/TopicEvalBench/models/F...,/content/drive/MyDrive/TopicEvalBench/models/F...,/content/drive/MyDrive/TopicEvalBench/models/F...,/content/drive/MyDrive/TopicEvalBench/models/F...,/content/drive/MyDrive/TopicEvalBench/models/F...,/content/drive/MyDrive/TopicEvalBench/models/F...,/content/drive/MyDrive/TopicEvalBench/models/F...
1,F1_K003,1,3,Available,240,891,42,20,400,"[0.3333333432674408, 0.3333333432674408, 0.333...",...,4.6282,-6.214306,/content/drive/MyDrive/TopicEvalBench/models/F...,/content/drive/MyDrive/TopicEvalBench/models/F...,/content/drive/MyDrive/TopicEvalBench/models/F...,/content/drive/MyDrive/TopicEvalBench/models/F...,/content/drive/MyDrive/TopicEvalBench/models/F...,/content/drive/MyDrive/TopicEvalBench/models/F...,/content/drive/MyDrive/TopicEvalBench/models/F...,/content/drive/MyDrive/TopicEvalBench/models/F...
2,F1_K004,1,4,Available,240,891,42,20,400,"[0.25, 0.25, 0.25, 0.25]",...,2.7942,-6.193754,/content/drive/MyDrive/TopicEvalBench/models/F...,/content/drive/MyDrive/TopicEvalBench/models/F...,/content/drive/MyDrive/TopicEvalBench/models/F...,/content/drive/MyDrive/TopicEvalBench/models/F...,/content/drive/MyDrive/TopicEvalBench/models/F...,/content/drive/MyDrive/TopicEvalBench/models/F...,/content/drive/MyDrive/TopicEvalBench/models/F...,/content/drive/MyDrive/TopicEvalBench/models/F...
3,F1_K005,1,5,Available,240,891,42,20,400,"[0.20000000298023224, 0.20000000298023224, 0.2...",...,6.0153,-6.191917,/content/drive/MyDrive/TopicEvalBench/models/F...,/content/drive/MyDrive/TopicEvalBench/models/F...,/content/drive/MyDrive/TopicEvalBench/models/F...,/content/drive/MyDrive/TopicEvalBench/models/F...,/content/drive/MyDrive/TopicEvalBench/models/F...,/content/drive/MyDrive/TopicEvalBench/models/F...,/content/drive/MyDrive/TopicEvalBench/models/F...,/content/drive/MyDrive/TopicEvalBench/models/F...
4,F1_K006,1,6,Available,240,891,42,20,400,"[0.1666666716337204, 0.1666666716337204, 0.166...",...,2.5762,-6.224693,/content/drive/MyDrive/TopicEvalBench/models/F...,/content/drive/MyDrive/TopicEvalBench/models/F...,/content/drive/MyDrive/TopicEvalBench/models/F...,/content/drive/MyDrive/TopicEvalBench/models/F...,/content/drive/MyDrive/TopicEvalBench/models/F...,/content/drive/MyDrive/TopicEvalBench/models/F...,/content/drive/MyDrive/TopicEvalBench/models/F...,/content/drive/MyDrive/TopicEvalBench/models/F...

In [151]:
print_line()

print("Notebook 3 Completed Successfully")

print()

print(f"Total Models : {len(overall_summary)}")

print()

print("Output Files Created")

print("""
✓ lda.model
✓ metadata.json
✓ theta_train.csv
✓ theta_test.csv
✓ phi.csv
✓ topic_sizes.csv
✓ top_words.csv
✓ training_summary.csv
✓ training_summary_all_folds.csv
✓ validation_report.csv
✓ experiment_manifest.csv
""")

print_line()

======================================================================
Notebook 3 Completed Successfully

Total Models : 495

Output Files Created

✓ lda.model
✓ metadata.json
✓ theta_train.csv
✓ theta_test.csv
✓ phi.csv
✓ topic_sizes.csv
✓ top_words.csv
✓ training_summary.csv
✓ training_summary_all_folds.csv
✓ validation_report.csv
✓ experiment_manifest.csv

======================================================================